### PR TITLE
CF-572 Migrate volumes to non-default backends

### PR DESCRIPTION
**Pull request by roman-verchikov**
Adds support to migrate cinder volumes to non-default cinder backends.
This resolves cinder migration issues when source cloud has NFS backend
but destination cloud has NFS and non-NFS backend, and non-NFS backend
is configured as default.

### CODE REVIEW

**Comment by SVilgelm** [comment]
👍

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.lib.utils.test_override
tests/lib/utils/test_override.py:16: [W0611(unused-import), ] Unused import mock

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3893/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
tested in staging, can be merged

**Pull request merged**
