### PR TITLE
[SAIC-820] Add boot_timeout option

### PR DESCRIPTION
**Pull request by SVilgelm**
Make a timeout value of checking is VM active configurable.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:773: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:773: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
