### PR TITLE
[CF-43] Move base exceptions to cloudferrylib.base.exception

### PR DESCRIPTION
**Pull request by vladiskuz**
Move TimeoutException from cloudferrylib.utils.timeout_exception to
cloudferrylib.base.exception.
Remove unused ChecksumImageInvalid from cloudferrylib.utils.utils.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib/utils/timeout_exception.py
cloudferrylib/utils/timeout_exception.py:1: [F0001(fatal), ] No module named cloudferrylib/utils/timeout_exception.py
************* Module cloudferrylib.base.exception
cloudferrylib/base/exception.py:31: [W0231(super-init-not-called), TimeoutException.__init__] __init__ method from base class 'Exception' is not called
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:219: [W0201(attribute-defined-outside-init), Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:240: [W0232(no-init), Templater] Class has no __init__ method
cloudferrylib/utils/utils.py:337: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'pid' defined outside __init__
cloudferrylib/utils/utils.py:338: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'ssh_auth_sock' defined outside __init__
cloudferrylib/utils/utils.py:397: [W0201(attribute-defined-outside-init), UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
cloudferrylib/utils/utils.py:424: [E1101(no-member), render_info] Instance of 'str' has no 'render' member
************* Module tests.cloudferrylib.os.compute.test_nova
tests/cloudferrylib/os/compute/test_nova.py:402: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:405: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:407: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:434: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:435: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:439: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:441: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:468: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:469: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:473: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:475: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib/utils/timeout_exception.py
cloudferrylib/utils/timeout_exception.py:1: [F0001(fatal), ] No module named cloudferrylib/utils/timeout_exception.py
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:219: [W0201(attribute-defined-outside-init), Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:240: [W0232(no-init), Templater] Class has no __init__ method
cloudferrylib/utils/utils.py:337: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'pid' defined outside __init__
cloudferrylib/utils/utils.py:338: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'ssh_auth_sock' defined outside __init__
cloudferrylib/utils/utils.py:397: [W0201(attribute-defined-outside-init), UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
cloudferrylib/utils/utils.py:424: [E1101(no-member), render_info] Instance of 'str' has no 'render' member
************* Module tests.cloudferrylib.os.compute.test_nova
tests/cloudferrylib/os/compute/test_nova.py:402: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:405: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:407: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:434: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:435: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:439: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:441: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:468: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:469: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:473: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:475: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
