### PR TITLE
[CF-279] Specify command to start bbcp on remote host

### PR DESCRIPTION
**Pull request by SVilgelm**
Add default ssh options to bbcp command.
Check a usage of copier for TaskTransfer action transfer a data.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by archyufa** [comment]
Failed at staging

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Comment by archyufa** [comment]
Worked on staging

**Pull request merged**
