### PR TITLE
SAIC-828 Add specific tests execution after each tenant migration.

### PR DESCRIPTION
**Pull request by plomakin**
Added nosetests attributes for specific tests.
Added lost licenses in files with tests.
Optimized imports in tests.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.test_vm_migration
devlab/tests/test_vm_migration.py:19: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_vm_migration.py:20: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:16: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:17: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:426: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:436: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.test_group_verification
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:21: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_group_verification.py:61: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/test_group_verification.py:97: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/test_group_verification.py:74: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/test_group_verification.py:80: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/test_group_verification.py:73: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/test_group_verification.py:108: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/test_group_verification.py:134: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/test_group_verification.py:186: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.test_vm_migration
devlab/tests/test_vm_migration.py:19: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_vm_migration.py:20: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:16: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:17: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:426: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:436: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.test_group_verification
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:21: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_group_verification.py:61: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/test_group_verification.py:97: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/test_group_verification.py:74: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/test_group_verification.py:80: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/test_group_verification.py:73: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/test_group_verification.py:108: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/test_group_verification.py:134: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/test_group_verification.py:186: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
@pavloivanets @ntymtsiv please review

**Comment by pavloivanets** [comment]
+1 looks good!

**Comment by ntymtsiv** [comment]
+1

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
