### PR TITLE
little fix for sec groups rule uploading

### PR DESCRIPTION
**Pull request by toha10**
Used wrong key for getting port_range_max parameter

### CODE REVIEW

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test success

**Comment by Wasapl** [comment]
Functional test success

**Comment by roman-verchikov** [comment]
+1

**Comment by roman-verchikov** [comment]
Can be merged.

**Pull request merged**
