### PR TITLE
CloudFerry Brochure README addition.

### PR DESCRIPTION
**Pull request by cburns-mirantis**
Redid this in devel branch and added README with instructions to convert latex files to rtf

### CODE REVIEW

**Comment by Settis** [comment]
Why are you use `psi` in list ?
fig001 does not fit the page. Please, resize it:
```latex
\resizebox{\textwidth}{!}{
\includegraphics[width=525pt, height=210pt, keepaspectratio=true]{images/CloudFerry_Brochure-fig001.jpg}
}
```

**Comment by roman-verchikov** [comment]
@cburns-mirantis please resolve comment

**Comment by roman-verchikov** [comment]
@cburns-mirantis please squash 3 commits into one

**Comment by roman-verchikov** [comment]
Moved to #464

**Pull request closed without merging**
