### PR TITLE
CF-466 Refactor parameter's validations for all OS objects.

### PR DESCRIPTION
**Pull request by plomakin**
* Change validation logic to not fail by the first found invalid object - make the list of invalid migrated objects
* Extend flavors parameters to check - move them to different test_file as different test cases for each parameter.
* Don't skip validation if src list is empty - fail it

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3483/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3494/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.tests.functional_test
cloudferry_devlab/cloudferry_devlab/tests/functional_test.py:95: 
[W0631(undefined-loop-variable), FunctionalTest.filter_subnets] Using possibly 
undefined loop variable 'subnet'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
$PYLINT_STATUS

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.tests.testcases.test_cinder_migration
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_cinder_migration.py:18: 
[E0401(import-error), ] Unable to import 'generator'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_cinder_migration.py:19: 
[E0401(import-error), ] Unable to import 'nose.plugins.attrib'
************* Module cloudferry_devlab.tests.testcases.test_flavors_migration
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_flavors_migration.py:15: 
[E0401(import-error), ] Unable to import 'generator'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_flavors_migration.py:16: 
[E0401(import-error), ] Unable to import 'nose.plugins.attrib'
************* Module cloudferry_devlab.tests.testcases.test_keystone_migration
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_keystone_migration.py:15: 
[E0401(import-error), ] Unable to import 'generator'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_keystone_migration.py:16: 
[E0401(import-error), ] Unable to import 'nose.plugins.attrib'
************* Module cloudferry_devlab.tests.testcases.test_glance_image_migration
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_glance_image_migration.py:17: 
[E0401(import-error), ] Unable to import 'generator'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_glance_image_migration.py:18: 
[E0401(import-error), ] Unable to import 'nose.plugins.attrib'
************* Module cloudferry_devlab.tests.testcases.test_lbaas_migration
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_lbaas_migration.py:15: 
[E0401(import-error), ] Unable to import 'generator'
************* Module cloudferry_devlab.tests.testcases.test_nova_resource_migration
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_nova_resource_migration.py:17: 
[E0401(import-error), ] Unable to import 'generator'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_nova_resource_migration.py:18: 
[E0401(import-error), ] Unable to import 'nose.plugins.attrib'
************* Module cloudferry_devlab.tests.testcases.test_networking_migration
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_networking_migration.py:18: 
[E0401(import-error), ] Unable to import 'generator'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_networking_migration.py:19: 
[E0401(import-error), ] Unable to import 'nose.plugins.attrib'
************* Module cloudferry_devlab.tests.functional_test
cloudferry_devlab/cloudferry_devlab/tests/functional_test.py:19: [E0401(import-error), 
] Unable to import 'keystoneclient'
cloudferry_devlab/cloudferry_devlab/tests/functional_test.py:20: [E0401(import-error), 
] Unable to import 'testconfig'
************* Module cloudferry_devlab.tests.testcases.test_vm_migration
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py:19: 
[E0401(import-error), ] Unable to import 'fabric.api'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py:20: 
[E0401(import-error), ] Unable to import 'fabric.network'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py:21: 
[E0401(import-error), ] Unable to import 'generator'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py:22: 
[E0401(import-error), ] Unable to import 'nose.plugins.attrib'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by jaspreetrawel** [comment]
@plomakin I rebuilt icehouse to juno, http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-icehouse-to-juno/2247/ has succeeded.

**Pull request merged**
