### PR TITLE
CF-206 Availability zone mapping

### PR DESCRIPTION
**Pull request by roman-verchikov**
Allows mapping availability zones from source cloud to destination when
some or none zones are present in the destination compared to source.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.cloudferrylib.os.compute.test_nova
tests/cloudferrylib/os/compute/test_nova.py:454: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:457: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:459: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:420: [W0613(unused-argument), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Unused argument 'azm'
tests/cloudferrylib/os/compute/test_nova.py:420: [W0613(unused-argument), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Unused argument 'ncl'
tests/cloudferrylib/os/compute/test_nova.py:489: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:490: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:494: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:496: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:466: [W0613(unused-argument), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Unused argument 'azm'
tests/cloudferrylib/os/compute/test_nova.py:466: [W0613(unused-argument), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Unused argument 'ncli'
tests/cloudferrylib/os/compute/test_nova.py:526: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:527: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:531: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:533: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:503: [W0613(unused-argument), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Unused argument 'azm'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.cloudferrylib.os.compute.test_nova
tests/cloudferrylib/os/compute/test_nova.py:454: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:457: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:459: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:420: [W0613(unused-argument), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Unused argument 'azm'
tests/cloudferrylib/os/compute/test_nova.py:420: [W0613(unused-argument), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Unused argument 'ncl'
tests/cloudferrylib/os/compute/test_nova.py:489: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:490: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:494: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:496: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:466: [W0613(unused-argument), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Unused argument 'azm'
tests/cloudferrylib/os/compute/test_nova.py:466: [W0613(unused-argument), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Unused argument 'ncli'
tests/cloudferrylib/os/compute/test_nova.py:526: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:527: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:531: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:533: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:503: [W0613(unused-argument), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Unused argument 'azm'

**Comment by SVilgelm** [comment]
I think the best is to wait #851 and re-use that code

**Comment by SVilgelm** [comment]
should be closed, #851 covers this problem.

**Pull request closed without merging**
