### PR TITLE
[SAIC-912] Wait volume to become available before delete

### PR DESCRIPTION
**Pull request by antonf**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:319: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
cloudferrylib/os/storage/cinder_storage.py:441: [W0221(arguments-differ), CinderNFSStorage.get_client] Arguments number differs from overridden 'get_client' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:319: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
cloudferrylib/os/storage/cinder_storage.py:441: [W0221(arguments-differ), CinderNFSStorage.get_client] Arguments number differs from overridden 'get_client' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:319: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
cloudferrylib/os/storage/cinder_storage.py:441: [W0221(arguments-differ), CinderNFSStorage.get_client] Arguments number differs from overridden 'get_client' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:319: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
cloudferrylib/os/storage/cinder_storage.py:441: [W0221(arguments-differ), CinderNFSStorage.get_client] Arguments number differs from overridden 'get_client' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
