### PR TITLE
[CF-21] Check mysql db password for db snapshot/restore commands

### PR DESCRIPTION
**Pull request by toha10**
This fix checks DB password and if it's empty, we are not using '--password' option for mysql and mysqldump commands.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:76: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:87: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
:-1: you have to check that the password is empty and prepare the command instead of replacing of password with empty string. Something like that:
```python
options = ["--user={user}", "--opt", "--all-databases"]
if self.cloud.cloud_config.mysql.db_password:
    options.append("--password={password}")
options = " ".join(options).format(user=..., password=...)
command = "mysqldump {options} > {path}".format(options=options, path=...)
```

**Comment by toha10** [comment]
@SVilgelm, yes i agree with you, because you're speaking about obvious solution. But i think that proposed logic, keeps command structure, i mean sequence of arguments (w/o extra formatting) and, based on tests, it uniquely solves the issue. Ok, i will rewrite the fix.

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:76: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:87: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:79: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:90: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:78: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:89: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
:+1: Thanks

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
