### PR TITLE
SAIC-136 test load improvements.

### PR DESCRIPTION
**Pull request by plomakin**
Expanded config.py with tenant's parameters.
Fixed logic in load generator.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by roman-verchikov** [comment]
This does not include cinder volumes generation, is it going to be done separately?

**Comment by plomakin** [comment]
@roman-verchikov yes, cinder will be included in another pull-reqests, it is also different task for this: SAIC-173

**Comment by miarmak** [comment]
Looks good. +1

**Comment by roman-verchikov** [comment]
+1

**Pull request merged**
