### PR TITLE
[DONT'T MERGE]Fix pylint issues in func tests

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.functional_test
devlab/tests/functional_test.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/functional_test.py:20: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/functional_test.py:21: [W0403(relative-import), ] Relative import 'filtering_utils', should be 'tests.filtering_utils'
devlab/tests/functional_test.py:28: [F0401(import-error), ] Unable to import 'cfglib'
************* Module tests.test_group_verification
devlab/tests/test_group_verification.py:67: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:67: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:67: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:67: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:67: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:67: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:67: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/test_group_verification.py:19: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
************* Module tests.generate_load
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:9: [W0403(relative-import), ] Relative import 'filtering_utils', should be 'tests.filtering_utils'
devlab/tests/generate_load.py:953: [W0120(useless-else-on-loop), CleanEnv.clean_vms.wait_until_vms_all_deleted] Else clause on loop without a break statement

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1512/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.functional_test
devlab/tests/functional_test.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/functional_test.py:20: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/functional_test.py:21: [W0403(relative-import), ] Relative import 'filtering_utils', should be 'tests.filtering_utils'
devlab/tests/functional_test.py:28: [F0401(import-error), ] Unable to import 'cfglib'
************* Module tests.test_group_verification
devlab/tests/test_group_verification.py:19: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
************* Module tests.generate_load
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:9: [W0403(relative-import), ] Relative import 'filtering_utils', should be 'tests.filtering_utils'
devlab/tests/generate_load.py:953: [W0120(useless-else-on-loop), CleanEnv.clean_vms.wait_until_vms_all_deleted] Else clause on loop without a break statement

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Please either finish the task, or close the pull request and reopen when it's fully resolved.

**Comment by roman-verchikov** [comment]
@ntymtsiv According to pylint report this looks not finished. Please either finish it or close.

**Comment by roman-verchikov** [comment]
Closing until it resolved

**Pull request closed without merging**
