### PR TITLE
Changes to config.ini in development branch

### PR DESCRIPTION
**Pull request by oleksii-shyman**
- changes according to vagrant devlab
  - added keystone/mysql settings
  - disabled swift usage in configs (depends on SAIC-66)

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/165/

**Comment by miarmak** [comment]
I guess we need to create separate config for such purposes, because config.ini supposed to be smth like a config template without any specific information.

**Comment by oleksii-shyman** [comment]
From one side - it is fine as soon as we are in devel branch
from other side - we will have problems in the future when we will merge changes to master branch (because we will have to exclude commit from history and it will break our fast-forward merge plan)

**Comment by miarmak** [comment]
Why do we need exclude any commits now? We can make smth like configs/devlab_config.ini and merge it to master too.

**Pull request closed without merging**
