### PR TITLE
Print filters

### PR DESCRIPTION
**Pull request by SVilgelm**
Add the printing filters action into migrate_vms and
3_get_and_transfer_images scenarios to easy debugging.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by miarmak** [comment]
Maybe we need to add this action to all related scenarios?

**Comment by roman-verchikov** [comment]
Let's either add these changes to all scenarios or close pull request

**Pull request closed without merging**
