### PR TITLE
[SAIC-780] Skip the broken images

### PR DESCRIPTION
**Pull request by SVilgelm**
Raise ImageDownloadError instead of IncompleteRead exception.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.file_like_proxy
cloudferrylib/utils/file_like_proxy.py:21: [W0403(relative-import), ] Relative import 'utils', should be 'cloudferrylib.utils.utils'
cloudferrylib/utils/file_like_proxy.py:60: [W0141(bad-builtin), FileLikeProxy._parse_speed_limit] Used builtin function 'filter'. Using a list comprehension can be clearer.
cloudferrylib/utils/file_like_proxy.py:81: [E0202(method-hidden), FileLikeProxy.read] An attribute defined in cloudferrylib.utils.file_like_proxy line 44 hides this method
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:158: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:239: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:280: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:291: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:294: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:304: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/image/glance_image.py:352: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:358: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:367: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:370: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:390: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:417: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:444: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:158: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:239: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:280: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:291: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:294: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:304: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/image/glance_image.py:352: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:358: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:367: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:370: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:390: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:417: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:444: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.cloudferrylib.utils.test_file_like_proxy
tests/cloudferrylib/utils/test_file_like_proxy.py:22: [E1002(super-on-old-class), FileLikeProxyTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/utils/test_file_like_proxy.py:26: [W0212(protected-access), FileLikeProxyTestCase.test_parse_speed_limit_off] Access to a protected member _parse_speed_limit of a client class
tests/cloudferrylib/utils/test_file_like_proxy.py:31: [W0212(protected-access), FileLikeProxyTestCase.test_parse_speed_limit_incorrect] Access to a protected member _parse_speed_limit of a client class
tests/cloudferrylib/utils/test_file_like_proxy.py:36: [W0212(protected-access), FileLikeProxyTestCase.test_parse_speed_limit_number] Access to a protected member _parse_speed_limit of a client class
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:158: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:239: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:280: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:291: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:294: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:304: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/image/glance_image.py:352: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:358: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:367: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:370: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:390: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:417: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:444: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.file_like_proxy
cloudferrylib/utils/file_like_proxy.py:19: [W0611(unused-import), ] Unused exception imported from cloudferrylib.base
************* Module tests.cloudferrylib.utils.test_file_like_proxy
tests/cloudferrylib/utils/test_file_like_proxy.py:22: [E1002(super-on-old-class), FileLikeProxyTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/utils/test_file_like_proxy.py:26: [W0212(protected-access), FileLikeProxyTestCase.test_parse_speed_limit_off] Access to a protected member _parse_speed_limit of a client class
tests/cloudferrylib/utils/test_file_like_proxy.py:31: [W0212(protected-access), FileLikeProxyTestCase.test_parse_speed_limit_incorrect] Access to a protected member _parse_speed_limit of a client class
tests/cloudferrylib/utils/test_file_like_proxy.py:36: [W0212(protected-access), FileLikeProxyTestCase.test_parse_speed_limit_number] Access to a protected member _parse_speed_limit of a client class
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:159: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:240: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:281: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:292: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:295: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:305: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/image/glance_image.py:353: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:359: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:368: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:371: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:391: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:418: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:448: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:159: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:240: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:281: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:292: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:295: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:305: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/image/glance_image.py:353: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:359: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:368: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:371: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:391: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:418: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:448: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions and pass the % parameters as arguments

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Pull request merged**
