### PR TITLE
Optimized imports in testcases and test classes.

### PR DESCRIPTION
**Pull request by plomakin**
Added import optimization for test classes.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.data_collector
devlab/tests/data_collector.py:20: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/data_collector.py:21: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/data_collector.py:22: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.functional_test
devlab/tests/functional_test.py:21: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/functional_test.py:22: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/functional_test.py:23: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/functional_test.py:24: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/functional_test.py:186: [W0106(expression-not-assigned), FunctionalTest.filter_volumes] Expression "[volumes.extend(i['cinder_volumes']) for i in config.tenants if ('cinder_volumes' in i) and (not i.get('deleted'))]" is assigned to nothing
devlab/tests/functional_test.py:236: [W0106(expression-not-assigned), FunctionalTest.get_vms_with_fip_associated] Expression "[vms.extend(i['vms']) for i in config.tenants if 'vms' in i]" is assigned to nothing
************* Module tests.rollback_scenario_generation
devlab/tests/rollback_scenario_generation.py:27: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/rollback_scenario_generation.py:55: [W0612(unused-variable), RollbackScenarioGeneration._get_list_of_tasks] Unused variable 'key'
devlab/tests/rollback_scenario_generation.py:66: [W0612(unused-variable), RollbackScenarioGeneration._insert_break_point] Unused variable 'key'
************* Module tests.base
devlab/tests/base.py:22: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/base.py:23: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
************* Module tests.generate_load_real_env
devlab/tests/generate_load_real_env.py:4: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/generate_load_real_env.py:5: [W0403(relative-import), ] Relative import 'real_env_conf', should be 'tests.real_env_conf'
devlab/tests/generate_load_real_env.py:11: [E1120(no-value-for-parameter), Prerequisites.update_vm_status] No value for argument 'configuration_ini' in constructor call
devlab/tests/generate_load_real_env.py:26: [W0703(broad-except), Prerequisites.create_keypairs] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:61: [W0221(arguments-differ), Prerequisites.create_networks] Arguments number differs from overridden 'create_networks' method
devlab/tests/generate_load_real_env.py:70: [E1101(no-member), Prerequisites.create_all_networking] Instance of 'Prerequisites' has no 'create_router' member
devlab/tests/generate_load_real_env.py:86: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'Prerequisites' has no 'wait_for_volume' member
devlab/tests/generate_load_real_env.py:90: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member
devlab/tests/generate_load_real_env.py:92: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'Prerequisites' has no 'wait_for_volume' member
devlab/tests/generate_load_real_env.py:150: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:156: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:162: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:170: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:176: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:183: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:189: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:195: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:202: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:211: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:219: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:227: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:233: [E1120(no-value-for-parameter), ] No value for argument 'configuration_ini' in constructor call
************* Module tests.testcases.test_group_verification
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:63: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/testcases/test_group_verification.py:99: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/testcases/test_group_verification.py:76: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:82: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:75: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:110: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:136: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/testcases/test_group_verification.py:191: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:374: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:374: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:669: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:679: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.utils
devlab/tests/utils.py:24: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/utils.py:34: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:36: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:135: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.
************* Module tests.generate_load
devlab/tests/generate_load.py:27: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:28: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/generate_load.py:29: [W0403(relative-import), ] Relative import 'cleanup', should be 'tests.cleanup'
devlab/tests/generate_load.py:594: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:668: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Would also be good to resolve all pylint issues related to imports

**Comment by plomakin** [comment]
yes, for sure.

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.functional_test
devlab/tests/functional_test.py:186: [W0106(expression-not-assigned), FunctionalTest.filter_volumes] Expression "[volumes.extend(i['cinder_volumes']) for i in config.tenants if ('cinder_volumes' in i) and (not i.get('deleted'))]" is assigned to nothing
devlab/tests/functional_test.py:236: [W0106(expression-not-assigned), FunctionalTest.get_vms_with_fip_associated] Expression "[vms.extend(i['vms']) for i in config.tenants if 'vms' in i]" is assigned to nothing
************* Module tests.rollback_scenario_generation
devlab/tests/rollback_scenario_generation.py:55: [W0612(unused-variable), RollbackScenarioGeneration._get_list_of_tasks] Unused variable 'key'
devlab/tests/rollback_scenario_generation.py:66: [W0612(unused-variable), RollbackScenarioGeneration._insert_break_point] Unused variable 'key'
************* Module tests.generate_load_real_env
devlab/tests/generate_load_real_env.py:25: [E1120(no-value-for-parameter), Prerequisites.update_vm_status] No value for argument 'configuration_ini' in constructor call
devlab/tests/generate_load_real_env.py:40: [W0703(broad-except), Prerequisites.create_keypairs] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:75: [W0221(arguments-differ), Prerequisites.create_networks] Arguments number differs from overridden 'create_networks' method
devlab/tests/generate_load_real_env.py:84: [E1101(no-member), Prerequisites.create_all_networking] Instance of 'Prerequisites' has no 'create_router' member
devlab/tests/generate_load_real_env.py:100: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'Prerequisites' has no 'wait_for_volume' member
devlab/tests/generate_load_real_env.py:104: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member
devlab/tests/generate_load_real_env.py:106: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'Prerequisites' has no 'wait_for_volume' member
devlab/tests/generate_load_real_env.py:164: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:170: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:176: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:184: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:190: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:197: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:203: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:209: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:216: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:225: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:233: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:241: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:247: [E1120(no-value-for-parameter), ] No value for argument 'configuration_ini' in constructor call
************* Module tests.testcases.test_group_verification
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:63: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/testcases/test_group_verification.py:99: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/testcases/test_group_verification.py:76: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:82: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:75: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:110: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:136: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/testcases/test_group_verification.py:191: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:374: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:374: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:669: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:679: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.generate_load
devlab/tests/generate_load.py:594: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:668: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member
************* Module tests.utils
devlab/tests/utils.py:34: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:36: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:135: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.functional_test
devlab/tests/functional_test.py:186: [W0106(expression-not-assigned), FunctionalTest.filter_volumes] Expression "[volumes.extend(i['cinder_volumes']) for i in config.tenants if ('cinder_volumes' in i) and (not i.get('deleted'))]" is assigned to nothing
devlab/tests/functional_test.py:236: [W0106(expression-not-assigned), FunctionalTest.get_vms_with_fip_associated] Expression "[vms.extend(i['vms']) for i in config.tenants if 'vms' in i]" is assigned to nothing
************* Module tests.rollback_scenario_generation
devlab/tests/rollback_scenario_generation.py:55: [W0612(unused-variable), RollbackScenarioGeneration._get_list_of_tasks] Unused variable 'key'
devlab/tests/rollback_scenario_generation.py:66: [W0612(unused-variable), RollbackScenarioGeneration._insert_break_point] Unused variable 'key'
************* Module tests.generate_load_real_env
devlab/tests/generate_load_real_env.py:25: [E1120(no-value-for-parameter), Prerequisites.update_vm_status] No value for argument 'configuration_ini' in constructor call
devlab/tests/generate_load_real_env.py:40: [W0703(broad-except), Prerequisites.create_keypairs] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:75: [W0221(arguments-differ), Prerequisites.create_networks] Arguments number differs from overridden 'create_networks' method
devlab/tests/generate_load_real_env.py:84: [E1101(no-member), Prerequisites.create_all_networking] Instance of 'Prerequisites' has no 'create_router' member
devlab/tests/generate_load_real_env.py:100: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'Prerequisites' has no 'wait_for_volume' member
devlab/tests/generate_load_real_env.py:104: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member
devlab/tests/generate_load_real_env.py:106: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'Prerequisites' has no 'wait_for_volume' member
devlab/tests/generate_load_real_env.py:164: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:170: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:176: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:184: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:190: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:197: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:203: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:209: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:216: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:225: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:233: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:241: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:247: [E1120(no-value-for-parameter), ] No value for argument 'configuration_ini' in constructor call
************* Module tests.testcases.test_group_verification
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:68: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:63: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/testcases/test_group_verification.py:99: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/testcases/test_group_verification.py:76: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:82: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:75: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:110: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:136: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/testcases/test_group_verification.py:191: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__
************* Module tests.utils
devlab/tests/utils.py:34: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:36: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:135: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.
************* Module tests.generate_load
devlab/tests/generate_load.py:27: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:28: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/generate_load.py:29: [W0403(relative-import), ] Relative import 'cleanup', should be 'tests.cleanup'
devlab/tests/generate_load.py:594: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:668: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:374: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:374: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:669: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:679: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Pull request closed without merging**
