### PR TITLE
SAIC-302 Neutron migration logging

### PR DESCRIPTION
**Pull request by roman-verchikov**
Adds logging information to neutron migration process

### CODE REVIEW

**Comment by Settis** [comment]
Good! Especially `tenants_on_src_and_dst_dont_match`. +1

**Comment by roman-verchikov** [comment]
>  Settis commented 7 hours ago
> Good! Especially tenants_on_src_and_dst_dont_match. +1

Readable code is our all!

**Comment by roman-verchikov** [comment]
Jenkins slave conflicts again:
```
>>> Creating networking:
Traceback (most recent call last):
  File "generate_load.py", line 577, in <module>
    preqs.run_preparation_scenario()
  File "generate_load.py", line 440, in run_preparation_scenario
    self.create_all_networking()
  File "generate_load.py", line 292, in create_all_networking
    self.create_networks(config.networks, config.subnets)
  File "generate_load.py", line 282, in create_networks
    self.neutronclient.create_subnet({'subnet': subnet})
  File "/home/jenkins/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/neutronclient/v2_0/client.py", line 111, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/home/jenkins/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/neutronclient/v2_0/client.py", line 369, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/home/jenkins/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/neutronclient/v2_0/client.py", line 1241, in post
    headers=headers, params=params)
  File "/home/jenkins/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/neutronclient/v2_0/client.py", line 1164, in do_request
    self._handle_fault_response(status_code, replybody)
  File "/home/jenkins/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/neutronclient/v2_0/client.py", line 1134, in _handle_fault_response
    exception_handler_v20(status_code, des_error_body)
  File "/home/jenkins/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/neutronclient/v2_0/client.py", line 96, in exception_handler_v20
    message=msg)
neutronclient.common.exceptions.NeutronClientException: 400-{u'QuantumError': u'Invalid input for operation: Requested subnet with cidr: 172.18.10.0/24 for network: c158b488-0c3b-45f3-a1f3-ae65774834cd overlaps with another subnet.'}
```

**Comment by miarmak** [comment]
Looks good. +1

**Comment by roman-verchikov** [comment]
Got two +1s, functional tests succeed, can  be merged.

**Pull request merged**
