### PR TITLE
Get cloud config

### PR DESCRIPTION
**Pull request by ShaikhAliJabbar**
With the help of scripts we will get source and destination Cloud credentials that will be helpful to update configuration.ini

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloud_conf
getCloudCredentials/cloud_conf.py:6: [W0611(unused-import), ] Unused import re
getCloudCredentials/cloud_conf.py:10: [W0611(unused-import), ] Unused env imported from 
fabric.api

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3292/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3294/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloud_conf
getCloudCredentials/cloud_conf.py:6: [W0611(unused-import), ] Unused import re

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3296/

**Comment by SVilgelm** [comment]
What is it? Why do we need it in the CloudFerry? If you so want to get some credentials and prepare configuration.ini automatically, please use  [crudini](https://github.com/pixelb/crudini) tool.

**Comment by SVilgelm** [comment]
👎 We will not merge this to the CloudFerry repo

**Pull request closed without merging**
