### PR TITLE
CF-26 SNAT support for external routers

### PR DESCRIPTION
**Pull request by roman-verchikov**
Adds support for SNAT property of external routers which was introduced
in icehouse release of neutron.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2149/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:18: [E0401(import-error), ] Unable to import 'ipaddr'
cloudferrylib/os/network/neutron.py:19: [E0401(import-error), ] Unable to import 'netaddr'
cloudferrylib/os/network/neutron.py:21: [E0401(import-error), ] Unable to import 'neutronclient.common'
cloudferrylib/os/network/neutron.py:22: [E0401(import-error), ] Unable to import 'neutronclient.v2_0'
cloudferrylib/os/network/neutron.py:180: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:285: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:814: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:180: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:285: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:814: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
+1, tested on devlab

**Comment by roman-verchikov** [comment]
Can be merged

**Pull request merged**
