### PR TITLE
[SAIC-11] Pre-migration smoke test

### PR DESCRIPTION
**Pull request by Settis**
Here is ready for merge pull request https://github.com/MirantisWorkloadMobility/CloudFerry/pull/112

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test FAILed.   http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/121/

**Comment by miarmak** [comment]
I guess we have 3 'yes' for this patch.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/127/

**Comment by miarmak** [comment]
Ok, Tests finally passed)

**Pull request merged**
