### PR TITLE
SAIC-790 Automated test for router migration

### PR DESCRIPTION
**Pull request by plomakin**
Added user's routers generation.
Reworked network topologies for tenants.
Added test to check router presents once.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.functional_test
devlab/tests/functional_test.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/functional_test.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/functional_test.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/functional_test.py:23: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/functional_test.py:31: [E0401(import-error), ] Unable to import 'cfglib'
devlab/tests/functional_test.py:190: [W0106(expression-not-assigned), FunctionalTest.filter_volumes] Expression "[volumes.extend(i['cinder_volumes']) for i in config.tenants if ('cinder_volumes' in i) and (not i.get('deleted'))]" is assigned to nothing
devlab/tests/functional_test.py:216: [W0106(expression-not-assigned), FunctionalTest.get_vms_with_fip_associated] Expression "[vms.extend(i['vms']) for i in config.tenants if 'vms' in i]" is assigned to nothing
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:1: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:2: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:3: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:396: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:406: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.generate_load
devlab/tests/generate_load.py:8: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:9: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/generate_load.py:23: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/generate_load.py:730: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:804: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.functional_test
devlab/tests/functional_test.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/functional_test.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/functional_test.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/functional_test.py:23: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/functional_test.py:31: [E0401(import-error), ] Unable to import 'cfglib'
devlab/tests/functional_test.py:190: [W0106(expression-not-assigned), FunctionalTest.filter_volumes] Expression "[volumes.extend(i['cinder_volumes']) for i in config.tenants if ('cinder_volumes' in i) and (not i.get('deleted'))]" is assigned to nothing
devlab/tests/functional_test.py:216: [W0106(expression-not-assigned), FunctionalTest.get_vms_with_fip_associated] Expression "[vms.extend(i['vms']) for i in config.tenants if 'vms' in i]" is assigned to nothing
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:1: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:2: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:3: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:396: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:406: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.generate_load
devlab/tests/generate_load.py:8: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:9: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/generate_load.py:23: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/generate_load.py:730: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:804: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
+1, looks good

**Comment by plomakin** [comment]
@pavloivanets pls, review

**Comment by pavloivanets** [comment]
+1, looks ok

**Comment by plomakin** [comment]
@roman-verchikov this one can be merged

**Pull request merged**
