### PR TITLE
[CF-399] Use print_filter_raw action instead of print_filter

### PR DESCRIPTION
**Pull request by SVilgelm**
print_filter action requires parsed filter.yaml, it means
act_get_filter action should be executed before print_filter.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
$PYLINT_STATUS

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
$PYLINT_STATUS

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by roman-verchikov** [comment]
-2. This needs to be done in a more generic way: filter config should be read regardless of what's in scenario file. Closing for now.

**Pull request closed without merging**
