### PR TITLE
Changes in Vagrantfiles

### PR DESCRIPTION
**Pull request by yuvb**
Added link to new openstack boxes and deleted all unused strings.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3990/

**Comment by roman-verchikov** [comment]
pull request should only have one commit, please rebase your changes on top of latest devel and upload

**Comment by plomakin** [comment]
```
git pull --rebase origin devel
```

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.scheduler.test_scheduler
tests/scheduler/test_scheduler.py:36: [E1136(unsubscriptable-object), 
SchedulerTestCase.test_start_scheduler] Value 's.event_start_task.call_args' is 
unsubscriptable
tests/scheduler/test_scheduler.py:38: [E1136(unsubscriptable-object), 
SchedulerTestCase.test_start_scheduler] Value 's.event_end_task.call_args' is 
unsubscriptable

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3997/

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/4000/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.scheduler.test_scheduler
tests/scheduler/test_scheduler.py:36: [E1136(unsubscriptable-object), 
SchedulerTestCase.test_start_scheduler] Value 's.event_start_task.call_args' is 
unsubscriptable
tests/scheduler/test_scheduler.py:38: [E1136(unsubscriptable-object), 
SchedulerTestCase.test_start_scheduler] Value 's.event_end_task.call_args' is 
unsubscriptable

**Comment by roman-verchikov** [comment]
Moved to #1111

**Pull request closed without merging**
