### PR TITLE
[CF-177] Add start/end task messages into log

### PR DESCRIPTION
**Pull request by SVilgelm**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.scheduler.scheduler
cloudferrylib/scheduler/scheduler.py:25: [W0403(relative-import), ] Relative import 'cursor', should be 'cloudferrylib.scheduler.cursor'
cloudferrylib/scheduler/scheduler.py:26: [W0403(relative-import), ] Relative import 'signal_handler', should be 'cloudferrylib.scheduler.signal_handler'
cloudferrylib/scheduler/scheduler.py:27: [W0403(relative-import), ] Relative import 'task', should be 'cloudferrylib.scheduler.task'
cloudferrylib/scheduler/scheduler.py:28: [W0403(relative-import), ] Relative import 'thread_tasks', should be 'cloudferrylib.scheduler.thread_tasks'
cloudferrylib/scheduler/scheduler.py:60: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'task'
cloudferrylib/scheduler/scheduler.py:60: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'e'
cloudferrylib/scheduler/scheduler.py:78: [W0703(broad-except), BaseScheduler.process_chain] Catching too general exception Exception
cloudferrylib/scheduler/scheduler.py:87: [W0201(attribute-defined-outside-init), BaseScheduler.process_chain] Attribute 'exception' defined outside __init__
cloudferrylib/scheduler/scheduler.py:110: [W0201(attribute-defined-outside-init), BaseScheduler.addCursor] Attribute 'cursor' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, @archyufa please confirm if that's good enough

**Comment by archyufa** [comment]
+1

**Pull request merged**
