### PR TITLE
Added an ability for using multiple ssh keys

### PR DESCRIPTION
**Pull request by toha10**
Now we can use several ssh private keys, f.e. different keys for
source and destinashion clouds.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:72: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:83: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:148: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:151: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:166: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:174: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:181: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:185: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:187: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:191: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:195: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:219: [W0201(attribute-defined-outside-init), Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:240: [W0232(no-init), Templater] Class has no __init__ method
cloudferrylib/utils/utils.py:260: [W0613(unused-argument), get_log] Unused argument 'name'
cloudferrylib/utils/utils.py:351: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'pid' defined outside __init__
cloudferrylib/utils/utils.py:352: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'ssh_auth_sock' defined outside __init__
cloudferrylib/utils/utils.py:411: [W0201(attribute-defined-outside-init), UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
cloudferrylib/utils/utils.py:435: [W0231(super-init-not-called), ChecksumImageInvalid.__init__] __init__ method from base class 'Exception' is not called
cloudferrylib/utils/utils.py:441: [E1305(too-many-format-args), ChecksumImageInvalid.__str__] Too many arguments for format string
cloudferrylib/utils/utils.py:449: [E1101(no-member), render_info] Instance of 'str' has no 'render' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1453/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1454/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:72: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:83: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:148: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:151: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:166: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:174: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:181: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:185: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:187: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:191: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:195: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:219: [W0201(attribute-defined-outside-init), Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:240: [W0232(no-init), Templater] Class has no __init__ method
cloudferrylib/utils/utils.py:260: [W0613(unused-argument), get_log] Unused argument 'name'
cloudferrylib/utils/utils.py:351: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'pid' defined outside __init__
cloudferrylib/utils/utils.py:352: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'ssh_auth_sock' defined outside __init__
cloudferrylib/utils/utils.py:411: [W0201(attribute-defined-outside-init), UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
cloudferrylib/utils/utils.py:435: [W0231(super-init-not-called), ChecksumImageInvalid.__init__] __init__ method from base class 'Exception' is not called
cloudferrylib/utils/utils.py:441: [E1305(too-many-format-args), ChecksumImageInvalid.__str__] Too many arguments for format string
cloudferrylib/utils/utils.py:449: [E1101(no-member), render_info] Instance of 'str' has no 'render' member

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:72: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:83: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:148: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:151: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:166: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:174: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:181: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:185: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:187: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:191: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:195: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:219: [W0201(attribute-defined-outside-init), Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:240: [W0232(no-init), Templater] Class has no __init__ method
cloudferrylib/utils/utils.py:260: [W0613(unused-argument), get_log] Unused argument 'name'
cloudferrylib/utils/utils.py:351: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'pid' defined outside __init__
cloudferrylib/utils/utils.py:352: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'ssh_auth_sock' defined outside __init__
cloudferrylib/utils/utils.py:411: [W0201(attribute-defined-outside-init), UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
cloudferrylib/utils/utils.py:435: [W0231(super-init-not-called), ChecksumImageInvalid.__init__] __init__ method from base class 'Exception' is not called
cloudferrylib/utils/utils.py:441: [E1305(too-many-format-args), ChecksumImageInvalid.__str__] Too many arguments for format string
cloudferrylib/utils/utils.py:449: [E1101(no-member), render_info] Instance of 'str' has no 'render' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1455/

**Comment by MirantisWorkloadMobility** [comment]
Ready

**Comment by toha10** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:72: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:83: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:148: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:151: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:166: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:174: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:181: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:185: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:187: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:191: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:195: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:219: [W0201(attribute-defined-outside-init), Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:240: [W0232(no-init), Templater] Class has no __init__ method
cloudferrylib/utils/utils.py:260: [W0613(unused-argument), get_log] Unused argument 'name'
cloudferrylib/utils/utils.py:351: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'pid' defined outside __init__
cloudferrylib/utils/utils.py:352: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'ssh_auth_sock' defined outside __init__
cloudferrylib/utils/utils.py:411: [W0201(attribute-defined-outside-init), UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
cloudferrylib/utils/utils.py:435: [W0231(super-init-not-called), ChecksumImageInvalid.__init__] __init__ method from base class 'Exception' is not called
cloudferrylib/utils/utils.py:441: [E1305(too-many-format-args), ChecksumImageInvalid.__str__] Too many arguments for format string
cloudferrylib/utils/utils.py:449: [E1101(no-member), render_info] Instance of 'str' has no 'render' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by toha10** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:72: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:83: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:148: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:151: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:166: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:174: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:181: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:185: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:187: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:191: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:195: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:219: [W0201(attribute-defined-outside-init), Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:240: [W0232(no-init), Templater] Class has no __init__ method
cloudferrylib/utils/utils.py:260: [W0613(unused-argument), get_log] Unused argument 'name'
cloudferrylib/utils/utils.py:351: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'pid' defined outside __init__
cloudferrylib/utils/utils.py:352: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'ssh_auth_sock' defined outside __init__
cloudferrylib/utils/utils.py:411: [W0201(attribute-defined-outside-init), UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
cloudferrylib/utils/utils.py:435: [W0231(super-init-not-called), ChecksumImageInvalid.__init__] __init__ method from base class 'Exception' is not called
cloudferrylib/utils/utils.py:441: [E1305(too-many-format-args), ChecksumImageInvalid.__str__] Too many arguments for format string
cloudferrylib/utils/utils.py:449: [E1101(no-member), render_info] Instance of 'str' has no 'render' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Please add unit tests to cover the new logic

**Comment by toha10** [comment]
@roman-verchikov It's not a new logic, we just use underlying OpenSSH functionality that can't be tested in CF. Please, correct me if i'm wrong.

**Comment by roman-verchikov** [comment]
`_agent_already_running()` logic was modified, so it's new compared to what we had previously, so it needs to be covered with unit tests.

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.snapshots
cloudferrylib/os/actions/snapshots.py:72: [W1202(logging-format-interpolation), MysqlDump.run] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/actions/snapshots.py:44: [W0613(unused-argument), MysqlDump.run] Unused argument 'args'
cloudferrylib/os/actions/snapshots.py:83: [W0613(unused-argument), MysqlRestore.run] Unused argument 'args'
************* Module tests.cloudferrylib.utils.test_utils
tests/cloudferrylib/utils/test_utils.py:33: [E1101(no-member), forward_agentTestCase.test_agent_is_already_run_w_keys] Instance of 'forward_agentTestCase' has no 'assertTrue' member
tests/cloudferrylib/utils/test_utils.py:33: [W0212(protected-access), forward_agentTestCase.test_agent_is_already_run_w_keys] Access to a protected member _agent_already_running of a client class
tests/cloudferrylib/utils/test_utils.py:43: [E1101(no-member), forward_agentTestCase.test_agent_is_not_run] Instance of 'forward_agentTestCase' has no 'assertFalse' member
tests/cloudferrylib/utils/test_utils.py:43: [W0212(protected-access), forward_agentTestCase.test_agent_is_not_run] Access to a protected member _agent_already_running of a client class
tests/cloudferrylib/utils/test_utils.py:53: [E1101(no-member), forward_agentTestCase.test_agent_is_already_run_w_another_key] Instance of 'forward_agentTestCase' has no 'assertFalse' member
tests/cloudferrylib/utils/test_utils.py:53: [W0212(protected-access), forward_agentTestCase.test_agent_is_already_run_w_another_key] Access to a protected member _agent_already_running of a client class
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:148: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:151: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:166: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:174: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:181: [W1504(unidiomatic-typecheck), convert_to_dict] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:185: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:187: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:191: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:195: [W1504(unidiomatic-typecheck), convert_to_obj] Using type() instead of isinstance() for a typecheck.
cloudferrylib/utils/utils.py:219: [W0201(attribute-defined-outside-init), Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:240: [W0232(no-init), Templater] Class has no __init__ method
cloudferrylib/utils/utils.py:260: [W0613(unused-argument), get_log] Unused argument 'name'
cloudferrylib/utils/utils.py:351: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'pid' defined outside __init__
cloudferrylib/utils/utils.py:352: [W0201(attribute-defined-outside-init), forward_agent.__enter__] Attribute 'ssh_auth_sock' defined outside __init__
cloudferrylib/utils/utils.py:411: [W0201(attribute-defined-outside-init), UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
cloudferrylib/utils/utils.py:435: [W0231(super-init-not-called), ChecksumImageInvalid.__init__] __init__ method from base class 'Exception' is not called
cloudferrylib/utils/utils.py:441: [E1305(too-many-format-args), ChecksumImageInvalid.__str__] Too many arguments for format string
cloudferrylib/utils/utils.py:449: [E1101(no-member), render_info] Instance of 'str' has no 'render' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Comment by Settis** [comment]
+1

**Pull request merged**
