### PR TITLE
CF-136 test_migrate_glance_belongs_to_deleted_tenant fails.

### PR DESCRIPTION
**Pull request by plomakin**
Changed test_migrate_glance_belongs_to_deleted_tenant test.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:16: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:17: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:547: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:557: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:16: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:17: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:547: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:557: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
Also need to check, that image's owner on dst is admin tenant

**Comment by mgrygoriev** [comment]
+1

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:16: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:17: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:559: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:569: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:16: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:17: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:559: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:569: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
