### PR TITLE
Updated neutron.py to return subnet info of external net

### PR DESCRIPTION
**Pull request by VitaliiYerys**
Fixed neutron.py in order to return subnet info of external net
'shared_net'.

### CODE REVIEW

**Comment by roman-verchikov** [comment]
Please provide reasonable title and description for pull request and commit

**Comment by roman-verchikov** [comment]
Code looks ok, but let's see why the functional tests failed

**Comment by realsystem** [comment]
+1

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
