### PR TITLE
[Generate Load] Fixed cleaning of private images

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.functional_test
devlab/tests/functional_test.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/functional_test.py:18: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/functional_test.py:19: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/functional_test.py:21: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/functional_test.py:180: [W0106(expression-not-assigned), FunctionalTest.filter_volumes] Expression "[volumes.extend(i['cinder_volumes']) for i in config.tenants if ('cinder_volumes' in i) and (not i.get('deleted'))]" is assigned to nothing
devlab/tests/functional_test.py:206: [W0106(expression-not-assigned), FunctionalTest.get_vms_with_fip_associated] Expression "[vms.extend(i['vms']) for i in config.tenants if 'vms' in i]" is assigned to nothing
************* Module tests.generate_load
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:8: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/generate_load.py:21: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/generate_load.py:832: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:906: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
+1

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
