### PR TITLE
Added Service tenant name to config

### PR DESCRIPTION
**Pull request by toha10**
We need to exclude service tenant and service users from migration
process to not broke destination cloud services.
Also neutron resource was switched from using internal const value to
service tenant name from config file.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test FAILed.   http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/42/

**Comment by roman-verchikov** [comment]
Looks good, but the unit tests are failing, please fix.

**Comment by Wasapl** [comment]
Merged build finished. Test FAILed.   http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/52/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/53/

**Comment by roman-verchikov** [comment]
Looks good, +1

**Comment by miarmak** [comment]
Looks good for me too.
+1

**Comment by mirrorcoder** [comment]
+1

**Pull request merged**
