### PR TITLE
[SAIC-797] Fix ReCreateBootImage

### PR DESCRIPTION
**Pull request by antonf**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.recreate_boot_image
cloudferrylib/os/actions/recreate_boot_image.py:41: [W0102(dangerous-default-value), ReCreateBootImage.run] Dangerous default value {} as argument
cloudferrylib/os/actions/recreate_boot_image.py:41: [W0102(dangerous-default-value), ReCreateBootImage.run] Dangerous default value {} as argument

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Looks ok, +1

**Comment by abochkarev** [comment]
Looks good to me, +1

**Pull request merged**
