### PR TITLE
[CF-508] Support absent references during link stage

### PR DESCRIPTION
**Pull request by antonf**
This patch fixes issue found in production environment where there
was attachment to server that wasn't saved to database (probably due
to it's state or something else). The link stage thrown exception
failing to find server. This patch fixes the problem.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.model.test_model
tests/model/test_model.py:121: [E1101(no-member), ExampleRef.equals] Instance of 
'Reference' has no 'equals' member
tests/model/test_model.py:124: [W0621(redefined-outer-name), ExampleRef.create_object] 
Redefining name 'uuid' from outer scope (line 15)

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, do we need to test this?

**Comment by archyufa** [comment]
+1 Tested in staging

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
