### PR TITLE
[SAIC-646] Remove excess warnings from log

### PR DESCRIPTION
**Pull request by antonf**
Client proxy catch all exceptions and retry request after waiting for
some time. The problem is that sometimes exception is expected to
occur but proxy client don't know anything about this. So it try to
call API several times before allowing exception to be handled
elsewhere. This results in several WARNINGs shown in log. This
patch fix it by adding special method that can be used to tell
proxy client which exceptions it shouldn't handle.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:180: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:201: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.utils.proxy_client
cloudferrylib/utils/proxy_client.py:80: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/utils/proxy_client.py:105: [W0602(global-variable-not-assigned), expect_exception] Using global for 'tls' but no assignment is done
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:778: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:228: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:308: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:372: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:195: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/identity/keystone.py:19: [W0611(unused-import), ] Unused import keystoneclient

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:180: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:201: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:96: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:253: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.utils.proxy_client
cloudferrylib/utils/proxy_client.py:80: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/utils/proxy_client.py:105: [W0602(global-variable-not-assigned), expect_exception] Using global for 'tls' but no assignment is done
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:779: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:228: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:308: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:372: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:194: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:180: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:201: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:96: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:253: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.utils.proxy_client
cloudferrylib/utils/proxy_client.py:80: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:779: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:228: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:308: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:372: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:194: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
retest it please

**Comment by antonf** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:180: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:201: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:96: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:253: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.utils.proxy_client
cloudferrylib/utils/proxy_client.py:80: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:779: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:228: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:308: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:372: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:194: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:180: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:201: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:96: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:253: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.utils.proxy_client
cloudferrylib/utils/proxy_client.py:80: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:779: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:228: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:308: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:372: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:194: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
@antonf please rebase

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:180: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:201: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:139: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:318: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.utils.proxy_client
cloudferrylib/utils/proxy_client.py:80: [I0011(locally-disabled), ] Locally disabling broad-except (W0703)
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:779: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:406: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:196: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
@antonf looks like this needs to be rebased again

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.cold_evacuate
cloudferrylib/os/compute/cold_evacuate.py:277: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
cloudferrylib/os/compute/cold_evacuate.py:278: [E1101(no-member), install_ssh_keys] Instance of 'ValueError' has no 'replace' member
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:139: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:318: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:807: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
cloudferrylib/os/compute/nova_compute.py:993: [W0621(redefined-outer-name), NovaCompute.get_instance_sql_id_by_uuid] Redefining name 'uuid' from outer scope (line 20)
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:406: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:196: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
