### PR TITLE
Remove unused import from prepare_networks.py

### PR DESCRIPTION
**Pull request by abochkarev**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.prepare_networks
cloudferrylib/os/actions/prepare_networks.py:149: [W0612(unused-variable), CreatePortsForVRRP.run] Unused variable 'id_inst'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.prepare_networks
cloudferrylib/os/actions/prepare_networks.py:149: [W0612(unused-variable), CreatePortsForVRRP.run] Unused variable 'id_inst'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
+1

**Comment by miarmak** [comment]
+1. can be merged

**Pull request merged**
