### PR TITLE
SAIC-77: Add 'auth_url' option to config

### PR DESCRIPTION
**Pull request by miarmak**
Use this parameter for OpenStack clients authentication in CloudFerry
resources instead of it's (URL) constructing in the code.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/159/

**Comment by roman-verchikov** [comment]
I found a number of port 35357 hardcoded in tasks:
```
$ find . -type f -name '*.py' -not -path './.git/*' -not -path './.osx-venv/*' | xargs grep 35357
./cloudferrylib/os/actions/convert_file_to_image.py:                       "--os-auth-url=http://%s:35357/v2.0 " +
./cloudferrylib/os/actions/convert_image_to_file.py:                     "--os-auth-url=http://%s:35357/v2.0 " +
./cloudferrylib/os/actions/load_compute_image_to_file.py:                         "--os-auth-url=http://%s:35357/v2.0 " +
./cloudferrylib/os/actions/upload_file_to_image.py:                           "--os-auth-url=http://%s:35357/v2.0 " +
./tests/cloudferrylib/os/compute/test_nova.py:                          'auth_url': 'http://1.1.1.1:35357/v2.0/'}),
./tests/cloudferrylib/os/compute/test_nova.py:                                                 'http://1.1.1.1:35357/v2.0/')
./tests/cloudferrylib/os/identity/test_keystone.py:                          'auth_url': 'http://1.1.1.1:35357/v2.0/'}),
./tests/cloudferrylib/os/identity/test_keystone.py:                      auth_url='http://1.1.1.1:35357/v2.0/'),
./tests/cloudferrylib/os/identity/test_keystone.py:            mock.call(token='fake_id', endpoint='http://1.1.1.1:35357/v2.0/')]
./tests/cloudferrylib/os/network/test_neutron.py:                          'auth_url': 'http://1.1.1.1:35357/v2.0/'}),
./tests/cloudferrylib/os/network/test_neutron.py:            auth_url='http://1.1.1.1:35357/v2.0/'
./tests/cloudferrylib/os/network/test_nova_network.py:                          'auth_url': 'http://1.1.1.1:35357/v2.0/'}),
./tests/cloudferrylib/os/storage/test_cinder.py:                          'auth_url': 'http://1.1.1.1:35357/v2.0/'}),
./tests/cloudferrylib/os/storage/test_cinder.py:                                                 'http://1.1.1.1:35357/v2.0/')
```
Please fix

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/166/

**Comment by miarmak** [comment]
@roman-verchikov Nice catch, thanks. I've lost sight of it. Already done.

**Comment by roman-verchikov** [comment]
+1

**Comment by roman-verchikov** [comment]
We need one more +1 to merge

**Comment by oleksii-shyman** [comment]
+1

**Pull request merged**
