### PR TITLE
CF-580 Check available space before copying data

### PR DESCRIPTION
**Pull request by roman-verchikov**
Checks if destination has enough space before attempting to copy data
instead of failing in the middle of the process.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3979/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3980/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
Can you rewrite `SharedNFSPlugin.get_provider_location()` function to re-use your `gnu_df_output_parser`?

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
👍 can be merged

**Pull request merged**
