### PR TITLE
[CF-86] Fix recreating broken images

### PR DESCRIPTION
**Pull request by SVilgelm**
Refactor ReCreateBootImage.
Check that image exists on destination.
Create images on destination with keeping old id.
Implement unit tests.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2275/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.qemu_img
cloudferrylib/utils/qemu_img.py:90: [W0101(unreachable), QemuImg.get_info] Unreachable code
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:422: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:422: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.cloudferrylib.os.actions.test_recreate_boot_image
tests/cloudferrylib/os/actions/test_recreate_boot_image.py:66: [E0102(function-redefined), ReCreateBootImageTestCase.test_run_with_missing_images] method already defined line 55
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:422: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:422: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.cloudferrylib.utils.test_file_proxy
tests/cloudferrylib/utils/test_file_proxy.py:15: [W0611(unused-import), ] Unused import os
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:422: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2298/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib/utils/file_like_proxy.py
cloudferrylib/utils/file_like_proxy.py:1: [F0001(fatal), ] No module named cloudferrylib/utils/file_like_proxy.py
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:420: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib/utils/file_like_proxy.py
cloudferrylib/utils/file_like_proxy.py:1: [F0001(fatal), ] No module named cloudferrylib/utils/file_like_proxy.py
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:420: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib/utils/file_like_proxy.py
cloudferrylib/utils/file_like_proxy.py:1: [F0001(fatal), ] No module named cloudferrylib/utils/file_like_proxy.py
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:420: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib/utils/file_like_proxy.py
cloudferrylib/utils/file_like_proxy.py:1: [F0001(fatal), ] No module named cloudferrylib/utils/file_like_proxy.py
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:420: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
+1, tested on devlab, works good

**Comment by ntymtsiv** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib/utils/file_like_proxy.py
cloudferrylib/utils/file_like_proxy.py:1: [F0001(fatal), ] No module named cloudferrylib/utils/file_like_proxy.py
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:420: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
Please look at the error in http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-grizzly-to-juno/1484/console

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib/utils/file_like_proxy.py
cloudferrylib/utils/file_like_proxy.py:1: [F0001(fatal), ] No module named cloudferrylib/utils/file_like_proxy.py
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:420: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
