### PR TITLE
Minor fix: Config refactoring

### PR DESCRIPTION
**Pull request by miarmak**
Lead to an overall view of the configs/config.ini.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/161/

**Comment by roman-verchikov** [comment]
Doesn't seem to be breaking anything, +1

**Comment by roman-verchikov** [comment]
@miarmak could you pull the changes from #135 here?

**Comment by miarmak** [comment]
@roman-verchikov They are already here

**Comment by roman-verchikov** [comment]
Please rebase

**Comment by miarmak** [comment]
Done

**Comment by roman-verchikov** [comment]
No functional changes made, so I think we can merge it.

**Pull request merged**
