### PR TITLE
SAIC-211 Integrate condensation steps

### PR DESCRIPTION
**Pull request by roman-verchikov**
- The hardware info, nova info and grouping are all part of condensation.
  - All output files are used internally for CF only, should be put in /tmp, not defined in config.ini.
  - Grouping rule should stay in configs/. Remove the [condensation] section from config.ini.
  - The condensation script should take yaml file as input, not yml file.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSED.

**Comment by roman-verchikov** [comment]
This depends on https://github.com/MirantisWorkloadMobility/CloudFerry/pull/193

**Comment by Wasapl** [comment]
Merged build finished. Test PASSED.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSED.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSED.

**Comment by Wasapl** [comment]
Can one of the admins verify this patch?

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by plomakin** [comment]
Please, rebase

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by roman-verchikov** [comment]
Verified on production env - success

**Pull request merged**
