### PR TITLE
Port option for mysql connection.

### PR DESCRIPTION
**Pull request by toha10**
Added port option to mysql config section for setting custom ports.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by miarmak** [comment]
Since we have separate database config settings for image and storage sections (and I guess in future for other components), it would be nice to add it there too.

**Comment by roman-verchikov** [comment]
Looks like you'd have to modify `cloudferrylib.os.actions.snapshots.MysqlDump` and `cloudferrylib.os.actions.snapshots.MysqlRestore` as part of this patch too. I believe mysql connector code in those classes must be moved to `cloudferrylib/utils/mysql_connector.py`. Looks good otherwise.

**Comment by roman-verchikov** [comment]
@toha10 please update according to comments (or let us know if our comments don't make sense)

**Comment by Wasapl** [comment]
Merged build finished. Test PASSED.

**Comment by toha10** [comment]
Added port option for glance and storage sections.
Speaking about 'cloudferrylib.os.actions.snapshots.MysqlDump' and 'cloudferrylib.os.actions.snapshots.MysqlRestore' classes, i think that it is a different action and not related to mysql connection to DB. This is an external interaction with DB and also AFAIK sqlalchemy have no functionality for dumping or restoring DBs.
So, please correct me if i'm wrong.

**Comment by roman-verchikov** [comment]
@toha10 `mysqldump` has similar options for connecting to the database, so please update `cloudferrylib.os.actions.snapshots.MysqlDump` and `cloudferrylib.os.actions.snapshots.MysqlRestore` accordingly, it should be an easy fix.

**Comment by Wasapl** [comment]
Merged build finished. Test FAILED.

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by roman-verchikov** [comment]
@toha10 please modify your code so that functional test pass, currently it fails with:
```
DEBUG    [/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/os/compute/nova_compute.py : lineno 94]  07-01 14:21:32  Running on custom mysql settings
Traceback (most recent call last):
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/fabfile.py", line 56, in migrate
    cloud = cloud_ferry.CloudFerry(cfglib.CONF)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloud/cloud_ferry.py", line 28, in __new__
    return __import__('cloud').os2os.OS2OSFerry(config)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloud/os2os.py", line 93, in __init__
    self.src_cloud = cloud.Cloud(resources, cloud.SRC, config)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloud/cloud.py", line 34, in __init__
    self.init_resources(self.cloud_config)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloud/cloud.py", line 97, in init_resources
    resource_config, self)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/os/compute/nova_compute.py", line 76, in __init__
    self.mysql_connector = self.get_db_connection()
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/os/compute/nova_compute.py", line 98, in get_db_connection
    my_settings.database_name)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/utils/mysql_connector.py", line 23, in __init__
    self.connection_url = self.compose_connection_url()
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/utils/mysql_connector.py", line 30, in compose_connection_url
    self.config['port'],
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 2554, in __getitem__
    return self.__getattr__(key)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 2550, in __getattr__
    return self._conf._get(name, self._group)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 2267, in _get
    value = self._do_get(name, group, namespace)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 2285, in _do_get
    info = self._get_opt_info(name, group)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/.venv/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 2418, in _get_opt_info
    raise NoSuchOptError(opt_name, group)
oslo_config.cfg.NoSuchOptError: no such option in group src_compute: port
```

**Comment by miarmak** [comment]
Implemented in https://github.com/MirantisWorkloadMobility/CloudFerry/commit/0f95548c5bd3af619e7cbb534fbe2937fdb7974c

Can be closed.

**Pull request closed without merging**
