### PR TITLE
Migrate VM when flavor is not present.

### PR DESCRIPTION
**Pull request by VitaliiYerys**
Added a new VM and flavor, flavor was deleted after VM spawning.

### CODE REVIEW

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by roman-verchikov** [comment]
Functional tests failure:
```
INFO     [/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/scheduler/scheduler.py : lineno 47]  06-10 17:09:13  -------- Start task: BaseTask|CheckNeededComputeResources
ERROR    [/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/os/actions/check_needed_compute_resources.py : lineno 69]  06-10 17:09:13  The flavor ID of instance c1a78554-1f02-480d-b945-1a48f1846744 does not match to any flavor. Please resize the instance.
ERROR    [/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/scheduler/scheduler.py : lineno 58]  06-10 17:09:13  BaseTask|CheckNeededComputeResources TASK FAILED
Traceback (most recent call last):
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/scheduler/scheduler.py", line 71, in process_chain
    self.run_task(task)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/scheduler/scheduler.py", line 63, in run_task
    self.map_func_task[task](task)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/scheduler/scheduler.py", line 92, in task_run
    task(namespace=self.namespace)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/scheduler/task.py", line 96, in __call__
    result = self.run(**namespace.vars)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/os/actions/check_needed_compute_resources.py", line 32, in run
    self.check_in_use_flavor(objs)
  File "/home/ubuntu/jenkins_slave/workspace/cloudferry-functional-tests/cloudferry/cloudferrylib/os/actions/check_needed_compute_resources.py", line 71, in check_in_use_flavor
    instance['instance']['flavor_id'])
RuntimeError: ('Obsolete flavor ID', u'0f6f014a-17ac-44bb-86d7-22c93deea267')
```

**Comment by roman-verchikov** [comment]
We'd have to provide a fix for this prior to merging the test

**Comment by roman-verchikov** [comment]
Please rebase

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Functional test success

**Comment by Wasapl** [comment]
Functional test success

**Comment by roman-verchikov** [comment]
Looks good, can be merged

**Pull request merged**
