### PR TITLE
Readme file updates based on new documentation

### PR DESCRIPTION
**Pull request by roman-verchikov**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by SVilgelm** [comment]
:+1: Looks good to me

**Pull request merged**
