### PR TITLE
CF-588 Some Functional Tests being skipped

### PR DESCRIPTION
**Pull request by plomakin**
Fixed requirements.txt

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by plomakin** [comment]
@jaspreetrawel functional tests here: http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-icehouse-to-juno/256/console

Hope it'll help.

**Comment by plomakin** [comment]
@jaspreetrawel nevermind, looks like it didn't work...

**Comment by jaspreetrawel** [comment]
@plomakin I added below in CloudFerry/cloudferry_devlab/setup.py but that also did not work.
`dependency_links = ['git+https://github.com/kevinastone/generator.git@dc9c3a5ed5e8ba70f8d514e847b882f11807bd57#egg=test-generator'],`

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
