### PR TITLE
CF-138 Refactor generate_load.py

### PR DESCRIPTION
**Pull request by plomakin**
Moved BasePrerequisites to base.py
Moved CleanEnv to cleanup.py
Reworked Prerequisites in generate_load.py
Moved all tests to tests/ dir
Added lost licenses.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab/tests/test_group_verification.py
devlab/tests/test_group_verification.py:1: [F0001(fatal), ] No module named devlab/tests/test_group_verification.py
************* Module devlab/tests/test_resource_migration.py
devlab/tests/test_resource_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_resource_migration.py
************* Module devlab/tests/test_verify_dst_del_tenant_resources.py
devlab/tests/test_verify_dst_del_tenant_resources.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_del_tenant_resources.py
************* Module devlab/tests/test_verify_dst_functionality.py
devlab/tests/test_verify_dst_functionality.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_functionality.py
************* Module devlab/tests/test_verify_dst_net_segm_id.py
devlab/tests/test_verify_dst_net_segm_id.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_net_segm_id.py
************* Module devlab/tests/test_vm_migration.py
devlab/tests/test_vm_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_vm_migration.py
************* Module tests.testcases.test_group_verification
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:21: [E0611(no-name-in-module), ] No name 'functional_test' in module 'test'
devlab/tests/testcases/test_group_verification.py:21: [E0401(import-error), ] Unable to import 'test.functional_test'
devlab/tests/testcases/test_group_verification.py:61: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/testcases/test_group_verification.py:97: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/testcases/test_group_verification.py:74: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:80: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:73: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:108: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:134: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/testcases/test_group_verification.py:186: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__
************* Module tests.cleanup
devlab/tests/cleanup.py:8: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/cleanup.py:9: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
************* Module tests.base
devlab/tests/base.py:9: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/base.py:10: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:559: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:569: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.generate_load
devlab/tests/generate_load.py:13: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/generate_load.py:14: [W0403(relative-import), ] Relative import 'cleanup', should be 'tests.cleanup'
devlab/tests/generate_load.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:570: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:644: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab/tests/rollback_verification.py
devlab/tests/rollback_verification.py:1: [F0001(fatal), ] No module named devlab/tests/rollback_verification.py
************* Module devlab/tests/test_group_verification.py
devlab/tests/test_group_verification.py:1: [F0001(fatal), ] No module named devlab/tests/test_group_verification.py
************* Module devlab/tests/test_resource_migration.py
devlab/tests/test_resource_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_resource_migration.py
************* Module devlab/tests/test_verify_dst_del_tenant_resources.py
devlab/tests/test_verify_dst_del_tenant_resources.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_del_tenant_resources.py
************* Module devlab/tests/test_verify_dst_functionality.py
devlab/tests/test_verify_dst_functionality.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_functionality.py
************* Module devlab/tests/test_verify_dst_net_segm_id.py
devlab/tests/test_verify_dst_net_segm_id.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_net_segm_id.py
************* Module devlab/tests/test_vm_migration.py
devlab/tests/test_vm_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_vm_migration.py
************* Module tests.testcases.rollback_verification
devlab/tests/testcases/rollback_verification.py:42: [E1101(no-member), RollbackVerification.setUp] Instance of 'DataCollector' has no 'main_folder' member
************* Module tests.testcases.test_group_verification
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:21: [E0611(no-name-in-module), ] No name 'functional_test' in module 'test'
devlab/tests/testcases/test_group_verification.py:21: [E0401(import-error), ] Unable to import 'test.functional_test'
devlab/tests/testcases/test_group_verification.py:61: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/testcases/test_group_verification.py:97: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/testcases/test_group_verification.py:74: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:80: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:73: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:108: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:134: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/testcases/test_group_verification.py:186: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__
************* Module tests.cleanup
devlab/tests/cleanup.py:8: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/cleanup.py:9: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
************* Module tests.base
devlab/tests/base.py:9: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/base.py:10: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:559: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:569: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.generate_load
devlab/tests/generate_load.py:13: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/generate_load.py:14: [W0403(relative-import), ] Relative import 'cleanup', should be 'tests.cleanup'
devlab/tests/generate_load.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:570: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:644: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab/tests/rollback_verification.py
devlab/tests/rollback_verification.py:1: [F0001(fatal), ] No module named devlab/tests/rollback_verification.py
************* Module devlab/tests/test_group_verification.py
devlab/tests/test_group_verification.py:1: [F0001(fatal), ] No module named devlab/tests/test_group_verification.py
************* Module devlab/tests/test_resource_migration.py
devlab/tests/test_resource_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_resource_migration.py
************* Module devlab/tests/test_verify_dst_del_tenant_resources.py
devlab/tests/test_verify_dst_del_tenant_resources.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_del_tenant_resources.py
************* Module devlab/tests/test_verify_dst_functionality.py
devlab/tests/test_verify_dst_functionality.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_functionality.py
************* Module devlab/tests/test_verify_dst_net_segm_id.py
devlab/tests/test_verify_dst_net_segm_id.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_net_segm_id.py
************* Module devlab/tests/test_vm_migration.py
devlab/tests/test_vm_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_vm_migration.py
************* Module tests.testcases.rollback_verification
devlab/tests/testcases/rollback_verification.py:42: [E1101(no-member), RollbackVerification.setUp] Instance of 'DataCollector' has no 'main_folder' member
************* Module tests.base
devlab/tests/base.py:9: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/base.py:10: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.cleanup
devlab/tests/cleanup.py:8: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/cleanup.py:9: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
************* Module tests.testcases.test_group_verification
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:61: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/testcases/test_group_verification.py:97: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/testcases/test_group_verification.py:74: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:80: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:73: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:108: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:134: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/testcases/test_group_verification.py:186: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__
************* Module tests.generate_load
devlab/tests/generate_load.py:13: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/generate_load.py:14: [W0403(relative-import), ] Relative import 'cleanup', should be 'tests.cleanup'
devlab/tests/generate_load.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:570: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:644: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:559: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:569: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Please add license headers to all files

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab/tests/rollback_verification.py
devlab/tests/rollback_verification.py:1: [F0001(fatal), ] No module named devlab/tests/rollback_verification.py
************* Module devlab/tests/test_group_verification.py
devlab/tests/test_group_verification.py:1: [F0001(fatal), ] No module named devlab/tests/test_group_verification.py
************* Module devlab/tests/test_resource_migration.py
devlab/tests/test_resource_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_resource_migration.py
************* Module devlab/tests/test_verify_dst_del_tenant_resources.py
devlab/tests/test_verify_dst_del_tenant_resources.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_del_tenant_resources.py
************* Module devlab/tests/test_verify_dst_functionality.py
devlab/tests/test_verify_dst_functionality.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_functionality.py
************* Module devlab/tests/test_verify_dst_net_segm_id.py
devlab/tests/test_verify_dst_net_segm_id.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_net_segm_id.py
************* Module devlab/tests/test_vm_migration.py
devlab/tests/test_vm_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_vm_migration.py
************* Module tests.testcases.rollback_verification
devlab/tests/testcases/rollback_verification.py:42: [E1101(no-member), RollbackVerification.setUp] Instance of 'DataCollector' has no 'main_folder' member
************* Module tests.base
devlab/tests/base.py:9: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/base.py:10: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.testcases.test_group_verification
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:61: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/testcases/test_group_verification.py:97: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/testcases/test_group_verification.py:74: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:80: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:73: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:108: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:134: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/testcases/test_group_verification.py:186: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__
************* Module tests.cleanup
devlab/tests/cleanup.py:8: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/cleanup.py:9: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
************* Module tests.generate_load
devlab/tests/generate_load.py:13: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/generate_load.py:14: [W0403(relative-import), ] Relative import 'cleanup', should be 'tests.cleanup'
devlab/tests/generate_load.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:570: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:644: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:559: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:569: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab/tests/rollback_verification.py
devlab/tests/rollback_verification.py:1: [F0001(fatal), ] No module named devlab/tests/rollback_verification.py
************* Module devlab/tests/test_group_verification.py
devlab/tests/test_group_verification.py:1: [F0001(fatal), ] No module named devlab/tests/test_group_verification.py
************* Module devlab/tests/test_resource_migration.py
devlab/tests/test_resource_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_resource_migration.py
************* Module devlab/tests/test_verify_dst_del_tenant_resources.py
devlab/tests/test_verify_dst_del_tenant_resources.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_del_tenant_resources.py
************* Module devlab/tests/test_verify_dst_functionality.py
devlab/tests/test_verify_dst_functionality.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_functionality.py
************* Module devlab/tests/test_verify_dst_net_segm_id.py
devlab/tests/test_verify_dst_net_segm_id.py:1: [F0001(fatal), ] No module named devlab/tests/test_verify_dst_net_segm_id.py
************* Module devlab/tests/test_vm_migration.py
devlab/tests/test_vm_migration.py:1: [F0001(fatal), ] No module named devlab/tests/test_vm_migration.py
************* Module tests.testcases.rollback_verification
devlab/tests/testcases/rollback_verification.py:42: [E1101(no-member), RollbackVerification.setUp] Instance of 'DataCollector' has no 'main_folder' member
************* Module tests.cleanup
devlab/tests/cleanup.py:22: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/cleanup.py:23: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
************* Module tests.base
devlab/tests/base.py:23: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/base.py:24: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.testcases.test_group_verification
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:66: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
devlab/tests/testcases/test_group_verification.py:61: [W0703(broad-except), GroupProcedureVerification.tearDown] Catching too general exception Exception
devlab/tests/testcases/test_group_verification.py:97: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'new_file_name' defined outside __init__
devlab/tests/testcases/test_group_verification.py:74: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:80: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'pre_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:73: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:108: [W0201(attribute-defined-outside-init), GroupProcedureVerification._prepare_files] Attribute 'post_conf_dict' defined outside __init__
devlab/tests/testcases/test_group_verification.py:134: [W0201(attribute-defined-outside-init), GroupProcedureVerification.src_vms_info_generator] Attribute 'src_vms' defined outside __init__
devlab/tests/testcases/test_group_verification.py:186: [W0201(attribute-defined-outside-init), GroupProcedureVerification.test_verify_vm_status_filtering_during_grouping] Attribute 'src_vms' defined outside __init__
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:560: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:570: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class
************* Module tests.generate_load
devlab/tests/generate_load.py:27: [W0403(relative-import), ] Relative import 'base', should be 'tests.base'
devlab/tests/generate_load.py:28: [W0403(relative-import), ] Relative import 'cleanup', should be 'tests.cleanup'
devlab/tests/generate_load.py:29: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:584: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:658: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
