### PR TITLE
[Do not merge] Use oslo-config-generator to generate a configuration file

### PR DESCRIPTION
**Pull request by SVilgelm**

### CODE REVIEW

**Comment by SVilgelm** [comment]
@roman-verchikov, @plomakin please take a look, it's a draft

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3039/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
looks ok

**Pull request closed without merging**
