### PR TITLE
Fix bug with the 'time_wait' parameter

### PR DESCRIPTION
**Pull request by miarmak**
Since 'time_wait' is defined as IntOpt in the cfglib.py, it should have
integer value, instead of string value. In other case it raises
exception, when a Proxy wrapper is used for OpenStack clients in the
CloudFerry resources.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/111/

**Comment by mirrorcoder** [comment]
+1

**Comment by oleksii-shyman** [comment]
looks ok

**Comment by roman-verchikov** [comment]
+1

**Pull request merged**
