### PR TITLE
CF-589 Rework functional tests to support external network mapping.

### PR DESCRIPTION
**Pull request by plomakin**
Fixed ext_net_map.yaml generation.
Added mapped FIPs test.
Small refactor for functional_test.py

[skip ci]

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
!!! Couldn't read commit file !!!

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/4039/

**Comment by MirantisWorkloadMobility** [comment]
!!! Couldn't read commit file !!!

**Comment by MirantisWorkloadMobility** [comment]
!!! Couldn't read commit file !!!

**Comment by MirantisWorkloadMobility** [comment]
!!! Couldn't read commit file !!!

**Comment by MirantisWorkloadMobility** [comment]
!!! Couldn't read commit file !!!

**Comment by MirantisWorkloadMobility** [comment]
!!! Couldn't read commit file !!!

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Unittests failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests/3/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/21/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/30/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/33/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/40/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/42/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/43/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/44/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/45/

**Pull request closed without merging**
