### PR TITLE
CF-513 Refactor functional tests to remove unnecessary dependencies.

### PR DESCRIPTION
**Pull request by plomakin**
Removed pre_migration_vm_states.json file generation and usage.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3678/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.generate_load
cloudferry_devlab/cloudferry_devlab/generate_load.py:16: [W0611(unused-import), ] 
Unused import json

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Looks ok, +1

**Comment by SVilgelm** [comment]
👍 can be merged

**Pull request merged**
