### PR TITLE
[CF-175] Add region_name into creating openstack clients

### PR DESCRIPTION
**Pull request by SVilgelm**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.network.nova_network
cloudferrylib/os/network/nova_network.py:55: [W0221(arguments-differ), NovaNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/nova_network.py:58: [W0221(arguments-differ), NovaNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:319: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:198: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:184: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:289: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:817: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2435/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.network.nova_network
cloudferrylib/os/network/nova_network.py:55: [W0221(arguments-differ), NovaNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/nova_network.py:58: [W0221(arguments-differ), NovaNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:319: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:198: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method
************* Module tests.cloudferrylib.os.compute.test_nova
tests/cloudferrylib/os/compute/test_nova.py:446: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:449: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:451: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:478: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:479: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:483: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:485: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:512: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:513: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:517: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:519: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:184: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:289: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:817: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
************* Module tests.cloudferrylib.os.identity.test_keystone
tests/cloudferrylib/os/identity/test_keystone.py:213: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:214: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:236: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.tenant_create] Unused argument 'kwargs'
tests/cloudferrylib/os/identity/test_keystone.py:241: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.user_create] Unused argument 'kwars'
tests/cloudferrylib/os/identity/test_keystone.py:246: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.roles_create] Unused argument 'role_name'
tests/cloudferrylib/os/identity/test_keystone.py:446: [W0212(protected-access), KeystoneClientTestCase.test_adds_region_if_set_in_config] Access to a protected member _get_client_by_creds of a client class
tests/cloudferrylib/os/identity/test_keystone.py:478: [W0212(protected-access), KeystoneClientTestCase.test_does_not_add_region_if_not_set_in_config] Access to a protected member _get_client_by_creds of a client class

**Comment by roman-verchikov** [comment]
Please add regions to `condensation/scripts/nova_collector.py`

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.network.nova_network
cloudferrylib/os/network/nova_network.py:55: [W0221(arguments-differ), NovaNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/nova_network.py:58: [W0221(arguments-differ), NovaNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:319: [W0613(unused-argument), CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:198: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:184: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:289: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:817: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
************* Module tests.cloudferrylib.os.identity.test_keystone
tests/cloudferrylib/os/identity/test_keystone.py:213: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:214: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:236: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.tenant_create] Unused argument 'kwargs'
tests/cloudferrylib/os/identity/test_keystone.py:241: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.user_create] Unused argument 'kwars'
tests/cloudferrylib/os/identity/test_keystone.py:246: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.roles_create] Unused argument 'role_name'
tests/cloudferrylib/os/identity/test_keystone.py:446: [W0212(protected-access), KeystoneClientTestCase.test_adds_region_if_set_in_config] Access to a protected member _get_client_by_creds of a client class
tests/cloudferrylib/os/identity/test_keystone.py:478: [W0212(protected-access), KeystoneClientTestCase.test_does_not_add_region_if_not_set_in_config] Access to a protected member _get_client_by_creds of a client class
************* Module tests.cloudferrylib.os.compute.test_nova
tests/cloudferrylib/os/compute/test_nova.py:446: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:449: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:451: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:478: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:479: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:483: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:485: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:512: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:513: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:517: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:519: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
