### PR TITLE
Floating IP migration functional test

### PR DESCRIPTION
**Pull request by roman-verchikov**
Adds functional test which verifies floating IP migration: all floating
IPs on source are the same as floating IPs on destination.

### CODE REVIEW

**Comment by realsystem** [comment]
+1

**Comment by ntymtsiv** [comment]
+1

**Comment by miarmak** [comment]
Looks good to me too. +1

**Comment by roman-verchikov** [comment]
yeah, unfortunately it won't work because `pprint` library is not imported =)

**Comment by roman-verchikov** [comment]
can be merged.

**Comment by miarmak** [comment]
Ooops :)

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
