### PR TITLE
 [SIC-599] Missing quotation marks in tasks.yaml

### PR DESCRIPTION
**Pull request by raiesmh08**
Missing quotation marks in task defined in tasks.yaml
Line 110 in scenario/tasks.yaml should be changed from:
verify_vms: ['VerifyVms', src_cloud]
to
verify_vms: ['VerifyVms', 'src_cloud']

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Pylint check succeeded

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1426/

**Comment by MirantisWorkloadMobility** [comment]
Functional test failure for Grizzly to Juno migration
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-grizzly-to-juno/630/

**Comment by MirantisWorkloadMobility** [comment]
Functional test success for Icehouse to Juno migration

**Comment by MirantisWorkloadMobility** [comment]
Functional test success for Grizzly to Icehouse migration

**Comment by Settis** [comment]
In fact 'src_cloud' don't needed here. The action don't use it. Let's delete it:
> verify_vms: ['VerifyVms']

**Comment by MirantisWorkloadMobility** [comment]
Ready

**Comment by roman-verchikov** [comment]
@raiesmh08 please resolve comment from @Settis:
> In fact 'src_cloud' don't needed here. The action don't use it. Let's delete it:
>> verify_vms: ['VerifyVms']

**Comment by roman-verchikov** [comment]
Everything is string in YAML file, closing as invalid.

**Pull request closed without merging**
