### PR TITLE
[CF-23] Add verify step into migrate_vms.yaml

### PR DESCRIPTION
**Pull request by SVilgelm**
CF doesn't remove broken VMs from destination
because migrate_vms scenarion didn't contain verify step.
Add remove_failed_instances step into verify section.

### CODE REVIEW

**Comment by roman-verchikov** [comment]
please add description to pull request and commit

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by SVilgelm** [comment]
Done

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
