### PR TITLE
[CF-222] Hybrid resource migration scenario.

### PR DESCRIPTION
**Pull request by archyufa**
1. Hybrid resource migration scenario with no rollbacks, which migrates
resources that don't require time-consuming transfers (volumes, images).
Following resources going to be migrated in this scenario: identity,
compute, keypairs, networks.

2. Added print info for configurations, scenario and filters to be viewed
in logs for scenarios with no rollbacks.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by miarmak** [comment]
+1

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
