### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by SVilgelm**
Use newer version of external libraries.
Add IterProxy to use as a file for glance images migration.
_resp attribute is not needed at all.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.file_proxy
cloudferrylib/utils/file_proxy.py:136: [W0613(unused-argument), FileProxy.read] Unused 
argument 'size'
cloudferrylib/utils/file_proxy.py:155: [W0613(unused-argument), IterProxy.read] Unused 
argument 'size'
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:188: [W0221(arguments-differ), 
NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:294: [W0221(arguments-differ), 
NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' 
method
cloudferrylib/os/network/neutron.py:347: [W0221(arguments-differ), 
NeutronNetwork.check_existing_port] Arguments number differs from overridden 
'check_existing_port' method
cloudferrylib/os/network/neutron.py:840: [W0221(arguments-differ), 
NeutronNetwork.get_security_groups] Arguments number differs from overridden 
'get_security_groups' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:225: [W0201(attribute-defined-outside-init), 
Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:246: [W0232(no-init), Templater] Class has no __init__ 
method
cloudferrylib/utils/utils.py:404: [W0201(attribute-defined-outside-init), 
UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:188: [W0221(arguments-differ), 
NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:294: [W0221(arguments-differ), 
NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' 
method
cloudferrylib/os/network/neutron.py:347: [W0221(arguments-differ), 
NeutronNetwork.check_existing_port] Arguments number differs from overridden 
'check_existing_port' method
cloudferrylib/os/network/neutron.py:840: [W0221(arguments-differ), 
NeutronNetwork.get_security_groups] Arguments number differs from overridden 
'get_security_groups' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:225: [W0201(attribute-defined-outside-init), 
Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:246: [W0232(no-init), Templater] Class has no __init__ 
method
cloudferrylib/utils/utils.py:404: [W0201(attribute-defined-outside-init), 
UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3168/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:225: [W0201(attribute-defined-outside-init), 
Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:246: [W0232(no-init), Templater] Class has no __init__ 
method
cloudferrylib/utils/utils.py:404: [W0201(attribute-defined-outside-init), 
UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:28: [E0401(import-error), ] Unable to import 
'OpenSSL'

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:225: [W0201(attribute-defined-outside-init), 
Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:246: [W0232(no-init), Templater] Class has no __init__ 
method
cloudferrylib/utils/utils.py:404: [W0201(attribute-defined-outside-init), 
UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:225: [W0201(attribute-defined-outside-init), 
Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:246: [W0232(no-init), Templater] Class has no __init__ 
method
cloudferrylib/utils/utils.py:404: [W0201(attribute-defined-outside-init), 
UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
https://s-media-cache-ak0.pinimg.com/736x/b4/98/00/b49800f49d35fb8b13f09ef68322ac0b.jpg

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.utils
cloudferrylib/utils/utils.py:225: [W0201(attribute-defined-outside-init), 
Postman.__enter__] Attribute 'server' defined outside __init__
cloudferrylib/utils/utils.py:246: [W0232(no-init), Templater] Class has no __init__ 
method
cloudferrylib/utils/utils.py:404: [W0201(attribute-defined-outside-init), 
UpSshTunnelClass.__enter__] Attribute 'port' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
+1, can be merged

**Pull request merged**
