### PR TITLE
SAIC-770 Insert query fails for cinder tables

### PR DESCRIPTION
**Pull request by aguzikova**
Here is a bug:

query=
"INSERT INTO quotas
(deleted_at,resource,deleted,created_at,updated_at,hard_limit,project_id,id)
VALUES (s,%s,%s,%s,%s,%s,%s,%s)"
cursor.executemany(query, [i.values() for i in entries])

Columns: (deleted_at,resource,...) it created using first entry (entries[0]).
i (entry) is not an ordered dict.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.storage.cinder_database
cloudferrylib/os/storage/cinder_database.py:224: [W0125(using-constant-test), CinderStorage._filter_quotas_list] Using a conditional statement with a constant value

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Looks ok, requires testing in staging

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
Is it a valid pr? SAIC-770 is fixed with this pull request or with #668 ?

**Pull request closed without merging**
