### PR TITLE
CF-48 check if image with deleted primary tenant migrates successfully.

### PR DESCRIPTION
**Pull request by plomakin**
Added member to image6, image with deleted tenant.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.generate_load
devlab/tests/generate_load.py:6: [E0401(import-error), ] Unable to import 'yaml'
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:8: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/generate_load.py:11: [E0401(import-error), ] Unable to import 'glanceclient.v1'
devlab/tests/generate_load.py:12: [E0401(import-error), ] Unable to import 'keystoneclient'
devlab/tests/generate_load.py:13: [E0401(import-error), ] Unable to import 'keystoneclient.v2_0'
devlab/tests/generate_load.py:14: [E0401(import-error), ] Unable to import 'neutronclient.common'
devlab/tests/generate_load.py:16: [E0401(import-error), ] Unable to import 'novaclient'
devlab/tests/generate_load.py:17: [E0401(import-error), ] Unable to import 'novaclient.v1_1'
devlab/tests/generate_load.py:18: [E0401(import-error), ] Unable to import 'neutronclient.v2_0'
devlab/tests/generate_load.py:19: [E0401(import-error), ] Unable to import 'cinderclient.v1'
devlab/tests/generate_load.py:21: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2148/

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2151/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.generate_load
devlab/tests/generate_load.py:6: [E0401(import-error), ] Unable to import 'yaml'
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:8: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/generate_load.py:11: [E0401(import-error), ] Unable to import 'glanceclient.v1'
devlab/tests/generate_load.py:12: [E0401(import-error), ] Unable to import 'keystoneclient'
devlab/tests/generate_load.py:13: [E0401(import-error), ] Unable to import 'keystoneclient.v2_0'
devlab/tests/generate_load.py:14: [E0401(import-error), ] Unable to import 'neutronclient.common'
devlab/tests/generate_load.py:16: [E0401(import-error), ] Unable to import 'novaclient'
devlab/tests/generate_load.py:17: [E0401(import-error), ] Unable to import 'novaclient.v1_1'
devlab/tests/generate_load.py:18: [E0401(import-error), ] Unable to import 'neutronclient.v2_0'
devlab/tests/generate_load.py:19: [E0401(import-error), ] Unable to import 'cinderclient.v1'
devlab/tests/generate_load.py:21: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.generate_load
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:8: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/generate_load.py:21: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/generate_load.py:795: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:869: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
