### PR TITLE
CF-516 Migration report

### PR DESCRIPTION
**Pull request by roman-verchikov**
Gathers status of volumes and VMs and prints report in the end of
migration

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/4010/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.lib.os.actions.test_transport_instance
tests/lib/os/actions/test_transport_instance.py:64: [W0212(protected-access), 
DeployInstanceWithManualScheduling.test_tries_to_boot_vm_on_all_nodes] Access to a 
protected member _deploy_instance_on_random_host of a client class
tests/lib/os/actions/test_transport_instance.py:126: [W0212(protected-access), 
DeployInstanceWithManualScheduling.test_runs_only_one_boot_if_node_is_good] Access to a 
protected member _deploy_instance_on_random_host of a client class
************* Module tests.lib.os.compute.test_nova
tests/lib/os/compute/test_nova.py:442: [W0212(protected-access), 
FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access 
to a protected member _create_flavor_if_not_exists of a client class
tests/lib/os/compute/test_nova.py:445: [W0212(protected-access), 
FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access 
to a protected member _deploy_flavors of a client class
tests/lib/os/compute/test_nova.py:447: [W0212(protected-access), 
FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access 
to a protected member _create_flavor_if_not_exists of a client class
tests/lib/os/compute/test_nova.py:475: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a 
protected member _create_flavor_if_not_exists of a client class
tests/lib/os/compute/test_nova.py:476: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a 
protected member _add_flavor_access_for_tenants of a client class
tests/lib/os/compute/test_nova.py:480: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a 
protected member _deploy_flavors of a client class
tests/lib/os/compute/test_nova.py:482: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a 
protected member _add_flavor_access_for_tenants of a client class
tests/lib/os/compute/test_nova.py:510: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to 
a protected member _create_flavor_if_not_exists of a client class
tests/lib/os/compute/test_nova.py:511: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to 
a protected member _add_flavor_access_for_tenants of a client class
tests/lib/os/compute/test_nova.py:515: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to 
a protected member _deploy_flavors of a client class
tests/lib/os/compute/test_nova.py:517: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to 
a protected member _add_flavor_access_for_tenants of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.lib.os.actions.test_transport_instance
tests/lib/os/actions/test_transport_instance.py:64: [W0212(protected-access), 
DeployInstanceWithManualScheduling.test_tries_to_boot_vm_on_all_nodes] Access to a 
protected member _deploy_instance_on_random_host of a client class
tests/lib/os/actions/test_transport_instance.py:126: [W0212(protected-access), 
DeployInstanceWithManualScheduling.test_runs_only_one_boot_if_node_is_good] Access to a 
protected member _deploy_instance_on_random_host of a client class
************* Module tests.lib.os.compute.test_nova
tests/lib/os/compute/test_nova.py:442: [W0212(protected-access), 
FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access 
to a protected member _create_flavor_if_not_exists of a client class
tests/lib/os/compute/test_nova.py:445: [W0212(protected-access), 
FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access 
to a protected member _deploy_flavors of a client class
tests/lib/os/compute/test_nova.py:447: [W0212(protected-access), 
FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access 
to a protected member _create_flavor_if_not_exists of a client class
tests/lib/os/compute/test_nova.py:475: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a 
protected member _create_flavor_if_not_exists of a client class
tests/lib/os/compute/test_nova.py:476: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a 
protected member _add_flavor_access_for_tenants of a client class
tests/lib/os/compute/test_nova.py:480: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a 
protected member _deploy_flavors of a client class
tests/lib/os/compute/test_nova.py:482: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a 
protected member _add_flavor_access_for_tenants of a client class
tests/lib/os/compute/test_nova.py:510: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to 
a protected member _create_flavor_if_not_exists of a client class
tests/lib/os/compute/test_nova.py:511: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to 
a protected member _add_flavor_access_for_tenants of a client class
tests/lib/os/compute/test_nova.py:515: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to 
a protected member _deploy_flavors of a client class
tests/lib/os/compute/test_nova.py:517: [W0212(protected-access), 
FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to 
a protected member _add_flavor_access_for_tenants of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Unittests failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests/4/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/47/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/53/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/54/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/63/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/64/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/65/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/72/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/75/

**Comment by roman-verchikov** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/76/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/78/

**Comment by roman-verchikov** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/85/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/87/

**Comment by archyufa** [comment]
+1 Tested in staging. Looks good.

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/92/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/93/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/109/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/110/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/112/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/123/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/129/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/130/

**Comment by MirantisWorkloadMobility** [comment]
All checks successful.

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/133/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/134/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/135/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/138/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/139/

**Comment by roman-verchikov** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/142/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/148/

**Comment by roman-verchikov** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/149/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/151/

**Pull request merged**
