### PR TITLE
CF-378 Readable networks check

### PR DESCRIPTION
**Pull request by roman-verchikov**
Makes `CheckNetworks` pre-check output human readable.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3783/

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3784/

**Comment by antonf** [comment]
👍

**Comment by SVilgelm** [comment]
👍 can be merged

**Pull request merged**
