### PR TITLE
[WIP] Test cloudferry checking

### PR DESCRIPTION
**Pull request by SVilgelm**
foo

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/4063/

**Comment by SVilgelm** [comment]
retest checks

**Comment by SVilgelm** [comment]
retest checks

**Comment by SVilgelm** [comment]
retest checks

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/16/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/17/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/18/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/19/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/22/

**Pull request closed without merging**
