### PR TITLE
[CF-4] Fix cloudferrylib references

### PR DESCRIPTION
**Pull request by SVilgelm**
Move test_transport_instances module to the correct folder.
Rename all cloudferrylib references to cloudferry.lib.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.lib.os.actions.test_transport_instance
tests/lib/os/actions/test_transport_instance.py:64: [W0212(protected-access), 
DeployInstanceWithManualScheduling.test_tries_to_boot_vm_on_all_nodes] Access to a 
protected member _deploy_instance_on_random_host of a client class
tests/lib/os/actions/test_transport_instance.py:125: [W0212(protected-access), 
DeployInstanceWithManualScheduling.test_runs_only_one_boot_if_node_is_good] Access to a 
protected member _deploy_instance_on_random_host of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.lib.os.actions.test_transport_instance
tests/lib/os/actions/test_transport_instance.py:64: [W0212(protected-access), 
DeployInstanceWithManualScheduling.test_tries_to_boot_vm_on_all_nodes] Access to a 
protected member _deploy_instance_on_random_host of a client class
tests/lib/os/actions/test_transport_instance.py:125: [W0212(protected-access), 
DeployInstanceWithManualScheduling.test_runs_only_one_boot_if_node_is_good] Access to a 
protected member _deploy_instance_on_random_host of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
:+1: can be merged

**Pull request merged**
