### PR TITLE
[CF-482] Hide ssl warnings

### PR DESCRIPTION
**Pull request by SVilgelm**
Call disable_warnings function to hide all ssl warnings.

### CODE REVIEW

**Comment by SVilgelm** [comment]
retest this please

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by yosharma** [comment]
+1, Tested in staging environment. Fix is working fine

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
