### PR TITLE
CF-502 Disable available resources verification

### PR DESCRIPTION
**Pull request by roman-verchikov**
Resources required for VM to migrate to destination were verified
incorrectly and only considered values defined flavor, instead of
retrieving actual usage.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
I suggest remove it from the `tasks.yaml` and the action

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
+1

**Comment by SVilgelm** [comment]
👍 can be merged

**Pull request merged**
