### PR TITLE
[CF-539] Fix requirements

### PR DESCRIPTION
**Pull request by SVilgelm**
Add a protocol to the url of generator library
The format of the url should be vcs+protocol://url
Use -e flag to install nose-attribs branch.

Add oslo.serialization 2.7.0 version to the requirements.txt

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by plomakin** [comment]
Latest documentation says that "git://git" will also work well.
https://pip.readthedocs.io/en/stable/reference/pip_install/#git

**Comment by SVilgelm** [comment]
>>>
Here are the supported forms:

[-e] git+git://git.myproject.org/MyProject#egg=MyProject
[-e] git+https://git.myproject.org/MyProject#egg=MyProject
[-e] git+ssh://git.myproject.org/MyProject#egg=MyProject
-e git+git@git.myproject.org:MyProject#egg=MyProject

**Comment by plomakin** [comment]
Passing branch names, a commit hash or a tag name is possible like so:

[-e] git://git.myproject.org/MyProject.git@master#egg=MyProject
[-e] git://git.myproject.org/MyProject.git@v1.0#egg=MyProject
[-e] git://git.myproject.org/MyProject.git@da39a3ee5e6b4b0d3255bfef95601890afd80709#egg=MyProject

**Comment by jaspreetrawel** [comment]
I had tried these kind of formats at my end but they did not work. I also add --no-cache-dir to the pip install command just to make sure it does not fetch the cached copy, then also it did not work.

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by plomakin** [comment]
Let's see if it fix CF-588
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-icehouse-to-juno/270/console

**Comment by jaspreetrawel** [comment]
@SVilgelm Just sharing that during my day I already tried some of these formats at my end, but it still installed the code from pypi instead of the commit. I am not sure if I missed anything. One comment I saw somewhere that it will not work until the version of the test-generator package in nose-attribs branch of test-generator is newer than the latest version of test-generator in pypi. They suggested to change __version__ to '0.1.2' or higher in generator/version.py of test-generator code in nose-attribs branch.

**Comment by plomakin** [comment]
yeah, this change didn't help with generator version. it still from pypi

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Comment by plomakin** [comment]
+1

**Comment by SVilgelm** [comment]
👍 can be merged

**Pull request merged**
