### PR TITLE
Install bbcp to cloudferry box

### PR DESCRIPTION
**Pull request by mgrygoriev**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2812/

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2813/

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2814/

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by roman-verchikov** [comment]
@SVilgelm please take a look

**Comment by SVilgelm** [comment]
:+1: tested on local environment, can be merged

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
