### PR TITLE
SAIC-414 Added check vm with two nics migration

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by realsystem** [comment]
+1

**Comment by roman-verchikov** [comment]
In the commit message header, what is "wm"?.. Please change to something readable, I'm assuming it should be "VM" instead.

**Comment by roman-verchikov** [comment]
commit message too ;)

**Comment by roman-verchikov** [comment]
+1

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
