### PR TITLE
[CF-564] Set the final mode for the target file as 666 for bbcp

### PR DESCRIPTION
**Pull request by SVilgelm**
The default mode of targed files is 644.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
-1, I guess we should modify config for devlab instead

**Comment by SVilgelm** [comment]
Agree

**Pull request closed without merging**
