### PR TITLE
[CF-598] Fix CheckBandwith action

### PR DESCRIPTION
**Pull request by SVilgelm**
Use context manager to create and delete temporary folders on local
and remote hosts.

### CODE REVIEW

**Comment by roman-verchikov** [comment]
+1

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/86/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/88/

**Comment by MirantisWorkloadMobility** [comment]
All checks successful.

**Comment by SVilgelm** [comment]
👍 can be merged

**Pull request merged**
