### PR TITLE
Updates cinder volume config file documentation

### PR DESCRIPTION
**Pull request by roman-verchikov**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by SVilgelm** [comment]
:+1:

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by archyufa** [comment]
Please add the nfs_mount_point_bases for NFS plugins

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by archyufa** [comment]
Do we still require cinder_migration_strategy in config or this is not needed ?

**Pull request merged**
