### PR TITLE
CF-144 Fixed filter similiar vms

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
-1
Please remove 'src_info', it is not necessary:
https://github.com/MirantisWorkloadMobility/CloudFerry/blob/devel/cloudferrylib/os/actions/get_info_instances.py#L31

And fix VerifyVms, it is using the src_info. Probably we can use info_backup, but i'm not sure, need to investigate.
https://github.com/MirantisWorkloadMobility/CloudFerry/blob/devel/cloudferrylib/os/actions/verify_vms.py#L34

**Comment by ntymtsiv** [comment]
src_info has been added especially for VerifyVms (https://github.com/MirantisWorkloadMobility/CloudFerry/commit/4015b56457059f2e6e5a509c758713ebd9819a2e), so i'm not sure that we can use something else instead of src_info.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2258/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.get_info_instances
cloudferrylib/os/actions/get_info_instances.py:16: [W0611(unused-import), ] Unused import copy
************* Module cloudferrylib.os.actions.verify_vms
cloudferrylib/os/actions/verify_vms.py:71: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:76: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:80: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:85: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:89: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:106: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:108: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:186: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:291: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:820: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2259/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.verify_vms
cloudferrylib/os/actions/verify_vms.py:71: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:76: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:80: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:85: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:89: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:106: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/verify_vms.py:108: [W1202(logging-format-interpolation), VerifyVms.run] Use % formatting in logging functions and pass the % parameters as arguments
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:186: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:291: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:820: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2261/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:186: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:291: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:820: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
