### PR TITLE
[DON'T MERGE] SAIC-581 Added nets and fips creating on dst

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
MirantisWorkloadMobility

**Comment by MirantisWorkloadMobility** [comment]
MirantisWorkloadMobility

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.generate_load
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:9: [W0403(relative-import), ] Relative import 'filtering_utils', should be 'tests.filtering_utils'
devlab/tests/generate_load.py:36: [W0621(redefined-outer-name), clean_if_exists.wrapper] Redefining name 'args' from outer scope (line 1197)
devlab/tests/generate_load.py:56: [W0612(unused-variable), retry_until_resources_created.actual_decorator.wrapper] Unused variable 'i'
devlab/tests/generate_load.py:488: [W0612(unused-variable), Prerequisites.create_vms.wait_for_vm_creating] Unused variable 'i'
devlab/tests/generate_load.py:628: [W0612(unused-variable), Prerequisites.create_unassociated_fips] Unused variable 'i'
devlab/tests/generate_load.py:773: [W0612(unused-variable), Prerequisites.generate_vm_state_list] Unused variable 'i'
devlab/tests/generate_load.py:793: [W0703(broad-except), Prerequisites.delete_flavor] Catching too general exception Exception
devlab/tests/generate_load.py:977: [W0120(useless-else-on-loop), CleanEnv.clean_vms.wait_until_vms_all_deleted] Else clause on loop without a break statement
devlab/tests/generate_load.py:967: [W0612(unused-variable), CleanEnv.clean_vms.wait_until_vms_all_deleted] Unused variable 'i'
devlab/tests/generate_load.py:985: [W0106(expression-not-assigned), CleanEnv.clean_vms] Expression "[vms.append(vm) for vm in self.config.vms_from_volumes]" is assigned to nothing
devlab/tests/generate_load.py:1096: [W0703(broad-except), CleanEnv.clean_fips] Catching too general exception Exception
devlab/tests/generate_load.py:1131: [W0141(bad-builtin), CleanEnv.clean_keypairs.delete_user_keypairs] Used builtin function 'map'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1399/

**Comment by MirantisWorkloadMobility** [comment]
MirantisWorkloadMobility

**Comment by MirantisWorkloadMobility** [comment]
Functional test failure for Grizzly to Icehouse migration
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-grizzly-to-icehouse/1496/

**Comment by MirantisWorkloadMobility** [comment]
Functional test failure for Grizzly to Juno migration
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-grizzly-to-juno/610/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.generate_load
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:9: [W0403(relative-import), ] Relative import 'filtering_utils', should be 'tests.filtering_utils'
devlab/tests/generate_load.py:36: [W0621(redefined-outer-name), clean_if_exists.wrapper] Redefining name 'args' from outer scope (line 1200)
devlab/tests/generate_load.py:56: [W0612(unused-variable), retry_until_resources_created.actual_decorator.wrapper] Unused variable 'i'
devlab/tests/generate_load.py:490: [W0612(unused-variable), Prerequisites.create_vms.wait_for_vm_creating] Unused variable 'i'
devlab/tests/generate_load.py:630: [W0612(unused-variable), Prerequisites.create_unassociated_fips] Unused variable 'i'
devlab/tests/generate_load.py:775: [W0612(unused-variable), Prerequisites.generate_vm_state_list] Unused variable 'i'
devlab/tests/generate_load.py:795: [W0703(broad-except), Prerequisites.delete_flavor] Catching too general exception Exception
devlab/tests/generate_load.py:980: [W0120(useless-else-on-loop), CleanEnv.clean_vms.wait_until_vms_all_deleted] Else clause on loop without a break statement
devlab/tests/generate_load.py:970: [W0612(unused-variable), CleanEnv.clean_vms.wait_until_vms_all_deleted] Unused variable 'i'
devlab/tests/generate_load.py:988: [W0106(expression-not-assigned), CleanEnv.clean_vms] Expression "[vms.append(vm) for vm in self.config.vms_from_volumes]" is assigned to nothing
devlab/tests/generate_load.py:1099: [W0703(broad-except), CleanEnv.clean_fips] Catching too general exception Exception
devlab/tests/generate_load.py:1134: [W0141(bad-builtin), CleanEnv.clean_keypairs.delete_user_keypairs] Used builtin function 'map'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1452/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.generate_load
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:9: [W0403(relative-import), ] Relative import 'filtering_utils', should be 'tests.filtering_utils'
devlab/tests/generate_load.py:36: [W0621(redefined-outer-name), clean_if_exists.wrapper] Redefining name 'args' from outer scope (line 1200)
devlab/tests/generate_load.py:56: [W0612(unused-variable), retry_until_resources_created.actual_decorator.wrapper] Unused variable 'i'
devlab/tests/generate_load.py:490: [W0612(unused-variable), Prerequisites.create_vms.wait_for_vm_creating] Unused variable 'i'
devlab/tests/generate_load.py:630: [W0612(unused-variable), Prerequisites.create_unassociated_fips] Unused variable 'i'
devlab/tests/generate_load.py:775: [W0612(unused-variable), Prerequisites.generate_vm_state_list] Unused variable 'i'
devlab/tests/generate_load.py:795: [W0703(broad-except), Prerequisites.delete_flavor] Catching too general exception Exception
devlab/tests/generate_load.py:980: [W0120(useless-else-on-loop), CleanEnv.clean_vms.wait_until_vms_all_deleted] Else clause on loop without a break statement
devlab/tests/generate_load.py:970: [W0612(unused-variable), CleanEnv.clean_vms.wait_until_vms_all_deleted] Unused variable 'i'
devlab/tests/generate_load.py:988: [W0106(expression-not-assigned), CleanEnv.clean_vms] Expression "[vms.append(vm) for vm in self.config.vms_from_volumes]" is assigned to nothing
devlab/tests/generate_load.py:1099: [W0703(broad-except), CleanEnv.clean_fips] Catching too general exception Exception
devlab/tests/generate_load.py:1134: [W0141(bad-builtin), CleanEnv.clean_keypairs.delete_user_keypairs] Used builtin function 'map'

**Comment by MirantisWorkloadMobility** [comment]
Ready

**Comment by roman-verchikov** [comment]
Please rebase, also update pull request title in case it's still required to be merged.

**Comment by plomakin** [comment]
Need to be rebased and passed the functional checks.

**Comment by MirantisWorkloadMobility** [comment]
Can one of the admins verify this patch?

**Comment by MirantisWorkloadMobility** [comment]
Can one of the admins verify this patch?

**Comment by MirantisWorkloadMobility** [comment]
Can one of the admins verify this patch?

**Comment by MirantisWorkloadMobility** [comment]
Can one of the admins verify this patch?

**Comment by roman-verchikov** [comment]
@ntymtsiv please rebase

**Comment by ntymtsiv** [comment]
Should be finished when two external networks can be created on devlab. Close for now.

**Pull request closed without merging**
