### PR TITLE
Shutting VMs off before returning their state.

### PR DESCRIPTION
**Pull request by antonf**
Added shutting off step to the run_restore_vms_state scenario.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
👍

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Pull request merged**
