### PR TITLE
Fixed SAIC-51 partially: pep8

### PR DESCRIPTION
**Pull request by realsystem**

### CODE REVIEW

**Comment by mirrorcoder** [comment]
+1

**Comment by miarmak** [comment]
Please rebase

**Comment by miarmak** [comment]
Seems looks not bad.
 
But as for me (and PEP8 recommendations in https://www.python.org/dev/peps/pep-0008/#maximum-line-length), the preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation. But anyway, it is not a strict rule :wink:

Unit and functional tests have been passed and seems everything is OK. 
So, +1 from me.

**Comment by roman-verchikov** [comment]
Looks good, I think it's a good time to merge

**Pull request merged**
