### PR TITLE
SAIC-795 Fixed warning message 

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
$PYLINT_STATUS

**Comment by MirantisWorkloadMobility** [comment]
$PULL_STATUS
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1830/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.recreate_boot_image
cloudferrylib/os/actions/recreate_boot_image.py:47: [W0102(dangerous-default-value), ReCreateBootImage.run] Dangerous default value {} as argument
cloudferrylib/os/actions/recreate_boot_image.py:47: [W0102(dangerous-default-value), ReCreateBootImage.run] Dangerous default value {} as argument
cloudferrylib/os/actions/recreate_boot_image.py:73: [W1202(logging-format-interpolation), ReCreateBootImage.run] Use % formatting in logging functions and pass the % parameters as arguments

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Would be better with:

```
diff --git a/cloudferrylib/os/actions/recreate_boot_image.py b/cloudferrylib/os/actions/recreate_boot_image.py
index a5b5ddb..df825f4 100644
--- a/cloudferrylib/os/actions/recreate_boot_image.py
+++ b/cloudferrylib/os/actions/recreate_boot_image.py
@@ -70,12 +70,10 @@ class ReCreateBootImage(action.Action):
                     img_src_host = \
                         gl_image['meta']['instance'][0]['diff']['host_src']
                     if img_src_host != self.src_host:
-                        LOG.warning('Different host information. ' +
-                                    'Image is located on host ' +
-                                    '{img_src_host},' +
-                                    'but host in the configuration file ' +
-                                    '{src_host}.'.format(img_src_host,
-                                                         self.src_host))
+                        LOG.warning('Different host information. Image is '
+                                    'located on host "%s", but host in the '
+                                    'configuration file "%s".', img_src_host,
+                                    self.src_host)
                         continue
                     new_img = self.process_image(img_id, diff)
                     gl_image['image']['id'] = new_img['id']
```

**Comment by roman-verchikov** [comment]
Continued in https://github.com/MirantisWorkloadMobility/CloudFerry/pull/670

**Pull request closed without merging**
