### PR TITLE
[CF-577] Modify scp copier to avoid 'No space left on device' error

### PR DESCRIPTION
**Pull request by SVilgelm**
1. Copy a small part of source file to a temporary file.
2. Transfer the temporary file to the destination host.
3. Join the temporary file to the destination file.
4. Remove the temporary file on destination and source hosts.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Comment by roman-verchikov** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by japaniel** [comment]
+1 tested in staging

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
