### PR TITLE
Implementing resource plugin system.

### PR DESCRIPTION
**Pull request by Settis**
Refactoring current resource implementation and rewrite it as plugins.
Core refactoring for use plugins.
Yapsy was added as plugin engine.

### CODE REVIEW

**Comment by Wasapl** [comment]
Build finished.
Unittest failed

**Comment by Wasapl** [comment]
Unittest failed

**Comment by Settis** [comment]
Oops! I'll fix it.

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test success

**Comment by Wasapl** [comment]
Functional test success

**Comment by roman-verchikov** [comment]
Let's postpone this till we have stable prod migration

**Comment by MirantisWorkloadMobility** [comment]
Make sense.

2015-07-07 19:55 GMT+03:00 Roman Verchikov <notifications@github.com>:

**Comment by miarmak** [comment]
Are we going to continue working on it in the nearest future?

**Comment by roman-verchikov** [comment]
Closing it till better times.

**Pull request closed without merging**
