### PR TITLE
[CF-211] Fix host for `SshUtil`

### PR DESCRIPTION
**Pull request by miarmak**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.ssh_util
cloudferrylib/utils/ssh_util.py:18: [W0403(relative-import), ] Relative import 'cmd_cfg', should be 'cloudferrylib.utils.cmd_cfg'
cloudferrylib/utils/ssh_util.py:19: [W0403(relative-import), ] Relative import 'utils', should be 'cloudferrylib.utils.utils'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by wzbbbb** [comment]
It fixed my issue https://mirantis.jira.com/browse/CF-211

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
