### PR TITLE
DO NOT MERGE CF-300 Resolve bootable volumes migration

### PR DESCRIPTION
**Pull request by roman-verchikov**
Includes @ntymtsiv's patch with extended test for VM migration

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), 
CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:380: [W0613(unused-argument), 
CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module devlab.generate_load
devlab/generate_load.py:564: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:627: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2784/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), 
CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:380: [W0613(unused-argument), 
CinderStorage.convert_snapshot] Unused argument 'cloud'
************* Module devlab.generate_load
devlab/generate_load.py:564: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:627: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Pull request closed without merging**
