### PR TITLE
SAIC-457 Fixed tests for rollback verification

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by roman-verchikov** [comment]
Looks like this also requires 
```
AuthorizationFailure: Authorization Failed: Unable to establish connection to http://<src_ip>:35357/v2.0/tokens
```
to be fixed. Let's have fix for it in this pull request but with separate commit

**Comment by roman-verchikov** [comment]
@ntymtsiv please resolve in this pull request
```
AuthorizationFailure: Authorization Failed: Unable to establish connection to http://<src_ip>:35357/v2.0/tokens
```

**Comment by ntymtsiv** [comment]
It was an issue of Jenkins job configuration. Now it works.

**Comment by roman-verchikov** [comment]
+1, can be merged.

**Pull request merged**
