### PR TITLE
[CF-383] Add stage for matching objects in clouds

### PR DESCRIPTION
**Pull request by antonf**
1) Add ability to store objects of several types to Reference(many=True)
    fields.
 2) Add ``links`` attribute to base schema which will hold links to objects
    that are copies of original object.
 3) Modify Reference deserialize code to not include references to objects
    that are not exist in database. We don't want to remove any links from
    DB, but we don't want stale links to be visible to our code.
 4) Slightly refactor stages framework to store config as attribute instead
    of passing it as argument.
 5) Implement matching objects from different clouds.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.discovery.keystone
cloudferrylib/os/discovery/keystone.py:48: [E1101(no-member), Tenant.equals] Instance 
of 'Tenant' has no 'name' member
************* Module cloudferrylib.os.discovery.glance
cloudferrylib/os/discovery/glance.py:96: [E1101(no-member), Image.equals] Instance of 
'Image' has no 'tenant' member
cloudferrylib/os/discovery/glance.py:97: [E1101(no-member), Image.equals] Instance of 
'Image' has no 'name' member
cloudferrylib/os/discovery/glance.py:98: [E1101(no-member), Image.equals] Instance of 
'Image' has no 'checksum' member
cloudferrylib/os/discovery/glance.py:99: [E1101(no-member), Image.equals] Instance of 
'Image' has no 'size' member
cloudferrylib/os/discovery/glance.py:100: [E1101(no-member), Image.equals] Instance of 
'Image' has no 'is_public' member
cloudferrylib/os/discovery/glance.py:101: [E1101(no-member), Image.equals] Instance of 
'Image' has no 'container_format' member
cloudferrylib/os/discovery/glance.py:102: [E1101(no-member), Image.equals] Instance of 
'Image' has no 'disk_format' member
************* Module cloudferrylib.os.discovery.nova
cloudferrylib/os/discovery/nova.py:144: [E1101(no-member), Server.equals] Instance of 
'Server' has no 'tenant' member
cloudferrylib/os/discovery/nova.py:146: [E1101(no-member), Server.equals] Instance of 
'Server' has no 'flavor' member
cloudferrylib/os/discovery/nova.py:148: [E1101(no-member), Server.equals] Instance of 
'Server' has no 'image' member
cloudferrylib/os/discovery/nova.py:150: [E1101(no-member), Server.equals] Instance of 
'Server' has no 'key_name' member
cloudferrylib/os/discovery/nova.py:150: [E1101(no-member), Server.equals] Instance of 
'Server' has no 'name' member
************* Module cloudferrylib.os.discovery.stages
cloudferrylib/os/discovery/stages.py:110: [W0612(unused-variable), LinkStage.execute] 
Unused variable 'name'
************* Module cloudferrylib.os.discovery.model
cloudferrylib/os/discovery/model.py:514: [E1102(not-callable), Model.get_schema] 
cls.Schema is not callable
cloudferrylib/os/discovery/model.py:518: [E1102(not-callable), Model.get_schema] 
cls.Schema is not callable
cloudferrylib/os/discovery/model.py:656: [E1101(no-member), Model.link_to] Instance of 
'Model' has no 'links' member
cloudferrylib/os/discovery/model.py:659: [E1101(no-member), Model.link_to] Instance of 
'Model' has no 'links' member
cloudferrylib/os/discovery/model.py:666: [E1101(no-member), Model.find_link] Instance 
of 'Model' has no 'links' member
cloudferrylib/os/discovery/model.py:989: [W0211(bad-staticmethod-argument), 
Session._make_sql] Static method with 'cls' as first argument
************* Module fabfile
fabfile.py:128: [W0621(redefined-outer-name), condense] Redefining name 'config' from 
outer scope (line 25)

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.discovery.model
cloudferrylib/os/discovery/model.py:992: [W0211(bad-staticmethod-argument), 
Session._make_sql] Static method with 'cls' as first argument
************* Module fabfile
fabfile.py:128: [W0621(redefined-outer-name), condense] Redefining name 'config' from 
outer scope (line 25)

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module fabfile
fabfile.py:128: [W0621(redefined-outer-name), condense] Redefining name 'config' from 
outer scope (line 25)

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
