### PR TITLE
Implements SAIC-100 : mysqldump fix

### PR DESCRIPTION
**Pull request by oleksii-shyman**
- changed copying function to fabric.local + scp

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/19/

**Comment by roman-verchikov** [comment]
Looks good, +1

**Comment by miarmak** [comment]
+1

**Comment by plomakin** [comment]
It is still initiating scp from Icehouse node, not from cloudferry: 
[192.168.1.3] out: 

INFO     [/home/plomakin/Documents/CloudFerry/cloudferrylib/os/actions/snapshots.py : lineno 49]  04-16 17:44:34  EXECUTING scp -i ~/.ssh/id_rsa root@localhost:/root/dump.sql /root/dump.sql local
[localhost] local: scp -i ~/.ssh/id_rsa root@localhost:/root/dump.sql /root/dump.sql
The authenticity of host 'localhost (127.0.0.1)' can't be established.
ECDSA key fingerprint is 11:5d:55:29:8a:77:d8:08:b4:00:9b:a3:61:93:fe:e5.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
root@localhost's password: 
scp: /root/dump.sql: No such file or directory

Fatal error: local() encountered an error (return code 1) while executing 'scp -i ~/.ssh/id_rsa root@localhost:/root/dump.sql /root/dump.sql'

Aborting.
Disconnecting from 192.168.1.3... done.
local() encountered an error (return code 1) while executing 'scp -i ~/.ssh/id_rsa root@localhost:/root/dump.sql /root/dump.sql'
(.ubuntu-venv)vagrant@cloudferry:~/Documents/CloudFerry$ ll

From me its: 
-1

**Comment by oleksii-shyman** [comment]
Actually, it runs from CF node. Proof - I've added 'local("hostname")' in run section - and I see that it runs from cloudferry hostname

**Comment by oleksii-shyman** [comment]
According to your traceback - I see that You configured section dst_mysql improperly

**Comment by plomakin** [comment]
Yes, you right, need to change it in our auto-generated configuration. Thanks.

**Comment by plomakin** [comment]
+1

**Comment by roman-verchikov** [comment]
Looks like we've got three +1s, so this can be merged.

**Pull request merged**
