### PR TITLE
Changes in test configs due to changes in CF

### PR DESCRIPTION
**Pull request by plomakin**
Fixed tenants paramenters in load_generator
Added lost parameters from config.template

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/50/

**Comment by plomakin** [comment]
Will be needed for #162 testing.
Can be postponded after #162 will be merged.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/51/

**Comment by oleksii-shyman** [comment]
works for me. +1

**Comment by roman-verchikov** [comment]
Looks good, +1. Perhaps in the future we may have to introduce these changes as part of the functional code change.

**Comment by miarmak** [comment]
plomakin commented 3 hours ago
Will be needed for #162 testing.
Can be postponed after #162 will be merged.

**Comment by roman-verchikov** [comment]
> miarmak commented an hour ago

> plomakin commented 3 hours ago
Will be needed for #162 testing.
Can be postponed after #162 will be merged.

"Can" doesn't mean "must" ;)

**Comment by miarmak** [comment]
Yeah, but this patch adds to the devlab config template some fields, that has not been implemented yet) But anyway, I guess it shouldn't break anything.

**Pull request merged**
