### PR TITLE
SAIC-547 Fixed and refactored rollback test

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.rollback_verification
devlab/tests/rollback_verification.py:27: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/rollback_verification.py:28: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/rollback_verification.py:29: [W0403(relative-import), ] Relative import 'data_collector', should be 'tests.data_collector'
************* Module tests.data_collector
devlab/tests/data_collector.py:17: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/data_collector.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/data_collector.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.utils
devlab/tests/utils.py:18: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/utils.py:30: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:32: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:113: [W0621(redefined-outer-name), MigrationUtils.__init__] Redefining name 'config' from outer scope (line 18)
devlab/tests/utils.py:124: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.rollback_verification
devlab/tests/rollback_verification.py:27: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/rollback_verification.py:28: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/rollback_verification.py:29: [W0403(relative-import), ] Relative import 'data_collector', should be 'tests.data_collector'
************* Module tests.utils
devlab/tests/utils.py:18: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/utils.py:30: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:32: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:123: [W0621(redefined-outer-name), MigrationUtils.__init__] Redefining name 'config' from outer scope (line 18)
devlab/tests/utils.py:134: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.
************* Module tests.data_collector
devlab/tests/data_collector.py:17: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/data_collector.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/data_collector.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.generate_load
devlab/tests/generate_load.py:6: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/generate_load.py:7: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/generate_load.py:21: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/generate_load.py:697: [E1101(no-member), Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/tests/generate_load.py:762: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.rollback_verification
devlab/tests/rollback_verification.py:27: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/rollback_verification.py:28: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/rollback_verification.py:29: [W0403(relative-import), ] Relative import 'data_collector', should be 'tests.data_collector'
************* Module tests.utils
devlab/tests/utils.py:18: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/utils.py:35: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:37: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:109: [W0621(redefined-outer-name), MigrationUtils.__init__] Redefining name 'config' from outer scope (line 18)
devlab/tests/utils.py:120: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.
************* Module tests.data_collector
devlab/tests/data_collector.py:17: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/data_collector.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/data_collector.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/data_collector.py:51: [E1120(no-value-for-parameter), DataCollector.chose_destination_cloud] No value for argument 'configuration_ini' in constructor call

**Comment by roman-verchikov** [comment]
@ntymtsiv what's the status of this patch?

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.rollback_verification
devlab/tests/rollback_verification.py:27: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/rollback_verification.py:28: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/rollback_verification.py:29: [W0403(relative-import), ] Relative import 'data_collector', should be 'tests.data_collector'
************* Module tests.data_collector
devlab/tests/data_collector.py:17: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/data_collector.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/data_collector.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.utils
devlab/tests/utils.py:18: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/utils.py:35: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:37: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:109: [W0621(redefined-outer-name), MigrationUtils.__init__] Redefining name 'config' from outer scope (line 18)
devlab/tests/utils.py:120: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
Ready for review

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.rollback_verification
devlab/tests/rollback_verification.py:27: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/rollback_verification.py:28: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/rollback_verification.py:29: [W0403(relative-import), ] Relative import 'data_collector', should be 'tests.data_collector'
************* Module tests.data_collector
devlab/tests/data_collector.py:17: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/data_collector.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/data_collector.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.utils
devlab/tests/utils.py:18: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/utils.py:35: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:37: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:135: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.rollback_verification
devlab/tests/rollback_verification.py:28: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/rollback_verification.py:29: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/rollback_verification.py:30: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/rollback_verification.py:31: [W0403(relative-import), ] Relative import 'data_collector', should be 'tests.data_collector'
devlab/tests/rollback_verification.py:25: [W0611(unused-import), ] Unused import pprint
************* Module tests.data_collector
devlab/tests/data_collector.py:17: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/data_collector.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/data_collector.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.utils
devlab/tests/utils.py:18: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/utils.py:35: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:37: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:135: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.rollback_verification
devlab/tests/rollback_verification.py:27: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/rollback_verification.py:28: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/rollback_verification.py:29: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
devlab/tests/rollback_verification.py:30: [W0403(relative-import), ] Relative import 'data_collector', should be 'tests.data_collector'
************* Module tests.data_collector
devlab/tests/data_collector.py:17: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/data_collector.py:19: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/data_collector.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'tests.utils'
************* Module tests.utils
devlab/tests/utils.py:18: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/utils.py:35: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:37: [W0141(bad-builtin), convert] Used builtin function 'map'. Using a list comprehension can be clearer.
devlab/tests/utils.py:135: [E1129(not-context-manager), MigrationUtils.execute_command_on_vm] Context manager 'generator' doesn't implement __enter__ and __exit__.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
