### PR TITLE
[CF-215] Use RemoteRunner to get IPs for a host

### PR DESCRIPTION
**Pull request by SVilgelm**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
The real problem problem is that c18r8 can't be accessed from c1r6. And removing ssh_host = c1r6 don't fix the problem because it defaults to $host. Can you modify your patch to be like this: `cfg.StrOpt('ssh_host', default=None,
               help='ip-address of cloud node for ssh connect')`; note `default=None`

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
+1

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
