### PR TITLE
CF-380, 338 Post migration tests fail being unable to connect to VM.

### PR DESCRIPTION
**Pull request by plomakin**
Fixed external network selection logic in test setUP method.
Fixed jenkins fails to boot VM or to attach cinder volume to VM.
Fixed issues in tests:
- {{VerifyDstCloudFunctionality.test_cinder_volume}}
- {{VerifyDstCloudFunctionality.test_create_vm}}

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.tests.testcases.test_verify_dst_functionality
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py:342
: [E1101(no-member), VerifyDstCloudFunctionality.test_floating_ips_neutron_quota] 
Instance of 'VerifyDstCloudFunctionality' has no 'external_networks_ids_list' member
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py:346
: [E1101(no-member), VerifyDstCloudFunctionality.test_floating_ips_neutron_quota] 
Instance of 'VerifyDstCloudFunctionality' has no 'external_networks_ids_list' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.generate_load
cloudferry_devlab/cloudferry_devlab/generate_load.py:332: [E1101(no-member), 
Prerequisites._get_parameters_for_vm_creating.get_vm_nics] Instance of 'TenantManager' 
has no 'Tenant' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.tests.testcases.test_verify_dst_functionality
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py:17:
[E0401(import-error), ] Unable to import 'cinderclient'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py:18:
[E0401(import-error), ] Unable to import 'fabric'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py:19:
[E0401(import-error), ] Unable to import 'keystoneclient'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py:20:
[E0401(import-error), ] Unable to import 'neutronclient.common'
cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py:21:
[E0401(import-error), ] Unable to import 'novaclient'
************* Module cloudferry_devlab.generate_load
cloudferry_devlab/cloudferry_devlab/generate_load.py:22: [E0401(import-error), ] Unable 
to import 'keystoneclient'
cloudferry_devlab/cloudferry_devlab/generate_load.py:23: [E0401(import-error), ] Unable 
to import 'neutronclient.common'
cloudferry_devlab/cloudferry_devlab/generate_load.py:24: [E0401(import-error), ] Unable 
to import 'novaclient'
cloudferry_devlab/cloudferry_devlab/generate_load.py:25: [E0401(import-error), ] Unable 
to import 'yaml'

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Please update commit message to include CF-338 in title the same way we did for pull request title

**Comment by roman-verchikov** [comment]
Also please update description with more information on both problems

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
done

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
