### PR TITLE
[SAIC-677] Fix glance images deployment

### PR DESCRIPTION
**Pull request by SVilgelm**
Raise ImageDownloadError instead of HTTPNotFound

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:158: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:239: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:280: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:291: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:294: [W1202(logging-format-interpolation), GlanceImage.make_image_info] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:304: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/image/glance_image.py:334: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:347: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:353: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:362: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:365: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:385: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:418: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions but pass the % parameters as arguments
cloudferrylib/os/image/glance_image.py:444: [W1202(logging-format-interpolation), GlanceImage.deploy] Use % formatting in logging functions but pass the % parameters as arguments

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by miarmak** [comment]
+1

**Comment by mirrorcoder** [comment]
+1

**Comment by roman-verchikov** [comment]
Can be merged.

**Pull request merged**
