### PR TITLE
[CF-149] Fix filtering by tenant

### PR DESCRIPTION
**Pull request by miarmak**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.check_config_quota_neutron
cloudferrylib/os/actions/check_config_quota_neutron.py:58: [W1201(logging-not-lazy), CheckConfigQuotaNeutron.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/check_config_quota_neutron.py:28: [W0613(unused-argument), CheckConfigQuotaNeutron.run] Unused argument 'info'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
+1

**Comment by SVilgelm** [comment]
Add an information into description or title, that this patch fixes the filtering for CheckConfigQuotaNeutron action.

**Comment by miarmak** [comment]
@SVilgelm, there is a thing, it fixes filtering by tenant for all tasks, if `CheckConfigQuotaNeutron ` action is enabled =) This happens because of caching method using (`get_tenants_list `). So the fix is not especially for `CheckConfigQuotaNeutron ` task.

**Comment by roman-verchikov** [comment]
+1

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
