### PR TITLE
Fix pylint issues

### PR DESCRIPTION
**Pull request by SVilgelm**
Resolve all pylint issues.

### CODE REVIEW

**Comment by roman-verchikov** [comment]
+1

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/90/

**Comment by MirantisWorkloadMobility** [comment]
All checks successful.

**Comment by SVilgelm** [comment]
👍 can be merged

**Pull request merged**
