### PR TITLE
SAIC-8 Development environment

### PR DESCRIPTION
**Pull request by roman-verchikov**
This allows easily set up development environment using vagrant.

### CODE REVIEW

**Comment by miarmak** [comment]
I guess it needs to be rebased.

**Comment by Wasapl** [comment]
Build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/88/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/89/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/90/

**Comment by oleksii-shyman** [comment]
worked on Vagrant 1.7.2 on 3.18 linux with virtualbox 4.3.20

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/93/

**Comment by miarmak** [comment]
My env: 
- Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-76-generic x86_64)
- Vagrant 1.7.2
- Oracle VM VirtualBox Manager 4.1.12_Ubuntu
- Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 cores)
- 16 GB RAM
- HDD 150 GB free space

Issues:
- There is no access by ssh keypair from CloudFerry node to both Grizzly and Icehouse nodes (only with password)
- On Grizzly VM some troubles with MySQL happen, when trying to reach out any of OpenStack services.

Trace:
-------------------------------------------------------------------------------------------------------------------------------------------
vagrant@grizzly:~$ . openstackrc
vagrant@grizzly:~$ nova list
ERROR: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-4aabe9ae-d21e-49e5-8c92-99e52a465e25)
vagrant@grizzly:~$ nova list
ERROR: An unexpected error prevented the server from fulfilling your request. (OperationalError) (2003, "Can't connect to MySQL server on '10.0.2.15' (111)") None None (HTTP 500)
-------------------------------------------------------------------------------------------------------------------------------------------

- All VM's were created with the 1 GB RAM despite other values (4, 4 and 2 GB) in the Vagrantfile.

**Comment by roman-verchikov** [comment]
> There is no access by ssh keypair from CloudFerry node to both Grizzly and Icehouse nodes (only with password)
How did you try to connect? You should be using:
1. root user
2. make sure ssh has access to the key pair specified in Vagrantfile

I'll try to take a look at grizzly VM, I experienced similar issues during the demo.

**Comment by miarmak** [comment]
I've checked these requirements (root user, access to the ssh) one more time and gained same results.

And it is not only from CloudFerry node: from my PC if I use ssh -i <key> root@<grizzly/icehouse_ip> I have the same issue. (but 'vagrant ssh grizzly/icehouse' works fine)

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/95/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/96/

**Comment by roman-verchikov** [comment]
Please do not merge yet. I'll take a look at the memory/cpus issue.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/97/

**Comment by roman-verchikov** [comment]
Ready for merge

**Comment by mirrorcoder** [comment]
ok from my side.

**Comment by miarmak** [comment]
Everything is fine with the previous issues, but there is 1 new...
On the Icehouse OS if you create VM, it is created without the network (networks exist). But if you specify network_id manually (in the nova boot command) VM boots in ERROR state. 
Here is some trace from the /var/log/nova/nova-compute.log:
http://paste.openstack.org/show/191387/

**Comment by roman-verchikov** [comment]
@miarmak , those are the issues within the boxes themselves, and they have nothing to do with the code. I believe this can be merged unless anyone has objections.

**Pull request merged**
