### PR TITLE
CF-174 verify glance image UUIDs are kept the same

### PR DESCRIPTION
**Pull request by plomakin**
Added image id parameter to resource validation.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:378: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:378: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:673: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:683: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.testcases.test_resource_migration
devlab/tests/testcases/test_resource_migration.py:378: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:378: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\:'. String constant might be missing an r prefix.
devlab/tests/testcases/test_resource_migration.py:673: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/testcases/test_resource_migration.py:683: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
:+1: 
Also we can have the situation when the id cannot be kept if image id already exists on destination

**Comment by SVilgelm** [comment]
can be merged

**Pull request merged**
