### PR TITLE
[CF-473] Add filter-path, scenario and copy-backend options to migrate command

### PR DESCRIPTION
**Pull request by SVilgelm**
It allows to override migrate.filter_path, migrate.scenario and migrate.copy_backend options.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
looks really useful, 👍

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Please update commit message with reference to Jira ticket

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
Tested on jenkins: http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-grizzly-to-juno-test-svilgelm/81/

can be merged

**Comment by plomakin** [comment]
👍

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
