### PR TITLE
SAIC-119 Nova, keystone and neutron resources migration auto tests

### PR DESCRIPTION
**Pull request by plomakin**
Fixed prerequisites actions to use SRC and DST cloud credentials/endpoints.
Added openrc example file.
Added resource migration autotest suit.
Moved client's version constants to config.py
Added virtualenv preparation step to READ.me
Pep8 fixes.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/229/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/236/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/238/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/239/

**Comment by Wasapl** [comment]
Merged build finished. Test FAILed.   http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/6/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/20/

**Comment by roman-verchikov** [comment]
+1

**Comment by miarmak** [comment]
Looks good. +1

**Pull request merged**
