### PR TITLE
[FT] CF-311 Validate cinder quotas migration

### PR DESCRIPTION
**Pull request by ntymtsiv**
Scenario:
            1. Get nova quota parameters from src cloud
            2. Get neutron quota parameters from src cloud
            3. Get cinder quota parameters, common for src and dst clouds
            4. Get nova, neutron and cinder quotas values for each tenant from
                src cloud
            5. Get nova, neutron and cinder quotas values for each tenant from
                dst cloud
            6. Verify nova tenant quotas the same on dst and src clouds
            7. Verify neutron tenant quotas the same on dst and src clouds
            8. Verify cinder tenant quotas the same on dst and src clouds

### CODE REVIEW

**Comment by ntymtsiv** [comment]
depends on #888

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:568: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:631: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
please add test scenario to pull request description and commit message

**Comment by roman-verchikov** [comment]
Test scenario should also be documented in the code

**Comment by roman-verchikov** [comment]
retest this please

**Comment by roman-verchikov** [comment]
@ntymtsiv please resolve comments above

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:590: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:653: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:590: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:653: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:597: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:660: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
:+1: Looks good to me. Can be merged

**Pull request merged**
