### PR TITLE
[CF-164] Fix for scenario handling

### PR DESCRIPTION
**Pull request by abochkarev**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', should be 'cloud.cloud_ferry'
************* Module cloudferrylib.scheduler.scenario
cloudferrylib/scheduler/scenario.py:111: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
cloudferrylib/scheduler/scenario.py:36: [W0102(dangerous-default-value), Scenario.init_tasks] Dangerous default value {} as argument
cloudferrylib/scheduler/scenario.py:110: [W0141(bad-builtin), Scenario.get_actions] Used builtin function 'filter'. Using a list comprehension can be clearer.
cloudferrylib/scheduler/scenario.py:110: [W0110(deprecated-lambda), Scenario.get_actions] map/filter on lambda could be replaced by comprehension
cloudferrylib/scheduler/scenario.py:113: [W0141(bad-builtin), Scenario.get_actions] Used builtin function 'map'. Using a list comprehension can be clearer.
cloudferrylib/scheduler/scenario.py:113: [W0110(deprecated-lambda), Scenario.get_actions] map/filter on lambda could be replaced by comprehension
cloudferrylib/scheduler/scenario.py:53: [W0201(attribute-defined-outside-init), Scenario.init_tasks] Attribute 'tasks' defined outside __init__
cloudferrylib/scheduler/scenario.py:60: [W0201(attribute-defined-outside-init), Scenario.load_scenario] Attribute 'namespace' defined outside __init__
cloudferrylib/scheduler/scenario.py:65: [W0201(attribute-defined-outside-init), Scenario.load_scenario] Attribute 'preparation' defined outside __init__
cloudferrylib/scheduler/scenario.py:62: [W0201(attribute-defined-outside-init), Scenario.load_scenario] Attribute 'migration' defined outside __init__
cloudferrylib/scheduler/scenario.py:68: [W0201(attribute-defined-outside-init), Scenario.load_scenario] Attribute 'rollback' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by abochkarev** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', should be 'cloud.cloud_ferry'
************* Module cloudferrylib.scheduler.scenario
cloudferrylib/scheduler/scenario.py:111: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\.'. String constant might be missing an r prefix.
cloudferrylib/scheduler/scenario.py:36: [W0102(dangerous-default-value), Scenario.init_tasks] Dangerous default value {} as argument
cloudferrylib/scheduler/scenario.py:110: [W0141(bad-builtin), Scenario.get_actions] Used builtin function 'filter'. Using a list comprehension can be clearer.
cloudferrylib/scheduler/scenario.py:110: [W0110(deprecated-lambda), Scenario.get_actions] map/filter on lambda could be replaced by comprehension
cloudferrylib/scheduler/scenario.py:113: [W0141(bad-builtin), Scenario.get_actions] Used builtin function 'map'. Using a list comprehension can be clearer.
cloudferrylib/scheduler/scenario.py:113: [W0110(deprecated-lambda), Scenario.get_actions] map/filter on lambda could be replaced by comprehension
cloudferrylib/scheduler/scenario.py:53: [W0201(attribute-defined-outside-init), Scenario.init_tasks] Attribute 'tasks' defined outside __init__
cloudferrylib/scheduler/scenario.py:60: [W0201(attribute-defined-outside-init), Scenario.load_scenario] Attribute 'namespace' defined outside __init__
cloudferrylib/scheduler/scenario.py:65: [W0201(attribute-defined-outside-init), Scenario.load_scenario] Attribute 'preparation' defined outside __init__
cloudferrylib/scheduler/scenario.py:62: [W0201(attribute-defined-outside-init), Scenario.load_scenario] Attribute 'migration' defined outside __init__
cloudferrylib/scheduler/scenario.py:68: [W0201(attribute-defined-outside-init), Scenario.load_scenario] Attribute 'rollback' defined outside __init__

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
