### PR TITLE
[FT] Fixed test for server groups

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.test_resource_migration
devlab/tests/test_resource_migration.py:15: [W0403(relative-import), ] Relative import 'config', should be 'tests.config'
devlab/tests/test_resource_migration.py:16: [W0403(relative-import), ] Relative import 'test_exceptions', should be 'tests.test_exceptions'
devlab/tests/test_resource_migration.py:17: [W0403(relative-import), ] Relative import 'functional_test', should be 'tests.functional_test'
devlab/tests/test_resource_migration.py:560: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas.get_tenant_quotas] Access to a protected member _info of a client class
devlab/tests/test_resource_migration.py:570: [W0212(protected-access), ResourceMigrationTests.test_migrate_tenant_quotas] Access to a protected member _info of a client class

**Comment by ntymtsiv** [comment]
@roman-verchikov @plomakin Please take a look and merge this pull if possible (all tests are passed whit this one)

**Comment by plomakin** [comment]
+1

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
