### PR TITLE
[CF-465] Fix checking that quotas are identical

### PR DESCRIPTION
**Pull request by SVilgelm**
Update only existing quotas.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
👍 can be merged

**Pull request merged**
