### PR TITLE
CF-509 generate_load.py to create VMs sequentially.

### PR DESCRIPTION
**Pull request by plomakin**
Reworked create_all_vms method to include:
 * attach floating ip,
 * attach volume and generate data,
 * emulate status of VM.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
$PULL_STATUS
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3716/

**Comment by MirantisWorkloadMobility** [comment]
$PYLINT_STATUS

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
$PULL_STATUS
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3720/

**Comment by MirantisWorkloadMobility** [comment]
$PYLINT_STATUS

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
$PYLINT_STATUS

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3723/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.generate_load
cloudferry_devlab/cloudferry_devlab/generate_load.py:390: 
[E1205(logging-too-many-args), Prerequisites.create_vms] Too many arguments for logging 
format string

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.generate_load
cloudferry_devlab/cloudferry_devlab/generate_load.py:390: [W1201(logging-not-lazy), 
Prerequisites.create_vms] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by antonf** [comment]
👍

**Pull request merged**
