### PR TITLE
CF-295 update tests to create external neutron router.

### PR DESCRIPTION
**Pull request by plomakin**
Fixed dst_cloud object initialization.
Added external router generation on dst, and network assignment.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:585: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:648: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2902/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:586: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:649: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2905/

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2906/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:586: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:649: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:586: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:649: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:591: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:654: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
:+1: Looks good to me

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
