### PR TITLE
CF-317 Networking migration documentation

### PR DESCRIPTION
**Pull request by roman-verchikov**
Documents how neutron networking objects are migrated:

 - Networks
 - Subnets
 - Floating IPs
 - Security groups
 - Ports
 - Routers

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
