### PR TITLE
[SAIC-416] Add `connection_attempts` option to config

### PR DESCRIPTION
**Pull request by miarmak**
For all Fabric SSH connections in the project.

### CODE REVIEW

**Comment by roman-verchikov** [comment]
@miarmak please modify to have number of connection attempts configurable, I'd suggest that you put config option to [migrate]

**Comment by Settis** [comment]
Oh, so many place to change. Maybe is better way to wrap `settings` and provide `connection_attempts` only in one place in code?

**Comment by roman-verchikov** [comment]
Looks good to me, but needs rebase

**Comment by miarmak** [comment]
@Settis We already have a task (SAIC-472) for it. Will do it some day (based on priorities).

**Comment by realsystem** [comment]
+1

**Comment by roman-verchikov** [comment]
Looks ok, can be merged

**Pull request merged**
