### PR TITLE
[SAIC-697] Check networks fails on instances which are…

### PR DESCRIPTION
**Pull request by SVilgelm**
… not spawned in external networks

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.check_networks
cloudferrylib/os/actions/check_networks.py:278: [W1201(logging-not-lazy), NetworkInfo.get_overlapped_networks] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/check_networks.py:321: [W1201(logging-not-lazy), Network.check_network_overlapping] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.check_networks
cloudferrylib/os/actions/check_networks.py:242: [W1201(logging-not-lazy), NetworkInfo.get_overlapped_networks] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/check_networks.py:285: [W1201(logging-not-lazy), Network.check_network_overlapping] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1633/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.check_networks
cloudferrylib/os/actions/check_networks.py:242: [W1201(logging-not-lazy), NetworkInfo.get_overlapped_networks] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/check_networks.py:285: [W1201(logging-not-lazy), Network.check_network_overlapping] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Looks good, +1

**Pull request merged**
