### PR TITLE
SAIC-73. Fix icehouse and grizzly dev env

### PR DESCRIPTION
**Pull request by roman-verchikov**
- Fixes invalid neutron configuration on icehouse VM
- Moves all boxes to shared account, not tied to any personal account

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/118/

**Comment by roman-verchikov** [comment]
I kindly ask others to try if this actually works. Steps:

1 Build dev environment 
```
git clone https://github.com/roman-verchikov/CloudFerry.git
cd CloudFerry
git checkout -b fix-icehouse-dev-env origin/fix-icehouse-dev-env
cd devlab
vagrant up
 ```
2 Verify connectivity
```
for vm in grizzly icehouse cloudferry; do
   vagrant ssh $vm
   for ip in 192.168.1.$(seq 2..4); do
      ping $ip
   done
done
```
3 Verify openstack services
```
for vm in grizzly icehouse; do
   if [[ $vm -eq 'grizzly' ]]; then 
       netclient=quantum
   else
       netclient=neutron
   fi
   vagrant ssh $vm
   source openstackrc
   nova list
   netclient net-list
   netclient net-create testnet
   netclient subnet-create testnet 1.1.1.0/24
   nova boot --flavor 1 --image <image-id> --nic net-id=<testnet-id> testvm
done
```

**Comment by Settis** [comment]
Please add .ubuntu-venv and devlab/.vagrant in gitignore file.

**Comment by Settis** [comment]
@roman-verchikov all your verifying steps are work.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/123/

**Comment by Settis** [comment]
Thanks for readme. +1

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/CloudFerry_PR_checks/124/

**Comment by miarmak** [comment]
Tested all this cases. Works fine. At least for me)
+1

**Pull request merged**
