### PR TITLE
Fix for CF-10 : keystone exception handling

### PR DESCRIPTION
**Pull request by raiesmh08**
Sometimes during authorization process we can get some exception,
raised by some temporary conditions: network instability, auth-backend
unavailability and others not related to wrong credentials.
When this encountered, cloudferry lack handling of such situations.

This patch provides fix for above situations.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:201: [W0221(arguments-differ), 
KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' 
method
************* Module tests.cloudferrylib.os.identity.test_keystone
tests/cloudferrylib/os/identity/test_keystone.py:248: [W0212(protected-access), 
KeystoneIdentityTestCase.test_read_info] Access to a protected member 
_get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:249: [W0212(protected-access), 
KeystoneIdentityTestCase.test_read_info] Access to a protected member 
_get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:271: [W0613(unused-argument), 
KeystoneIdentityTestCase.test_deploy.tenant_create] Unused argument 'kwargs'
tests/cloudferrylib/os/identity/test_keystone.py:276: [W0613(unused-argument), 
KeystoneIdentityTestCase.test_deploy.user_create] Unused argument 'kwars'
tests/cloudferrylib/os/identity/test_keystone.py:281: [W0613(unused-argument), 
KeystoneIdentityTestCase.test_deploy.roles_create] Unused argument 'role_name'
tests/cloudferrylib/os/identity/test_keystone.py:482: [W0212(protected-access), 
KeystoneClientTestCase.test_adds_region_if_set_in_config] Access to a protected 
member _get_client_by_creds of a client class
tests/cloudferrylib/os/identity/test_keystone.py:514: [W0212(protected-access), 
KeystoneClientTestCase.test_does_not_add_region_if_not_set_in_config] Access to 
a protected member _get_client_by_creds of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:201: [W0221(arguments-differ), 
KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' 
method
************* Module tests.cloudferrylib.os.identity.test_keystone
tests/cloudferrylib/os/identity/test_keystone.py:248: [W0212(protected-access), 
KeystoneIdentityTestCase.test_read_info] Access to a protected member 
_get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:249: [W0212(protected-access), 
KeystoneIdentityTestCase.test_read_info] Access to a protected member 
_get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:271: [W0613(unused-argument), 
KeystoneIdentityTestCase.test_deploy.tenant_create] Unused argument 'kwargs'
tests/cloudferrylib/os/identity/test_keystone.py:276: [W0613(unused-argument), 
KeystoneIdentityTestCase.test_deploy.user_create] Unused argument 'kwars'
tests/cloudferrylib/os/identity/test_keystone.py:281: [W0613(unused-argument), 
KeystoneIdentityTestCase.test_deploy.roles_create] Unused argument 'role_name'
tests/cloudferrylib/os/identity/test_keystone.py:482: [W0212(protected-access), 
KeystoneClientTestCase.test_adds_region_if_set_in_config] Access to a protected 
member _get_client_by_creds of a client class
tests/cloudferrylib/os/identity/test_keystone.py:514: [W0212(protected-access), 
KeystoneClientTestCase.test_does_not_add_region_if_not_set_in_config] Access to 
a protected member _get_client_by_creds of a client class

**Comment by raiesmh08** [comment]
I will test it on Monday. Actually my setup got down. And I am unable to access jenkins log link from here (India). 
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-functional-tests-grizzly-to-juno/1930/ is opening from here.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Comment by SVilgelm** [comment]
can be merged, the errors of failed jobs are not related to this patch
:+1:

**Pull request merged**
