### PR TITLE
SAIC-141: Renamed load generator

### PR DESCRIPTION
**Pull request by plomakin**
Fixed readme description
Changes in config.py file - fixed tenants parameters.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/43/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/47/

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/48/

**Comment by roman-verchikov** [comment]
Many changes introduced with this commit are not related to renaming. Please split into separate commits and pull requests.

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.  http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/49/

**Comment by roman-verchikov** [comment]
Good, +1

**Comment by oleksii-shyman** [comment]
Good, +1

**Pull request merged**
