### PR TITLE
SAIC-701 Typo in generate_load_real_env.py wait_for_volume usage

### PR DESCRIPTION
**Pull request by cburns-mirantis**
In file generate_load_real_env.py it uses the call to the function wait_for_volume,
definition of the function is in generate_load.py with function name wait_for_volumes.
Its typo error so needs to be changed

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module tests.generate_load_real_env
devlab/tests/generate_load_real_env.py:3: [W0403(relative-import), ] Relative import 'generate_load', should be 'tests.generate_load'
devlab/tests/generate_load_real_env.py:4: [W0403(relative-import), ] Relative import 'real_env_conf', should be 'tests.real_env_conf'
devlab/tests/generate_load_real_env.py:25: [W0703(broad-except), Prerequisites.create_keypairs] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:60: [W0221(arguments-differ), Prerequisites.create_networks] Arguments number differs from overridden 'create_networks' method
devlab/tests/generate_load_real_env.py:69: [E1101(no-member), Prerequisites.create_all_networking] Instance of 'Prerequisites' has no 'create_router' member
devlab/tests/generate_load_real_env.py:85: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'Prerequisites' has no 'wait_for_volumes' member
devlab/tests/generate_load_real_env.py:91: [E1101(no-member), Prerequisites.create_cinder_volumes] Instance of 'Prerequisites' has no 'wait_for_volumes' member
devlab/tests/generate_load_real_env.py:149: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:155: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:161: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:169: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:175: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:182: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:188: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:194: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:201: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:210: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:218: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception
devlab/tests/generate_load_real_env.py:226: [W0703(broad-except), Prerequisites.clean_objects] Catching too general exception Exception

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
Looks ok, but I'm still not sure why we keep modifying non-working script with super minor changes.

**Comment by roman-verchikov** [comment]
Closing this in favor of fully-featured `generate_load_real_env.py` which is TBD

**Pull request closed without merging**
