### PR TITLE
[SAIC-732] Fix `speed_limit` for Images transfer

### PR DESCRIPTION
**Pull request by miarmak**
Fix `speed_limit` issue in `cloudferrylib.utils.file_like_proxy`, that
is used for speed limitation while Glance images and snapshots are
transferring.

Update configs with the new values of `speed_limit` option and it's
description.

Remove unused `speed_limit` fake config option from unit tests.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.utils.file_like_proxy
cloudferrylib/utils/file_like_proxy.py:20: [W0403(relative-import), ] Relative import 'utils', should be 'cloudferrylib.utils.utils'
cloudferrylib/utils/file_like_proxy.py:59: [W0141(bad-builtin), FileLikeProxy._parse_speed_limit] Used builtin function 'filter'
cloudferrylib/utils/file_like_proxy.py:74: [E0202(method-hidden), FileLikeProxy.read] An attribute defined in cloudferrylib.utils.file_like_proxy line 43 hides this method
************* Module tests.cloudferrylib.os.image.test_glance_image
tests/cloudferrylib/os/image/test_glance_image.py:46: [E1002(super-on-old-class), GlanceImageTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/os/image/test_glance_image.py:50: [W0212(protected-access), GlanceImageTestCase.setUp] Access to a protected member _resp of a client class
************* Module tests.cloudferrylib.os.network.test_nova_network
tests/cloudferrylib/os/network/test_nova_network.py:37: [E1002(super-on-old-class), TestNovaNetwork.setUp] Use of super on an old style class
************* Module tests.cloudferrylib.os.compute.test_nova
tests/cloudferrylib/os/compute/test_nova.py:44: [E1002(super-on-old-class), NovaComputeTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/os/compute/test_nova.py:160: [E1101(no-member), NovaComputeTestCase.test_change_status_same] Instance of 'NovaComputeTestCase' has no 'assertFalse' member
tests/cloudferrylib/os/compute/test_nova.py:170: [E1101(no-member), NovaComputeTestCase.test_shutoff_to_verify_resize_brings_instance_active] Instance of 'NovaComputeTestCase' has no 'assertTrue' member
tests/cloudferrylib/os/compute/test_nova.py:235: [E1101(no-member), NovaComputeTestCase.test_down_hosts_are_skipped] Instance of 'NovaComputeTestCase' has no 'assertTrue' member
tests/cloudferrylib/os/compute/test_nova.py:257: [E1101(no-member), NovaComputeTestCase.test_disabled_hosts_are_skipped] Instance of 'NovaComputeTestCase' has no 'assertTrue' member
tests/cloudferrylib/os/compute/test_nova.py:279: [E1101(no-member), NovaComputeTestCase.test_disabled_down_hosts_are_skipped] Instance of 'NovaComputeTestCase' has no 'assertTrue' member
tests/cloudferrylib/os/compute/test_nova.py:338: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_updated_with_destination_id] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:339: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_updated_with_destination_id] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:365: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_updated_with_destination_id] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:368: [E1101(no-member), FlavorDeploymentTestCase.test_flavor_is_updated_with_destination_id] Instance of 'FlavorDeploymentTestCase' has no 'assertTrue' member
tests/cloudferrylib/os/compute/test_nova.py:392: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:395: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:397: [W0212(protected-access), FlavorDeploymentTestCase.test_flavor_is_not_created_if_already_exists_on_dest] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:416: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:417: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:421: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:423: [W0212(protected-access), FlavorDeploymentTestCase.test_access_not_updated_for_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:442: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _create_flavor_if_not_exists of a client class
tests/cloudferrylib/os/compute/test_nova.py:443: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
tests/cloudferrylib/os/compute/test_nova.py:447: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _deploy_flavors of a client class
tests/cloudferrylib/os/compute/test_nova.py:449: [W0212(protected-access), FlavorDeploymentTestCase.test_access_list_is_updated_for_non_public_flavors] Access to a protected member _add_flavor_access_for_tenants of a client class
************* Module tests.cloudferrylib.os.identity.test_keystone
tests/cloudferrylib/os/identity/test_keystone.py:49: [E1002(super-on-old-class), KeystoneIdentityTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/os/identity/test_keystone.py:109: [E1101(no-member), KeystoneIdentityTestCase.test_get_client_generates_new_token] Instance of 'KeystoneIdentityTestCase' has no 'assertFalse' member
tests/cloudferrylib/os/identity/test_keystone.py:214: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:215: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:237: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.tenant_create] Unused argument 'kwargs'
tests/cloudferrylib/os/identity/test_keystone.py:242: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.user_create] Unused argument 'kwars'
tests/cloudferrylib/os/identity/test_keystone.py:247: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.roles_create] Unused argument 'role_name'
tests/cloudferrylib/os/identity/test_keystone.py:447: [W0212(protected-access), KeystoneClientTestCase.test_adds_region_if_set_in_config] Access to a protected member _get_client_by_creds of a client class
tests/cloudferrylib/os/identity/test_keystone.py:479: [W0212(protected-access), KeystoneClientTestCase.test_does_not_add_region_if_not_set_in_config] Access to a protected member _get_client_by_creds of a client class
************* Module tests.cloudferrylib.os.network.test_neutron
tests/cloudferrylib/os/network/test_neutron.py:47: [E1002(super-on-old-class), NeutronTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/os/network/test_neutron.py:185: [E1101(no-member), NeutronTestCase.test_get_quotas] Instance of 'NeutronTestCase' has no 'assertDictEqual' member
tests/cloudferrylib/os/network/test_neutron.py:187: [E1101(no-member), NeutronTestCase.test_get_quotas] Instance of 'NeutronTestCase' has no 'assertDictEqual' member
tests/cloudferrylib/os/network/test_neutron.py:190: [E1101(no-member), NeutronTestCase.test_get_quotas] Instance of 'NeutronTestCase' has no 'assertDictEqual' member
tests/cloudferrylib/os/network/test_neutron.py:195: [E1101(no-member), NeutronTestCase.test_get_quotas] Instance of 'NeutronTestCase' has no 'assertDictEqual' member
tests/cloudferrylib/os/network/test_neutron.py:200: [E1101(no-member), NeutronTestCase.test_get_quotas] Instance of 'NeutronTestCase' has no 'assertDictEqual' member
************* Module tests.cloudferrylib.os.storage.test_cinder_storage
tests/cloudferrylib/os/storage/test_cinder_storage.py:46: [E1002(super-on-old-class), CinderStorageTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/os/storage/test_cinder_storage.py:232: [W0703(broad-except), CinderStorageTestCase.test_get_volume_path_iscsi_error] Catching too general exception Exception

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Comment by roman-verchikov** [comment]
works in staging, can be merged

**Comment by archyufa** [comment]
+1 Tested in Lab. Will be good to add check if parametre speed_limit was introduced incorrectly. Or we only going to use "off" now

**Comment by miarmak** [comment]
I've already added this check into this commit. We'll disable `speed_limit` option and use default value for it (`off`), if it is introduced incorrectly.

**Pull request merged**
