### PR TITLE
CF-509 generate_load.py to create VMs sequentially.

### PR DESCRIPTION
**Pull request by plomakin**
Reworked create_all_vms method to include:
 * attach floating ip,
 * attach volume and generate data,
 * emulate status of VM.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferry_devlab.generate_load
cloudferry_devlab/cloudferry_devlab/generate_load.py:1091: 
[E1120(no-value-for-parameter), Prerequisites.run_restore_vms_state] No value for 
argument 'vm_id' in method call
cloudferry_devlab/cloudferry_devlab/generate_load.py:19: [W0611(unused-import), ] 
Unused import time

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3713/

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3714/

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3715/

**Pull request closed without merging**
