### PR TITLE
SAIC-191: Load generator should generate VMs in different states.

### PR DESCRIPTION
**Pull request by plomakin**
Added method to emulate vm's statuses.
Added config options.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by roman-verchikov** [comment]
+1

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Comment by miarmak** [comment]
+1

**Comment by Wasapl** [comment]
Merged build finished. Test PASSed.

**Pull request merged**
