### PR TITLE
SAIC-264 cloudferry VM devlab provisioning fix

### PR DESCRIPTION
**Pull request by roman-verchikov**
- Removed dependency on cloudferry repo path from configuration - less
   options to configure!
 - Fixed requirements installation occured due to working directory
   stayed home of root user (invalid `sudo` invocation).

### CODE REVIEW

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test success

**Comment by Wasapl** [comment]
Functional test success

**Comment by VitaliiYerys** [comment]
+1

**Comment by roman-verchikov** [comment]
Can be merged

**Pull request merged**
