### PR TITLE
[For review and testing] Recovering from a failed migration steps

### PR DESCRIPTION
**Pull request by mirrorcoder**
- Snapshot namespace
- Restore namespace from snapshot
- Recovery work was interrupted step

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.vm_snapshot
cloudferrylib/os/actions/vm_snapshot.py:45: [W0613(unused-argument), VmSnapshot.run] Unused argument 'args'
cloudferrylib/os/actions/vm_snapshot.py:71: [W0613(unused-argument), CheckPointVm.run] Unused argument 'args'
cloudferrylib/os/actions/vm_snapshot.py:105: [W1201(logging-not-lazy), VmRestore.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/vm_snapshot.py:106: [W1201(logging-not-lazy), VmRestore.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/vm_snapshot.py:108: [W1201(logging-not-lazy), VmRestore.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/vm_snapshot.py:109: [W1201(logging-not-lazy), VmRestore.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/vm_snapshot.py:113: [W1202(logging-format-interpolation), VmRestore.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/vm_snapshot.py:118: [W1202(logging-format-interpolation), VmRestore.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/vm_snapshot.py:90: [W0613(unused-argument), VmRestore.run] Unused argument 'args'
************* Module cloudferrylib.scheduler.namespace
cloudferrylib/scheduler/namespace.py:25: [W0232(no-init), ConvertNamespace] Class has no __init__ method
cloudferrylib/scheduler/namespace.py:80: [W0102(dangerous-default-value), Namespace.__init__] Dangerous default value {} as argument
cloudferrylib/scheduler/namespace.py:91: [W0102(dangerous-default-value), Namespace.snapshot] Dangerous default value [] as argument
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', should be 'cloud.cloud_ferry'
cloud/os2os.py:107: [W0221(arguments-differ), OS2OSFerry.migrate] Arguments number differs from overridden 'migrate' method
cloud/os2os.py:151: [W0621(redefined-outer-name), OS2OSFerry.check_cloud] Redefining name 'cloud' from outer scope (line 16)
************* Module cloudferrylib.scheduler.scheduler
cloudferrylib/scheduler/scheduler.py:23: [W0403(relative-import), ] Relative import 'cursor', should be 'cloudferrylib.scheduler.cursor'
cloudferrylib/scheduler/scheduler.py:24: [W0403(relative-import), ] Relative import 'signal_handler', should be 'cloudferrylib.scheduler.signal_handler'
cloudferrylib/scheduler/scheduler.py:25: [W0403(relative-import), ] Relative import 'task', should be 'cloudferrylib.scheduler.task'
cloudferrylib/scheduler/scheduler.py:26: [W0403(relative-import), ] Relative import 'thread_tasks', should be 'cloudferrylib.scheduler.thread_tasks'
cloudferrylib/scheduler/scheduler.py:57: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'task'
cloudferrylib/scheduler/scheduler.py:57: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'e'
cloudferrylib/scheduler/scheduler.py:75: [W0703(broad-except), BaseScheduler.process_chain] Catching too general exception Exception
cloudferrylib/scheduler/scheduler.py:84: [W0201(attribute-defined-outside-init), BaseScheduler.process_chain] Attribute 'exception' defined outside __init__
cloudferrylib/scheduler/scheduler.py:107: [W0201(attribute-defined-outside-init), BaseScheduler.addCursor] Attribute 'cursor' defined outside __init__
************* Module fabfile
fabfile.py:50: [W0621(redefined-outer-name), migrate] Redefining name 'restore' from outer scope (line 70)
fabfile.py:61: [E1123(unexpected-keyword-arg), migrate] Unexpected keyword argument 'restore' in method call
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:232: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:312: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:376: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:195: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/identity/keystone.py:575: [W0612(unused-variable), KeystoneIdentity._get_roles_sql_request] Unused variable 'type_record'
cloudferrylib/os/identity/keystone.py:576: [W0612(unused-variable), KeystoneIdentity._get_roles_sql_request] Unused variable 'inher_tmp'
cloudferrylib/os/identity/keystone.py:622: [W0141(bad-builtin), KeystoneIdentity._get_user_tenants_roles_by_db] Used builtin function 'map'. Using a list comprehension can be clearer.
cloudferrylib/os/identity/keystone.py:622: [W0110(deprecated-lambda), KeystoneIdentity._get_user_tenants_roles_by_db] map/filter on lambda could be replaced by comprehension

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1956/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.vm_snapshot
cloudferrylib/os/actions/vm_snapshot.py:45: [W0613(unused-argument), VmSnapshot.run] Unused argument 'args'
cloudferrylib/os/actions/vm_snapshot.py:71: [W0613(unused-argument), CheckPointVm.run] Unused argument 'args'
cloudferrylib/os/actions/vm_snapshot.py:105: [W1201(logging-not-lazy), VmRestore.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/vm_snapshot.py:106: [W1201(logging-not-lazy), VmRestore.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/vm_snapshot.py:108: [W1201(logging-not-lazy), VmRestore.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/vm_snapshot.py:109: [W1201(logging-not-lazy), VmRestore.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/vm_snapshot.py:113: [W1202(logging-format-interpolation), VmRestore.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/vm_snapshot.py:118: [W1202(logging-format-interpolation), VmRestore.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/vm_snapshot.py:90: [W0613(unused-argument), VmRestore.run] Unused argument 'args'
************* Module cloudferrylib.scheduler.namespace
cloudferrylib/scheduler/namespace.py:25: [W0232(no-init), ConvertNamespace] Class has no __init__ method
cloudferrylib/scheduler/namespace.py:80: [W0102(dangerous-default-value), Namespace.__init__] Dangerous default value {} as argument
cloudferrylib/scheduler/namespace.py:91: [W0102(dangerous-default-value), Namespace.snapshot] Dangerous default value [] as argument
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', should be 'cloud.cloud_ferry'
cloud/os2os.py:107: [W0221(arguments-differ), OS2OSFerry.migrate] Arguments number differs from overridden 'migrate' method
cloud/os2os.py:151: [W0621(redefined-outer-name), OS2OSFerry.check_cloud] Redefining name 'cloud' from outer scope (line 16)
************* Module cloudferrylib.scheduler.scheduler
cloudferrylib/scheduler/scheduler.py:23: [W0403(relative-import), ] Relative import 'cursor', should be 'cloudferrylib.scheduler.cursor'
cloudferrylib/scheduler/scheduler.py:24: [W0403(relative-import), ] Relative import 'signal_handler', should be 'cloudferrylib.scheduler.signal_handler'
cloudferrylib/scheduler/scheduler.py:25: [W0403(relative-import), ] Relative import 'task', should be 'cloudferrylib.scheduler.task'
cloudferrylib/scheduler/scheduler.py:26: [W0403(relative-import), ] Relative import 'thread_tasks', should be 'cloudferrylib.scheduler.thread_tasks'
cloudferrylib/scheduler/scheduler.py:57: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'task'
cloudferrylib/scheduler/scheduler.py:57: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'e'
cloudferrylib/scheduler/scheduler.py:75: [W0703(broad-except), BaseScheduler.process_chain] Catching too general exception Exception
cloudferrylib/scheduler/scheduler.py:84: [W0201(attribute-defined-outside-init), BaseScheduler.process_chain] Attribute 'exception' defined outside __init__
cloudferrylib/scheduler/scheduler.py:107: [W0201(attribute-defined-outside-init), BaseScheduler.addCursor] Attribute 'cursor' defined outside __init__
************* Module fabfile
fabfile.py:50: [W0621(redefined-outer-name), migrate] Redefining name 'restore' from outer scope (line 70)
fabfile.py:61: [E1123(unexpected-keyword-arg), migrate] Unexpected keyword argument 'restore' in method call
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:232: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:312: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:376: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:195: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/identity/keystone.py:575: [W0612(unused-variable), KeystoneIdentity._get_roles_sql_request] Unused variable 'type_record'
cloudferrylib/os/identity/keystone.py:576: [W0612(unused-variable), KeystoneIdentity._get_roles_sql_request] Unused variable 'inher_tmp'
cloudferrylib/os/identity/keystone.py:622: [W0141(bad-builtin), KeystoneIdentity._get_user_tenants_roles_by_db] Used builtin function 'map'. Using a list comprehension can be clearer.
cloudferrylib/os/identity/keystone.py:622: [W0110(deprecated-lambda), KeystoneIdentity._get_user_tenants_roles_by_db] map/filter on lambda could be replaced by comprehension

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1957/

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2032/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.vm_snapshot
cloudferrylib/os/actions/vm_snapshot.py:45: [W0613(unused-argument), VmSnapshot.run] Unused argument 'args'
cloudferrylib/os/actions/vm_snapshot.py:71: [W0613(unused-argument), CheckPointVm.run] Unused argument 'args'
cloudferrylib/os/actions/vm_snapshot.py:114: [W1202(logging-format-interpolation), VmRestore.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/vm_snapshot.py:119: [W1202(logging-format-interpolation), VmRestore.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/vm_snapshot.py:91: [W0613(unused-argument), VmRestore.run] Unused argument 'args'
************* Module cloudferrylib.scheduler.namespace
cloudferrylib/scheduler/namespace.py:26: [W0232(no-init), ConvertNamespace] Class has no __init__ method
cloudferrylib/scheduler/namespace.py:81: [W0102(dangerous-default-value), Namespace.__init__] Dangerous default value {} as argument
cloudferrylib/scheduler/namespace.py:92: [W0102(dangerous-default-value), Namespace.snapshot] Dangerous default value [] as argument
cloudferrylib/scheduler/namespace.py:117: [E1101(no-member), Namespace.restore] Instance of 'object' has no 'iteritems' member
************* Module cloudferrylib.scheduler.scheduler
cloudferrylib/scheduler/scheduler.py:23: [W0403(relative-import), ] Relative import 'cursor', should be 'cloudferrylib.scheduler.cursor'
cloudferrylib/scheduler/scheduler.py:24: [W0403(relative-import), ] Relative import 'signal_handler', should be 'cloudferrylib.scheduler.signal_handler'
cloudferrylib/scheduler/scheduler.py:25: [W0403(relative-import), ] Relative import 'task', should be 'cloudferrylib.scheduler.task'
cloudferrylib/scheduler/scheduler.py:26: [W0403(relative-import), ] Relative import 'thread_tasks', should be 'cloudferrylib.scheduler.thread_tasks'
cloudferrylib/scheduler/scheduler.py:27: [E0401(import-error), ] Unable to import 'oslo.config.cfg'
cloudferrylib/scheduler/scheduler.py:57: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'task'
cloudferrylib/scheduler/scheduler.py:57: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'e'
cloudferrylib/scheduler/scheduler.py:75: [W0703(broad-except), BaseScheduler.process_chain] Catching too general exception Exception
cloudferrylib/scheduler/scheduler.py:84: [W0201(attribute-defined-outside-init), BaseScheduler.process_chain] Attribute 'exception' defined outside __init__
cloudferrylib/scheduler/scheduler.py:107: [W0201(attribute-defined-outside-init), BaseScheduler.addCursor] Attribute 'cursor' defined outside __init__
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', should be 'cloud.cloud_ferry'
cloud/os2os.py:107: [W0221(arguments-differ), OS2OSFerry.migrate] Arguments number differs from overridden 'migrate' method
cloud/os2os.py:162: [W0621(redefined-outer-name), OS2OSFerry.check_cloud] Redefining name 'cloud' from outer scope (line 16)
************* Module fabfile
fabfile.py:15: [E0401(import-error), ] Unable to import 'fabric.api'
fabfile.py:38: [E0401(import-error), ] Unable to import 'oslo.config.cfg'
fabfile.py:50: [W0621(redefined-outer-name), migrate] Redefining name 'restore' from outer scope (line 71)
fabfile.py:61: [E1123(unexpected-keyword-arg), migrate] Unexpected keyword argument 'restore' in method call
************* Module tests.scheduler.test_scheduler
tests/scheduler/test_scheduler.py:16: [E0401(import-error), ] Unable to import 'mock'
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:16: [E0401(import-error), ] Unable to import 'pika'
cloudferrylib/os/identity/keystone.py:19: [E0401(import-error), ] Unable to import 'keystoneclient'
cloudferrylib/os/identity/keystone.py:20: [E0401(import-error), ] Unable to import 'keystoneclient'
cloudferrylib/os/identity/keystone.py:21: [E0401(import-error), ] Unable to import 'keystoneclient.v2_0'
cloudferrylib/os/identity/keystone.py:30: [E0401(import-error), ] Unable to import 'sqlalchemy.exc'
cloudferrylib/os/identity/keystone.py:193: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method
************* Module tests.cloudferrylib.os.identity.test_keystone
tests/cloudferrylib/os/identity/test_keystone.py:17: [E0401(import-error), ] Unable to import 'mock'
tests/cloudferrylib/os/identity/test_keystone.py:19: [E0401(import-error), ] Unable to import 'keystoneclient'
tests/cloudferrylib/os/identity/test_keystone.py:20: [E0401(import-error), ] Unable to import 'keystoneclient.v2_0'
tests/cloudferrylib/os/identity/test_keystone.py:21: [E0401(import-error), ] Unable to import 'oslotest'
tests/cloudferrylib/os/identity/test_keystone.py:49: [E1002(super-on-old-class), KeystoneIdentityTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/os/identity/test_keystone.py:214: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:215: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:237: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.tenant_create] Unused argument 'kwargs'
tests/cloudferrylib/os/identity/test_keystone.py:242: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.user_create] Unused argument 'kwars'
tests/cloudferrylib/os/identity/test_keystone.py:247: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.roles_create] Unused argument 'role_name'
tests/cloudferrylib/os/identity/test_keystone.py:447: [W0212(protected-access), KeystoneClientTestCase.test_adds_region_if_set_in_config] Access to a protected member _get_client_by_creds of a client class
tests/cloudferrylib/os/identity/test_keystone.py:479: [W0212(protected-access), KeystoneClientTestCase.test_does_not_add_region_if_not_set_in_config] Access to a protected member _get_client_by_creds of a client class
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:22: [E0401(import-error), ] Unable to import 'fabric.api'
cloudferrylib/os/image/glance_image.py:23: [E0401(import-error), ] Unable to import 'fabric.api'
cloudferrylib/os/image/glance_image.py:25: [E0401(import-error), ] Unable to import 'glanceclient'
cloudferrylib/os/image/glance_image.py:26: [E0401(import-error), ] Unable to import 'glanceclient'
cloudferrylib/os/image/glance_image.py:27: [E0401(import-error), ] Unable to import 'glanceclient.v1.images'
cloudferrylib/os/image/glance_image.py:29: [E0401(import-error), ] Unable to import 'keystoneclient'
cloudferrylib/os/image/glance_image.py:224: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:304: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:368: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method

**Comment by mirrorcoder** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.vm_snapshot
cloudferrylib/os/actions/vm_snapshot.py:45: [W0613(unused-argument), VmSnapshot.run] Unused argument 'args'
cloudferrylib/os/actions/vm_snapshot.py:71: [W0613(unused-argument), CheckPointVm.run] Unused argument 'args'
cloudferrylib/os/actions/vm_snapshot.py:114: [W1202(logging-format-interpolation), VmRestore.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/vm_snapshot.py:119: [W1202(logging-format-interpolation), VmRestore.run] Use % formatting in logging functions and pass the % parameters as arguments
cloudferrylib/os/actions/vm_snapshot.py:91: [W0613(unused-argument), VmRestore.run] Unused argument 'args'
************* Module cloudferrylib.scheduler.namespace
cloudferrylib/scheduler/namespace.py:26: [W0232(no-init), ConvertNamespace] Class has no __init__ method
cloudferrylib/scheduler/namespace.py:81: [W0102(dangerous-default-value), Namespace.__init__] Dangerous default value {} as argument
cloudferrylib/scheduler/namespace.py:92: [W0102(dangerous-default-value), Namespace.snapshot] Dangerous default value [] as argument
cloudferrylib/scheduler/namespace.py:117: [E1101(no-member), Namespace.restore] Instance of 'object' has no 'iteritems' member
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', should be 'cloud.cloud_ferry'
cloud/os2os.py:107: [W0221(arguments-differ), OS2OSFerry.migrate] Arguments number differs from overridden 'migrate' method
cloud/os2os.py:162: [W0621(redefined-outer-name), OS2OSFerry.check_cloud] Redefining name 'cloud' from outer scope (line 16)
************* Module cloudferrylib.scheduler.scheduler
cloudferrylib/scheduler/scheduler.py:23: [W0403(relative-import), ] Relative import 'cursor', should be 'cloudferrylib.scheduler.cursor'
cloudferrylib/scheduler/scheduler.py:24: [W0403(relative-import), ] Relative import 'signal_handler', should be 'cloudferrylib.scheduler.signal_handler'
cloudferrylib/scheduler/scheduler.py:25: [W0403(relative-import), ] Relative import 'task', should be 'cloudferrylib.scheduler.task'
cloudferrylib/scheduler/scheduler.py:26: [W0403(relative-import), ] Relative import 'thread_tasks', should be 'cloudferrylib.scheduler.thread_tasks'
cloudferrylib/scheduler/scheduler.py:57: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'task'
cloudferrylib/scheduler/scheduler.py:57: [W0613(unused-argument), BaseScheduler.event_error_task] Unused argument 'e'
cloudferrylib/scheduler/scheduler.py:75: [W0703(broad-except), BaseScheduler.process_chain] Catching too general exception Exception
cloudferrylib/scheduler/scheduler.py:84: [W0201(attribute-defined-outside-init), BaseScheduler.process_chain] Attribute 'exception' defined outside __init__
cloudferrylib/scheduler/scheduler.py:107: [W0201(attribute-defined-outside-init), BaseScheduler.addCursor] Attribute 'cursor' defined outside __init__
************* Module fabfile
fabfile.py:50: [W0621(redefined-outer-name), migrate] Redefining name 'restore' from outer scope (line 71)
fabfile.py:61: [E1123(unexpected-keyword-arg), migrate] Unexpected keyword argument 'restore' in method call
************* Module cloudferrylib.os.image.glance_image
cloudferrylib/os/image/glance_image.py:224: [W0212(protected-access), GlanceImage.get_ref_image] Access to a protected member _resp of a client class
cloudferrylib/os/image/glance_image.py:304: [W0613(unused-argument), GlanceImage.read_info] Unused argument 'kwargs'
cloudferrylib/os/image/glance_image.py:368: [W0221(arguments-differ), GlanceImage.deploy] Arguments number differs from overridden 'deploy' method
************* Module tests.scheduler.test_scheduler
tests/scheduler/test_scheduler.py:36: [E1136(unsubscriptable-object), SchedulerTestCase.test_start_scheduler] Value 's.event_start_task.call_args' is unsubscriptable
tests/scheduler/test_scheduler.py:38: [E1136(unsubscriptable-object), SchedulerTestCase.test_start_scheduler] Value 's.event_end_task.call_args' is unsubscriptable
************* Module cloudferrylib.os.identity.keystone
cloudferrylib/os/identity/keystone.py:193: [W0221(arguments-differ), KeystoneIdentity.deploy] Arguments number differs from overridden 'deploy' method
************* Module tests.cloudferrylib.os.identity.test_keystone
tests/cloudferrylib/os/identity/test_keystone.py:49: [E1002(super-on-old-class), KeystoneIdentityTestCase.setUp] Use of super on an old style class
tests/cloudferrylib/os/identity/test_keystone.py:214: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:215: [W0212(protected-access), KeystoneIdentityTestCase.test_read_info] Access to a protected member _get_user_roles_cached of a client class
tests/cloudferrylib/os/identity/test_keystone.py:237: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.tenant_create] Unused argument 'kwargs'
tests/cloudferrylib/os/identity/test_keystone.py:242: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.user_create] Unused argument 'kwars'
tests/cloudferrylib/os/identity/test_keystone.py:247: [W0613(unused-argument), KeystoneIdentityTestCase.test_deploy.roles_create] Unused argument 'role_name'
tests/cloudferrylib/os/identity/test_keystone.py:447: [W0212(protected-access), KeystoneClientTestCase.test_adds_region_if_set_in_config] Access to a protected member _get_client_by_creds of a client class
tests/cloudferrylib/os/identity/test_keystone.py:479: [W0212(protected-access), KeystoneClientTestCase.test_does_not_add_region_if_not_set_in_config] Access to a protected member _get_client_by_creds of a client class

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
@mirrorcoder please either close this pull request or rebase if it's still required

**Pull request closed without merging**
