### PR TITLE
CF-288 Documentation

### PR DESCRIPTION
**Pull request by roman-verchikov**
Adds user-oriented documentation for CloudFerry in rst format.

Following topics are described:
 - Generic overview;
 - Installation;
 - Quick start guide;
 - Configuration overview.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
+1 awesome thing. i'll need that auto test's documentation moved for standalone package

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2768/

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2769/

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/2770/

**Pull request merged**
