### PR TITLE
Fixed test for keypairs

### PR DESCRIPTION
**Pull request by ntymtsiv**

### CODE REVIEW

**Comment by realsystem** [comment]
+1

**Comment by miarmak** [comment]
+1

**Comment by ntymtsiv** [comment]
devlab/utils/clean_run.sh should be included in jenkins job for functional tests

**Comment by roman-verchikov** [comment]
I'm assuming this is still not working?

**Comment by ntymtsiv** [comment]
Is blocked by SAIC-429

**Comment by plomakin** [comment]
Duplicated with https://github.com/MirantisWorkloadMobility/CloudFerry/pull/483, please remove.

**Pull request closed without merging**
