### PR TITLE
Small fixes in config template for devlab.

### PR DESCRIPTION
**Pull request by plomakin**
Fixed path to public key.
Fixed temp paths on SRC and DST clouds.

### CODE REVIEW

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
**Build Log**
*last 5 lines*

 ```
[...truncated 801 lines...]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:397)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 13 more
```
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
**Build Log**
*last 5 lines*

 ```
[...truncated 799 lines...]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:397)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 13 more
```
Functional test failure

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by roman-verchikov** [comment]
This fix looks more like a bug in the code. There's a need to replace `src_temp + tmpfile` with `sys.path.join(src_temp, tmpfile)` somewhere in the code.

**Comment by Wasapl** [comment]
Build finished.
Functional test success

**Comment by Wasapl** [comment]
Functional test success

**Comment by Wasapl** [comment]
Build finished.
Functional test success

**Comment by Wasapl** [comment]
Functional test success

**Comment by roman-verchikov** [comment]
Fixed in #217

**Pull request closed without merging**
