### PR TITLE
SAIC-753 Add allowed_address_pairs migration

### PR DESCRIPTION
**Pull request by antonf**

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Can one of the admins verify this patch?

**Comment by MirantisWorkloadMobility** [comment]
Can one of the admins verify this patch?

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.prepare_networks
cloudferrylib/os/actions/prepare_networks.py:17: [W0611(unused-import), ] Unused exceptions imported from neutronclient.common as neutronclient_exceptions
************* Module cloudferrylib.os.actions.filter_similar_vms_from_dst
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:45: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:50: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:63: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'dst_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:39: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'tenant_id_to_new_id' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:65: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'similar_isntances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:38: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'src_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:66: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'conflict_instances' defined outside __init__
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:742: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:180: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:285: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:302: [W0631(undefined-loop-variable), NeutronNetwork.create_port] Using possibly undefined loop variable 'ip'
cloudferrylib/os/network/neutron.py:811: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
cloudferrylib/os/network/neutron.py:915: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_vips] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:940: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_members] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:971: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_monitors] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:1032: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_pools] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1742/

**Comment by MirantisWorkloadMobility** [comment]
Can one of the admins verify this patch?

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.filter_similar_vms_from_dst
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:45: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:50: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:63: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'dst_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:39: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'tenant_id_to_new_id' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:65: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'similar_isntances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:38: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'src_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:66: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'conflict_instances' defined outside __init__
************* Module cloudferrylib.os.actions.prepare_networks
cloudferrylib/os/actions/prepare_networks.py:143: [W0612(unused-variable), CreatePortsForVRRP.run] Unused variable 'id_inst'
cloudferrylib/os/actions/prepare_networks.py:17: [W0611(unused-import), ] Unused exceptions imported from neutronclient.common as neutronclient_exceptions
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:745: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:180: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:285: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:303: [W0631(undefined-loop-variable), NeutronNetwork.create_port] Using possibly undefined loop variable 'ip'
cloudferrylib/os/network/neutron.py:813: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
cloudferrylib/os/network/neutron.py:917: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_vips] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:942: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_members] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:973: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_monitors] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:1034: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_pools] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1749/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.filter_similar_vms_from_dst
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:45: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:50: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:63: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'dst_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:39: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'tenant_id_to_new_id' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:65: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'similar_isntances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:38: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'src_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:66: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'conflict_instances' defined outside __init__
************* Module cloudferrylib.os.actions.prepare_networks
cloudferrylib/os/actions/prepare_networks.py:143: [W0612(unused-variable), CreatePortsForVRRP.run] Unused variable 'id_inst'
cloudferrylib/os/actions/prepare_networks.py:17: [W0611(unused-import), ] Unused exceptions imported from neutronclient.common as neutronclient_exceptions
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:745: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:180: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:285: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:303: [W0631(undefined-loop-variable), NeutronNetwork.create_port] Using possibly undefined loop variable 'ip'
cloudferrylib/os/network/neutron.py:813: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
cloudferrylib/os/network/neutron.py:917: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_vips] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:942: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_members] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:973: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_monitors] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:1034: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_pools] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1750/

**Comment by archyufa** [comment]
Please add act_create_vrrp_ports stage migrate_vms.yaml.

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.filter_similar_vms_from_dst
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:45: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:50: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:63: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'dst_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:39: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'tenant_id_to_new_id' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:65: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'similar_isntances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:38: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'src_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:66: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'conflict_instances' defined outside __init__
************* Module cloudferrylib.os.actions.prepare_networks
cloudferrylib/os/actions/prepare_networks.py:150: [W0612(unused-variable), CreatePortsForVRRP.run] Unused variable 'id_inst'
cloudferrylib/os/actions/prepare_networks.py:17: [W0611(unused-import), ] Unused exceptions imported from neutronclient.common as neutronclient_exceptions
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:745: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:180: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:285: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:303: [W0631(undefined-loop-variable), NeutronNetwork.create_port] Using possibly undefined loop variable 'ip'
cloudferrylib/os/network/neutron.py:813: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
cloudferrylib/os/network/neutron.py:917: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_vips] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:942: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_members] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:973: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_monitors] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:1034: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_pools] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1770/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.filter_similar_vms_from_dst
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:45: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:50: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:63: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'dst_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:39: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'tenant_id_to_new_id' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:65: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'similar_isntances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:38: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'src_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:66: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'conflict_instances' defined outside __init__
************* Module cloudferrylib.os.actions.prepare_networks
cloudferrylib/os/actions/prepare_networks.py:150: [W0612(unused-variable), CreatePortsForVRRP.run] Unused variable 'id_inst'
cloudferrylib/os/actions/prepare_networks.py:17: [W0611(unused-import), ] Unused exceptions imported from neutronclient.common as neutronclient_exceptions
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:745: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:180: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:285: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:303: [W0631(undefined-loop-variable), NeutronNetwork.create_port] Using possibly undefined loop variable 'ip'
cloudferrylib/os/network/neutron.py:813: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
cloudferrylib/os/network/neutron.py:917: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_vips] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:942: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_members] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:973: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_monitors] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:1034: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_pools] Specify string format arguments as logging function parameters

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1773/

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.filter_similar_vms_from_dst
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:45: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:50: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:63: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'dst_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:39: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'tenant_id_to_new_id' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:65: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'similar_isntances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:38: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'src_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:66: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'conflict_instances' defined outside __init__
************* Module cloudferrylib.os.actions.prepare_networks
cloudferrylib/os/actions/prepare_networks.py:150: [W0612(unused-variable), CreatePortsForVRRP.run] Unused variable 'id_inst'
cloudferrylib/os/actions/prepare_networks.py:17: [W0611(unused-import), ] Unused exceptions imported from neutronclient.common as neutronclient_exceptions
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:745: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'
************* Module cloudferrylib.os.network.neutron
cloudferrylib/os/network/neutron.py:180: [W0221(arguments-differ), NeutronNetwork.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/network/neutron.py:285: [W0221(arguments-differ), NeutronNetwork.create_port] Arguments number differs from overridden 'create_port' method
cloudferrylib/os/network/neutron.py:303: [W0631(undefined-loop-variable), NeutronNetwork.create_port] Using possibly undefined loop variable 'ip'
cloudferrylib/os/network/neutron.py:813: [W0221(arguments-differ), NeutronNetwork.get_security_groups] Arguments number differs from overridden 'get_security_groups' method
cloudferrylib/os/network/neutron.py:917: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_vips] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:942: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_members] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:973: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_monitors] Specify string format arguments as logging function parameters
cloudferrylib/os/network/neutron.py:1034: [W1201(logging-not-lazy), NeutronNetwork.upload_lb_pools] Specify string format arguments as logging function parameters

**Comment by archyufa** [comment]
+1 tested in staging

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
