### PR TITLE
[CF-399] Print configuration, filter and scenario

### PR DESCRIPTION
**Pull request by SVilgelm**
Remove PrintInfo actions.
Print configuration, filter and scenario into log with DEBUG level.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
#985 should be merged before this

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
It's tested http://jenkins-cf.vm.mirantis.net:8080/view/svilgelm/job/cloudferry-functional-tests-grizzly-to-juno-test-svilgelm/64

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
can be merged

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
