### PR TITLE
[SAIC-802] Avoid extra getting an external ip from instances

### PR DESCRIPTION
**Pull request by SVilgelm**
Get only ids of instances instead of getting full information
in check_networks action.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.filter_similar_vms_from_dst
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:45: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:50: [W1201(logging-not-lazy), FilterSimilarVMsFromDST.run] Specify string format arguments as logging function parameters
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:65: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'dst_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:39: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'tenant_id_to_new_id' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:67: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'similar_isntances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:38: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.run] Attribute 'src_instances' defined outside __init__
cloudferrylib/os/actions/filter_similar_vms_from_dst.py:68: [W0201(attribute-defined-outside-init), FilterSimilarVMsFromDST.find_similar_instances] Attribute 'conflict_instances' defined outside __init__
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:766: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:766: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by aguzikova** [comment]
s/Awoid/Avoid/ )

**Comment by SVilgelm** [comment]
@aguzikova Done

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:767: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:767: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.compute.nova_compute
cloudferrylib/os/compute/nova_compute.py:767: [E0602(undefined-variable), NovaCompute.change_status.<lambda>.<lambda>] Undefined variable 'status'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1, can be merged

**Pull request merged**
