### PR TITLE
SAIC-672 Support JSON and human output for qemu-img

### PR DESCRIPTION
**Pull request by roman-verchikov**
Support older versions of qemu-img as well as newer. More recent
versions of qemu-img (v2.0.0) come with support for JSON output,
which is not available in the older versions.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
+1, I've tested this patch on devlab with #572, works good for qemu v1 and for qemu v2.

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
