### PR TITLE
Remove identity from glance with no rollback stage

### PR DESCRIPTION
**Pull request by archyufa**
This patch removes act_identity_trans task from scenario/stages_without_rollback/3_get_and_transfer_images.yaml.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
I'm not sure that the image's migration will work correctly with this patch.

**Comment by miarmak** [comment]
It works. At least in my devlab) And also I've not seen any dependencies in the code. Except of `2_identity_transporter.yaml` step (scenario) anyway should be done before this one.

And also it seems `migrate_vms.yaml` step also does not need `act_identity_trans` action inside of it anymore. In devlab it works fine without it.

**Comment by SVilgelm** [comment]
:+1: can be merged

**Pull request merged**
