### PR TITLE
CF-259 Add VM to generate_load with deleted image.

### PR DESCRIPTION
**Pull request by plomakin**
Added new VM to generate_load.py script with deleted image. Image
 should be deleted correctly via glance API.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:600: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:674: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module devlab.generate_load
devlab/generate_load.py:600: [E1101(no-member), 
Prerequisites.create_security_group] Instance of 'dict' has no 'id' member
devlab/generate_load.py:674: [E1101(no-member), 
Prerequisites.create_cinder_volumes] Instance of 'dict' has no 'id' member

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
looks good, +1

**Comment by SVilgelm** [comment]
:+1: can be merged

**Pull request merged**
