### PR TITLE
Fixed pep8 warnings

### PR DESCRIPTION
**Pull request by realsystem**

### CODE REVIEW

**Comment by miarmak** [comment]
Have you checked `/tests/cloudferrylib/os/compute/test_libvirt.py` also? 
https://github.com/MirantisWorkloadMobility/CloudFerry/blob/devel/tests/cloudferrylib/os/compute/test_libvirt.py

**Comment by realsystem** [comment]
test_libvirt is in the ignore list :)

**Comment by miarmak** [comment]
Hmm... maybe we can move those long strings to separate text files?)

**Comment by realsystem** [comment]
It's a question for QA team.

**Comment by roman-verchikov** [comment]
@realsystem we're all one team, and that particular file was actually submitted by me ;) pep8 can be resolved by simply shortening long lines (remove couple of characters from UUIDs for example), not all of those values are verified.

**Comment by realsystem** [comment]
ok, I'll do

**Comment by roman-verchikov** [comment]
Looks good to me, +1

**Pull request merged**
