### PR TITLE
CF-504 Reduce amount of VMs used for devlab environment.

### PR DESCRIPTION
**Pull request by SVilgelm**
Optimized VM's usage on both SRC and DST.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
the functional tests are passed: http://jenkins-cf.vm.mirantis.net:8080/view/svilgelm/job/cloudferry-functional-tests-grizzly-to-juno-test-svilgelm/95/
👍 can be merged

**Comment by roman-verchikov** [comment]
+1

**Pull request merged**
