### PR TITLE
VM states verification test updated.

### PR DESCRIPTION
**Pull request by VitaliiYerys**
Added required VM statets into config.py, updated generate_load.py
script in order to generate VM in required states, updated
test_vm_migration.py to verify VM state migration.

### CODE REVIEW

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by roman-verchikov** [comment]
Looks good, since fix for this test (#227) is merged, this can be merged too.

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Pull request merged**
