### PR TITLE
CF-385 Unauthorized errors during glance image migration

### PR DESCRIPTION
**Pull request by roman-verchikov**
Keystone sporadically fails with 401 Unauthorized during glance image
migration even though all credentials are correct. Resolved by adding
retries at the point of failure.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
:+1: Did you test it with ZhiBing?

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
