### PR TITLE
CF-562 Add debug logs to generate_load.

### PR DESCRIPTION
**Pull request by plomakin**
Added generate_load.log file and log handler.
Moved couple of constants to config.py
Extended logging in generate_load and base.py

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3832/

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Merge check failed
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/3833/

**Comment by roman-verchikov** [comment]
flake8 failed:
```
cloudferry_devlab/cloudferry_devlab/generate_load.py:996:24: E127 continuation line over-indented for visual indent
```

**Pull request closed without merging**
