### PR TITLE
Optimized config template for devlab.

### PR DESCRIPTION
**Pull request by plomakin**
Updated quota migration default value.
Added 'down'-state host ignoring by default.
Decreased testing file size to check bandwidth.
Removed comments from template.

### CODE REVIEW

**Comment by Wasapl** [comment]
Merged build finished. Test PASSED.

**Comment by roman-verchikov** [comment]
+1

**Comment by miarmak** [comment]
+1

**Comment by roman-verchikov** [comment]
Got two +1s, can be merged.

**Pull request merged**
