### PR TITLE
[CF-552] Attachment object has no 'size' attribute

### PR DESCRIPTION
**Pull request by SVilgelm**
Use Attachment.volume instead of Attachment.

### CODE REVIEW

**Comment by roman-verchikov** [comment]
Please fix typos in commit message:

 - `objet` should be `object`
 - `Attachemetn` should be `Attachment`

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
+1

**Comment by MirantisWorkloadMobility** [comment]
There were no python files updated. Admins, please, check pull request.

**Comment by archyufa** [comment]
+1 tested in staging

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
