### PR TITLE
CF-143 Cleanup unnecessary code

### PR DESCRIPTION
**Pull request by roman-verchikov**
Removes unnecessary code from cinder migration backend

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should 
be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', 
should be 'cloud.cloud_ferry'
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), 
CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:378: [W0613(unused-argument), 
CinderStorage.convert_snapshot] Unused argument 'cloud'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should 
be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', 
should be 'cloud.cloud_ferry'
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), 
CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:378: [W0613(unused-argument), 
CinderStorage.convert_snapshot] Unused argument 'cloud'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
:+1:

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloud.os2os
cloud/os2os.py:16: [W0403(relative-import), ] Relative import 'cloud', should 
be 'cloud.cloud'
cloud/os2os.py:17: [W0403(relative-import), ] Relative import 'cloud_ferry', 
should be 'cloud.cloud_ferry'
************* Module cloudferrylib.os.storage.cinder_storage
cloudferrylib/os/storage/cinder_storage.py:140: [W0221(arguments-differ), 
CinderStorage.deploy] Arguments number differs from overridden 'deploy' method
cloudferrylib/os/storage/cinder_storage.py:380: [W0613(unused-argument), 
CinderStorage.convert_snapshot] Unused argument 'cloud'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by SVilgelm** [comment]
I think you also can remove `CloudFerry/cloudferrylib/os/actions/migrate_volumes.py` and `CloudFerry/cloudferrylib/os/actions/cinder_database_manipulation.py`

**Comment by roman-verchikov** [comment]
@SVilgelm nope, unfortunately those are still required

**Comment by SVilgelm** [comment]
OK. I got it.

**Pull request merged**
