### PR TITLE
CF-601 Disable logging to stdout during functional tests execution.

### PR DESCRIPTION
**Pull request by plomakin**
Added logging handler for functional tests.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Unittests success.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
Unittests success.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
Unittests success.

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by roman-verchikov** [comment]
-1, some tests still print logs to stdout:
```
Validate volume data was migrated correctly. ... 2016-08-11 19:33:10,857 - DEBUG - Running sudo:
 pwd
2016-08-11 19:33:11,772 - DEBUG - Fabric sudo output:
 /home/cirros
2016-08-11 19:33:11,773 - DEBUG - Running sudo:
 [ -d /tmp/mount_here/ ]
2016-08-11 19:33:12,118 - DEBUG - Fabric sudo output:
 
2016-08-11 19:33:12,119 - DEBUG - Running sudo:
 mount /dev/vdb /tmp/mount_here/
2016-08-11 19:33:12,369 - DEBUG - Fabric sudo output:
 mount: mounting /dev/vdb on /tmp/mount_here/ failed: Device or resource busy
2016-08-11 19:33:12,370 - DEBUG - Running sudo:
 md5sum /tmp/mount_here/test_data.txt
2016-08-11 19:33:12,946 - DEBUG - Fabric sudo output:
 a4e5df9a5e9ed035ea519190872b8d8f  /tmp/mount_here/test_data.txt
...
```

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/29/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/31/

**Comment by MirantisWorkloadMobility** [comment]
Some checks failed.
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry%20checks/38/

**Comment by plomakin** [comment]
retest

**Comment by MirantisWorkloadMobility** [comment]
All checks successful.

**Comment by roman-verchikov** [comment]
+1

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
