### PR TITLE
[SAIC-442] FloatingIP migration creates another IPs on dst

### PR DESCRIPTION
**Pull request by Settis**
Steps for FloatingIP migration:
- Allocate FloatingIP on dst
- Change FloatingIP in database:
 - Change IP in `floatingips` table
 - Change IP in `ipallocations` table *(added in this patch)*
- Delete related rows from `ipavailabilityranges` table for avoid FloatingIP duplication *(added in this patch)*

### CODE REVIEW

**Comment by roman-verchikov** [comment]
Looks good, but before we merge this, please make sure the following scenario works:

1. On source cloud:
 1.1 Create 10 floating IPs
 1.2 Create 3 VMs
 1.3 Associate random floating IPs with VMs
2. Run Migration
3. Verify all VMs are associated with correct floating IPs
4. Create all possible floating IPs on dest
5. Make sure created floating IPs do not overlap with those associated with VMs

**Comment by Settis** [comment]
Test it manually. It works fine except case when router catch FloatingIP. But this case resolved in https://github.com/MirantisWorkloadMobility/CloudFerry/pull/309.

**Comment by mirrorcoder** [comment]
Conflicts

**Comment by roman-verchikov** [comment]
please address
```
DEBUG    [/home/vagrant/CloudFerry/cloudferrylib/os/network/neutron.py : lineno 1204]  09-15 00:56:01  ['UPDATE floatingips SET floating_ip_address = "192.168.1.101" WHERE id = "6a55e3cb-9cfd-4a50-a24e-8c86a86c5948"', 'UPDATE ipallocations SET ip_address = "192.168.1.101" WHERE port_id = (SELECT floating_port_id FROM floatingips WHERE id = "6a55e3cb-9cfd-4a50-a24e-8c86a86c5948")', 'DELETE FROM ipavailabilityranges WHERE allocation_pool_id in ( SELECT id FROM ipallocationpools WHERE subnet_id = ( SELECT subnet_id FROM ipallocations WHERE port_id = (SELECT floating_port_id FROM floatingips WHERE id = "6a55e3cb-9cfd-4a50-a24e-8c86a86c5948")))']
ERROR    [/home/vagrant/CloudFerry/cloudferrylib/scheduler/scheduler.py : lineno 58]  09-15 00:56:01  BaseTask|NetworkTransporter TASK FAILED
Traceback (most recent call last):
  File "/home/vagrant/CloudFerry/cloudferrylib/scheduler/scheduler.py", line 71, in process_chain
    self.run_task(task)
  File "/home/vagrant/CloudFerry/cloudferrylib/scheduler/scheduler.py", line 63, in run_task
    self.map_func_task[task](task)
  File "/home/vagrant/CloudFerry/cloudferrylib/scheduler/scheduler.py", line 94, in task_run
    task(namespace=self.namespace)
  File "/home/vagrant/CloudFerry/cloudferrylib/scheduler/task.py", line 96, in __call__
    result = self.run(**namespace.vars)
  File "/home/vagrant/CloudFerry/cloudferrylib/os/actions/networks_transporter.py", line 27, in run
    dst_resource.deploy(info)
  File "/home/vagrant/CloudFerry/cloudferrylib/os/network/neutron.py", line 111, in deploy
    deploy_info['floating_ips'])
  File "/home/vagrant/CloudFerry/cloudferrylib/os/network/neutron.py", line 1205, in upload_floatingips
    dst_mysql = self.get_db_connection()
AttributeError: 'NeutronNetwork' object has no attribute 'get_db_connection'
```

**Comment by roman-verchikov** [comment]
+1, can be merged.

**Pull request merged**
