### PR TITLE
SAIC-285 generate_config does not have error_exit defined

### PR DESCRIPTION
**Pull request by roman-verchikov**
This patch defines error_exit function to produce correct error for
invalid user input.

### CODE REVIEW

**Comment by Wasapl** [comment]
Build finished.
Unittest success

**Comment by Wasapl** [comment]
Unittest success

**Comment by Wasapl** [comment]
Build finished.
Functional test failure

**Comment by Wasapl** [comment]
Functional test failure

**Comment by roman-verchikov** [comment]
Minor change for the devlab, can be merged.

**Pull request merged**
