### PR TITLE
[SAIC-793] Improve keypairs migration speed.

### PR DESCRIPTION
**Pull request by abochkarev**
Added functionality which allows to search destination user by source user only one time. It should help to reduce time of keypairs migration.

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.transport_compute_resources
cloudferrylib/os/actions/transport_compute_resources.py:83: [W0613(unused-argument), TransportKeyPairs.__init__] Unused argument 'kwargs'
cloudferrylib/os/actions/transport_compute_resources.py:120: [W0613(unused-argument), SetKeyPairsForInstances.__init__] Unused argument 'kwargs'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1851/

**Comment by roman-verchikov** [comment]
+1

**Comment by ntymtsiv** [comment]
retest this please

**Comment by MirantisWorkloadMobility** [comment]
Consider resolving pylint issues: \
``` \
************* Module cloudferrylib.os.actions.transport_compute_resources
cloudferrylib/os/actions/transport_compute_resources.py:83: [W0613(unused-argument), TransportKeyPairs.__init__] Unused argument 'kwargs'
cloudferrylib/os/actions/transport_compute_resources.py:120: [W0613(unused-argument), SetKeyPairsForInstances.__init__] Unused argument 'kwargs'

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success

**Comment by ntymtsiv** [comment]
With patch keypairs are migrated almost in two times faster. I tested on devlab, with 4400 users, and each user has two keys (if user has more keys, it should be even faster)

**Comment by roman-verchikov** [comment]
can be merged

**Pull request merged**
