### PR TITLE
Fix for saic 599

### PR DESCRIPTION
**Pull request by raiesmh08**
Missing quotation marks in task defined in tasks.yaml

Line 110 in scenario/tasks.yaml should be changed from:
verify_vms: ['VerifyVms', src_cloud]
to
verify_vms: ['VerifyVms', 'src_cloud']

### CODE REVIEW

**Comment by MirantisWorkloadMobility** [comment]
Pylint check succeeded

**Comment by MirantisWorkloadMobility** [comment]
PEP8 check success, Unittests success
http://jenkins-cf.vm.mirantis.net:8080/job/cloudferry-unittests-and-style-checks/1410/

**Comment by MirantisWorkloadMobility** [comment]
Functional test success for Grizzly to Icehouse migration

**Comment by MirantisWorkloadMobility** [comment]
Functional test success for Grizzly to Juno migration

**Comment by MirantisWorkloadMobility** [comment]
Functional test success for Icehouse to Juno migration

**Comment by roman-verchikov** [comment]
Please leave only necessary commit - remove commit related to SAIC-603

**Pull request closed without merging**
